import {makeSampleProject,ensureVersionStore} from './core.mjs';
import {acceptAICandidate,createLocalDemoProvider,ensureAIStore,requestAICandidates,rejectAICandidate} from './ai-engine.mjs';
const KEY='engineering-design-graph-project-v2';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function load(){try{return ensureAIStore(ensureVersionStore(JSON.parse(localStorage.getItem(KEY))||makeSampleProject()))}catch{return ensureAIStore(makeSampleProject())}}
let project=load();
function save(){localStorage.setItem(KEY,JSON.stringify(project))}
function render(){const reqs=project.artifacts.filter(a=>a.type==='requirement');const pending=project.aiCandidates.filter(c=>c.status==='pending'||c.status==='edited');$('#aiMain').innerHTML=`<header><div><h1>AI Candidate Review</h1><p>AI output never writes the current artifact directly. Accept stages a ChangeSet for Preview / Validation / Apply.</p></div><a class="button" href="./">Back to Design Graph</a></header><section><label>Requirement<select id="target">${reqs.map(a=>`<option value="${a.id}">${esc(a.key)} — ${esc(a.title)}</option>`).join('')}</select></label><button id="generate">Generate review candidate</button></section><section><h2>Pending candidates</h2><div class="cards">${pending.length?pending.map(c=>`<article data-candidate="${c.id}"><b>${esc(c.operation)} · confidence ${Math.round(c.confidence*100)}%</b><h3>${esc(c.proposedTitle||project.artifacts.find(a=>a.id===c.targetArtifactId)?.key||c.proposedType||'Candidate')}</h3><p>Knowledge: ${esc(c.knowledgeState)} · Provider: ${esc(c.provenance.provider)}</p><pre style="white-space:pre-wrap">${esc(JSON.stringify(c.proposedPayload,null,2))}</pre><button data-accept="${c.id}">Accept to ChangeSet</button> <button data-reject="${c.id}">Reject</button></article>`).join(''):'<article><h3>No pending candidates</h3></article>'}</div></section><section><h2>History</h2><p>${project.aiCandidates.length} candidate(s) · ${project.aiRequests.length} request(s)</p></section>`;$('#generate').onclick=generate;document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>{acceptAICandidate(project,b.dataset.accept);save();render()});document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>{rejectAICandidate(project,b.dataset.reject,{reason:'Rejected in review UI'});save();render()})}
async function generate(){const target=$('#target').value;await requestAICandidates(project,{role:'requirement_reviewer',targetArtifactId:target,provider:createLocalDemoProvider()});save();render()}
render();
