import {ARTIFACT_TYPES,RELATION_TYPES,STATUSES,addChangeItem,applyChangeSet,artifactByKey,buildImplementationPackage,byId,createChangeSet,ensureVersionStore,impact,makeSampleProject,previewChangeSet,readiness,requirementCoverage,runValidation,validateRelation,validationSummary} from './core.mjs';
const KEY='engineering-design-graph-project-v2';
let project=load(),selected=project.artifacts[0]?.id||null,view='overview';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function load(){try{return ensureVersionStore(JSON.parse(localStorage.getItem(KEY))||makeSampleProject())}catch{return makeSampleProject()}}
function save(){localStorage.setItem(KEY,JSON.stringify(project))} function typeLabel(t){return t[0].toUpperCase()+t.slice(1)}
function openChangeSet(){let cs=project.changeSets.find(c=>c.status==='open');if(!cs)cs=createChangeSet(project,'Working changes');return cs}
function render(){renderNav();renderMain();renderInspector()}
function renderNav(){const s=validationSummary(project),open=project.changeSets.filter(c=>c.status==='open').reduce((n,c)=>n+c.items.length,0);$('#nav').innerHTML=`<div class="brand"><b>Design Graph</b><small>${esc(project.name)} · r${project.revision}</small></div><button data-view="overview">Overview</button>${ARTIFACT_TYPES.filter(t=>!['decision','question','source'].includes(t)).map(t=>`<button data-view="${t}">${typeLabel(t)}s <span>${project.artifacts.filter(a=>a.type===t).length}</span></button>`).join('')}<button data-view="graph">Graph</button><button data-view="validation">Validation <span>${s.total}</span></button><button data-view="readiness">Readiness</button><button data-view="changes">ChangeSets <span>${open}</span></button>`;$('#nav').querySelectorAll('button').forEach(b=>{if(b.dataset.view===view)b.classList.add('active');b.onclick=()=>{view=b.dataset.view;render()}})}
function tableRows(arts){const issues=runValidation(project);return arts.map(a=>`<tr data-id="${a.id}"><td><b>${esc(a.key)}</b><small>v${a.version} · ${esc(a.type)}</small></td><td>${esc(a.title)}${a.reviewRequired?' <small>review required</small>':''}</td><td><span class="pill ${a.status}">${esc(a.status)}</span></td><td>${esc(a.knowledgeState)}</td><td>${issues.filter(i=>i.artifactIds.includes(a.id)).length}</td><td>${a.type==='requirement'?requirementCoverage(project,a).score+'%':'—'}</td></tr>`).join('')}
function wireRows(){document.querySelectorAll('#main tbody tr[data-id]').forEach(r=>r.onclick=()=>{selected=r.dataset.id;renderInspector()})}
function renderMain(){const map=byId(project);if(view==='overview'){const rd=readiness(project),vs=validationSummary(project);$('#main').innerHTML=`<header><div><h1>${esc(project.name)}</h1><p>Versioned design repository / traceability / deterministic validation / readiness</p></div><div class="toolbar"><button id="reset">Reset sample</button><button id="export">Export JSON</button><label class="button">Import JSON<input id="import" type="file" accept="application/json"></label></div></header><section class="metrics"><article><small>Artifacts</small><strong>${project.artifacts.length}</strong></article><article><small>Versions</small><strong>${project.artifactVersions.length}</strong></article><article><small>Validation</small><strong>${vs.total}</strong></article><article><small>Readiness</small><strong>${rd.status}</strong></article></section><section><h2>Artifacts</h2><table><thead><tr><th>Key</th><th>Title</th><th>Status</th><th>Knowledge</th><th>Issues</th><th>Coverage</th></tr></thead><tbody>${tableRows(project.artifacts)}</tbody></table></section>`;wireRows();$('#reset').onclick=()=>{project=makeSampleProject();selected=project.artifacts[0].id;save();render()};$('#export').onclick=()=>download('engineering-design-graph-project.json',project);$('#import').onchange=importJson;return}
if(ARTIFACT_TYPES.includes(view)){const arts=project.artifacts.filter(a=>a.type===view);$('#main').innerHTML=`<header><div><h1>${typeLabel(view)}s</h1><p>${arts.length} artifacts</p></div><button id="addArtifact">+ Stage artifact</button></header><table><thead><tr><th>Key</th><th>Title</th><th>Status</th><th>Knowledge</th><th>Issues</th><th>Coverage</th></tr></thead><tbody>${tableRows(arts)}</tbody></table>`;wireRows();$('#addArtifact').onclick=()=>addArtifact(view);return}
if(view==='validation'){const s=validationSummary(project);$('#main').innerHTML=`<header><div><h1>Validation</h1><p>${s.total} issues · score ${s.score}/100</p></div></header><section class="metrics"><article><small>Critical</small><strong>${s.critical}</strong></article><article><small>Errors</small><strong>${s.errors}</strong></article><article><small>Warnings</small><strong>${s.warnings}</strong></article></section><div class="cards">${s.issues.length?s.issues.map(i=>`<article class="issue ${i.severity}" data-id="${i.artifactIds[0]}"><b>${i.ruleId} · ${i.severity} · ${i.category}</b><h3>${esc(i.title)}</h3><p>${esc(i.message)}</p><small>${i.artifactIds.map(id=>map.get(id)?.key||id).join(', ')}</small></article>`).join(''):'<article><h3>No issues</h3></article>'}</div>`;document.querySelectorAll('#main [data-id]').forEach(x=>x.onclick=()=>{selected=x.dataset.id;renderInspector()});return}
if(view==='readiness'){const r=readiness(project);$('#main').innerHTML=`<header><div><h1>Implementation Readiness</h1><p>Deterministic implementation gate</p></div><button id="pkg">Export task package</button></header><section class="readiness ${r.status.toLowerCase()}"><small>STATUS</small><strong>${r.status}</strong><span>${r.score}/100</span></section><section><h2>Blocking checks</h2>${r.blocking.length?`<ul>${r.blocking.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>All blocking checks passed.</p>'}</section>`;$('#pkg').onclick=exportPackage;return}
if(view==='graph'){const rows=project.relations.filter(r=>r.status!=='deprecated').map(r=>`<tr data-id="${r.fromArtifactId}"><td>${esc(map.get(r.fromArtifactId)?.key)}</td><td><span class="pill">${esc(r.type)}</span></td><td>${esc(map.get(r.toArtifactId)?.key)}</td></tr>`).join('');$('#main').innerHTML=`<header><div><h1>Traceability Graph</h1><p>Relations are first-class entities</p></div><button id="addRelation">+ Stage relation</button></header><table><thead><tr><th>From</th><th>Relation</th><th>To</th></tr></thead><tbody>${rows}</tbody></table>`;$('#addRelation').onclick=addRelation;wireRows();return}
if(view==='changes'){const css=project.changeSets.slice().reverse();$('#main').innerHTML=`<header><div><h1>ChangeSets</h1><p>Stage → Preview → atomic Apply</p></div></header><div class="cards">${css.map(cs=>{let p=null;try{if(cs.status==='open')p=previewChangeSet(project,cs.id)}catch{}return `<article><b>${esc(cs.status)} · base r${cs.baseRevision}</b><h3>${esc(cs.title)}</h3><p>${cs.items.length} item(s)${p?` · ${p.impacted.length} impacted · ${p.validation.total} validation issues · ${p.readiness.status}`:''}</p>${cs.status==='open'?`<button data-preview="${cs.id}">Preview</button> <button data-apply="${cs.id}">Apply</button>`:''}</article>`}).join('')||'<article><h3>No ChangeSets</h3></article>'}</div><div id="changePreview"></div>`;document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>showPreview(b.dataset.preview));document.querySelectorAll('[data-apply]').forEach(b=>b.onclick=()=>applyCS(b.dataset.apply));return}}
function renderInspector(){const a=project.artifacts.find(x=>x.id===selected);if(!a){$('#inspector').innerHTML='<p>Select an artifact</p>';return}const map=byId(project),related=project.relations.filter(r=>r.status!=='deprecated'&&(r.fromArtifactId===a.id||r.toArtifactId===a.id)),issues=runValidation(project).filter(i=>i.artifactIds.includes(a.id)),imp=impact(project,a.id);$('#inspector').innerHTML=`<div class="inspector-head"><small>${esc(a.type)} · v${a.version}</small><h2>${esc(a.key)}</h2><h3>${esc(a.title)}</h3></div><label>Status<select id="status">${STATUSES.map(x=>`<option ${x===a.status?'selected':''}>${x}</option>`).join('')}</select></label><label>Knowledge<select id="knowledge">${['known','assumed','proposed','undefined'].map(x=>`<option ${x===a.knowledgeState?'selected':''}>${x}</option>`).join('')}</select></label><label>Title<input id="title" value="${esc(a.title)}"></label><label>Payload JSON<textarea id="payload">${esc(JSON.stringify(a.payload,null,2))}</textarea></label><button id="saveArtifact">Stage update</button><hr><h3>Relations</h3>${related.map(r=>`<div class="relation"><small>${esc(r.type)}</small><b>${esc(map.get(r.fromArtifactId===a.id?r.toArtifactId:r.fromArtifactId)?.key)}</b></div>`).join('')||'<p>None</p>'}<h3>Validation</h3>${issues.map(i=>`<div class="mini-issue ${i.severity}">${esc(i.ruleId)} ${esc(i.title)}</div>`).join('')||'<p>No issues</p>'}<h3>Downstream impact</h3>${imp.slice(0,8).map(x=>`<div class="relation"><small>${x.classification} · ${x.score}</small><b>${esc(x.artifact?.key)}</b></div>`).join('')||'<p>None</p>'}`;$('#saveArtifact').onclick=()=>{try{const cs=openChangeSet();addChangeItem(cs,{kind:'update_artifact',artifactId:a.id,expectedRevision:a.revision||1,previousStatus:a.status,patch:{title:$('#title').value.trim(),status:$('#status').value,knowledgeState:$('#knowledge').value,payload:JSON.parse($('#payload').value)}});save();view='changes';render()}catch(e){alert(e.message)}}}
function addArtifact(type){const key=prompt('Artifact key');if(!key)return;if(artifactByKey(project,key)){alert('Key already exists');return}const title=prompt('Title')||key,id=crypto.randomUUID(),t=new Date().toISOString(),a={id,projectId:project.id,key,type,title,status:'draft',knowledgeState:'undefined',version:1,revision:1,currentVersionId:id+'-v1',tags:[],sourceIds:[],metadata:{},payload:{},createdAt:t,updatedAt:t};addChangeItem(openChangeSet(),{kind:'create_artifact',artifact:a});save();view='changes';render()}
function addRelation(){const fk=prompt('From artifact key'),tk=prompt('To artifact key'),type=prompt('Relation type\n'+RELATION_TYPES.join(', ')),from=artifactByKey(project,fk),to=artifactByKey(project,tk);if(!from||!to){alert('Artifact key not found');return}const t=new Date().toISOString(),r={id:crypto.randomUUID(),projectId:project.id,fromArtifactId:from.id,toArtifactId:to.id,type,status:'active',source:'human',createdAt:t,updatedAt:t},vr=validateRelation(project,r);if(!vr.ok){alert(vr.error);return}addChangeItem(openChangeSet(),{kind:'create_relation',relation:r});save();view='changes';render()}
function showPreview(id){try{const p=previewChangeSet(project,id);$('#changePreview').innerHTML=`<section><h2>Impact preview</h2><p>${p.impacted.length} impacted · validation ${p.validation.total} · readiness ${p.readiness.status}</p><div class="cards">${p.impacted.map(x=>`<article><b>${esc(x.classification)} · ${x.score}</b><h3>${esc(x.artifact?.key)}</h3><small>${esc(x.relationType)} · depth ${x.depth}</small></article>`).join('')||'<article><h3>No downstream impact</h3></article>'}</div></section>`}catch(e){alert(e.message)}}
function applyCS(id){try{applyChangeSet(project,id);save();render()}catch(e){alert(e.message)}}
function exportPackage(){const task=project.artifacts.find(a=>a.type==='task');if(!task){alert('Task not found');return}try{const pkg=buildImplementationPackage(project,[task.id]);save();download(`${task.key}-implementation-package.json`,pkg)}catch(e){alert(e.message)}}
function download(name,data){const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function importJson(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!Array.isArray(p.artifacts)||!Array.isArray(p.relations))throw new Error('artifacts/relations required');project=ensureVersionStore(p);selected=project.artifacts[0]?.id||null;save();render()}catch(err){alert(err.message)}};r.readAsText(f)}
render();
