import {ARTIFACT_TYPES,RELATION_TYPES,artifactByKey,byId,impact,makeSampleProject,readiness,requirementCoverage,runValidation,validateRelation} from './core.mjs';
const KEY='engineering-design-graph-project-v1';
let project=load(); let selected=project.artifacts[0]?.id||null; let view='overview';
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function load(){try{return JSON.parse(localStorage.getItem(KEY))||makeSampleProject()}catch{return makeSampleProject()}}
function save(){localStorage.setItem(KEY,JSON.stringify(project));}
function typeLabel(t){return t[0].toUpperCase()+t.slice(1)}
function render(){renderNav(); renderMain(); renderInspector();}
function renderNav(){ const issues=runValidation(project); $('#nav').innerHTML=`<div class="brand"><b>Design Graph</b><small>${esc(project.name)}</small></div><button data-view="overview">Overview</button>${ARTIFACT_TYPES.filter(t=>!['decision','question','source'].includes(t)).map(t=>`<button data-view="${t}">${typeLabel(t)}s <span>${project.artifacts.filter(a=>a.type===t).length}</span></button>`).join('')}<button data-view="graph">Graph</button><button data-view="validation">Validation <span>${issues.length}</span></button><button data-view="readiness">Readiness</button><button data-view="changes">Changes <span>${project.changes?.length||0}</span></button>`; $('#nav').querySelectorAll('button').forEach(b=>{if(b.dataset.view===view)b.classList.add('active'); b.onclick=()=>{view=b.dataset.view; render();}})}
function tableRows(arts){return arts.map(a=>{const cov=a.type==='requirement'?requirementCoverage(project,a).score+'%':'—'; return `<tr data-id="${a.id}"><td><b>${esc(a.key)}</b><small>${esc(a.type)}</small></td><td>${esc(a.title)}</td><td><span class="pill ${a.status}">${esc(a.status)}</span></td><td>${esc(a.knowledgeState)}</td><td>${runValidation(project).filter(i=>i.artifactIds.includes(a.id)).length}</td><td>${cov}</td></tr>`}).join('')}
function renderMain(){ const map=byId(project); if(view==='overview'){const rd=readiness(project); $('#main').innerHTML=`<header><div><h1>${esc(project.name)}</h1><p>Structured design repository / traceability / validation / readiness</p></div><div class="toolbar"><button id="reset">Reset sample</button><button id="export">Export JSON</button><label class="button">Import JSON<input id="import" type="file" accept="application/json"></label></div></header><section class="metrics"><article><small>Artifacts</small><strong>${project.artifacts.length}</strong></article><article><small>Relations</small><strong>${project.relations.length}</strong></article><article><small>Validation</small><strong>${rd.issues.length}</strong></article><article><small>Readiness</small><strong>${rd.status}</strong></article></section><section><h2>Artifacts</h2><table><thead><tr><th>Key</th><th>Title</th><th>Status</th><th>Knowledge</th><th>Issues</th><th>Coverage</th></tr></thead><tbody>${tableRows(project.artifacts)}</tbody></table></section>`; wireRows(); $('#reset').onclick=()=>{project=makeSampleProject(); selected=project.artifacts[0].id; save(); render()}; $('#export').onclick=exportJson; $('#import').onchange=importJson; return; }
if(ARTIFACT_TYPES.includes(view)){ const arts=project.artifacts.filter(a=>a.type===view); $('#main').innerHTML=`<header><div><h1>${typeLabel(view)}s</h1><p>${arts.length} artifacts</p></div><button id="addArtifact">+ Add</button></header><table><thead><tr><th>Key</th><th>Title</th><th>Status</th><th>Knowledge</th><th>Issues</th><th>Coverage</th></tr></thead><tbody>${tableRows(arts)}</tbody></table>`; wireRows(); $('#addArtifact').onclick=()=>addArtifact(view); return; }
if(view==='validation'){const issues=runValidation(project); $('#main').innerHTML=`<header><div><h1>Validation</h1><p>Deterministic validation results</p></div></header><div class="cards">${issues.length?issues.map(i=>`<article class="issue ${i.severity}" data-id="${i.artifactIds[0]}"><b>${i.ruleId} · ${i.severity}</b><h3>${esc(i.title)}</h3><p>${esc(i.message)}</p><small>${i.artifactIds.map(id=>map.get(id)?.key||id).join(', ')}</small></article>`).join(''):'<article><h3>No issues</h3></article>'}</div>`; $('#main').querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>{selected=x.dataset.id; renderInspector()}); return; }
if(view==='readiness'){const r=readiness(project); $('#main').innerHTML=`<header><div><h1>Implementation Readiness</h1><p>Rule-based gate, not an AI opinion</p></div></header><section class="readiness ${r.status.toLowerCase()}"><small>STATUS</small><strong>${r.status}</strong><span>${r.score}/100</span></section><section><h2>Blocking checks</h2>${r.blocking.length?`<ul>${r.blocking.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>All blocking checks passed.</p>'}</section>`; return; }
if(view==='graph'){const rows=project.relations.map(r=>`<tr data-id="${r.fromArtifactId}"><td>${esc(map.get(r.fromArtifactId)?.key)}</td><td><span class="pill">${esc(r.type)}</span></td><td>${esc(map.get(r.toArtifactId)?.key)}</td></tr>`).join(''); $('#main').innerHTML=`<header><div><h1>Traceability Graph</h1><p>Relations are first-class entities</p></div><button id="addRelation">+ Relation</button></header><table><thead><tr><th>From</th><th>Relation</th><th>To</th></tr></thead><tbody>${rows}</tbody></table>`; $('#addRelation').onclick=addRelation; $('#main').querySelectorAll('tr[data-id]').forEach(x=>x.onclick=()=>{selected=x.dataset.id; renderInspector()}); return; }
if(view==='changes'){ $('#main').innerHTML=`<header><div><h1>Working Changes</h1><p>Local change set</p></div><button id="clearChanges">Apply / clear</button></header><div class="cards">${(project.changes||[]).map(c=>`<article><b>${esc(c.kind)}</b><h3>${esc(c.key||c.relation||'change')}</h3><small>${esc(c.at)}</small></article>`).join('')||'<article><h3>No working changes</h3></article>'}</div>`; $('#clearChanges').onclick=()=>{project.changes=[];save();render()}; }}
function wireRows(){ $('#main').querySelectorAll('tbody tr[data-id]').forEach(r=>r.onclick=()=>{selected=r.dataset.id; renderInspector();}); }
function renderInspector(){ const a=project.artifacts.find(x=>x.id===selected); if(!a){$('#inspector').innerHTML='<p>Select an artifact</p>';return;} const map=byId(project); const related=project.relations.filter(r=>r.fromArtifactId===a.id||r.toArtifactId===a.id); const issues=runValidation(project).filter(i=>i.artifactIds.includes(a.id)); const imp=impact(project,a.id); $('#inspector').innerHTML=`<div class="inspector-head"><small>${esc(a.type)}</small><h2>${esc(a.key)}</h2><h3>${esc(a.title)}</h3></div><label>Status<select id="status">${['draft','in_review','approved','outdated','deprecated'].map(x=>`<option ${x===a.status?'selected':''}>${x}</option>`).join('')}</select></label><label>Knowledge<select id="knowledge">${['known','assumed','proposed','undefined'].map(x=>`<option ${x===a.knowledgeState?'selected':''}>${x}</option>`).join('')}</select></label><label>Title<input id="title" value="${esc(a.title)}"></label><label>Payload JSON<textarea id="payload">${esc(JSON.stringify(a.payload,null,2))}</textarea></label><button id="saveArtifact">Save to ChangeSet</button><hr><h3>Relations</h3>${related.map(r=>`<div class="relation"><small>${esc(r.type)}</small><b>${esc(map.get(r.fromArtifactId===a.id?r.toArtifactId:r.fromArtifactId)?.key)}</b></div>`).join('')||'<p>None</p>'}<h3>Validation</h3>${issues.map(i=>`<div class="mini-issue ${i.severity}">${esc(i.ruleId)} ${esc(i.title)}</div>`).join('')||'<p>No issues</p>'}<h3>Downstream impact</h3>${imp.slice(0,8).map(x=>`<div class="relation"><small>depth ${x.depth}</small><b>${esc(x.artifact?.key)}</b></div>`).join('')||'<p>None</p>'}`; $('#saveArtifact').onclick=()=>{try{a.title=$('#title').value.trim();a.status=$('#status').value;a.knowledgeState=$('#knowledge').value;a.payload=JSON.parse($('#payload').value);a.version++;a.updatedAt=new Date().toISOString();project.changes.push({kind:'artifact.updated',key:a.key,at:a.updatedAt});save();render()}catch(e){alert('Payload JSON: '+e.message)}}; }
function addArtifact(type){ const key=prompt('Artifact key'); if(!key)return; if(artifactByKey(project,key)){alert('Key already exists');return;} const title=prompt('Title')||key, id=crypto.randomUUID(); const now=new Date().toISOString(); project.artifacts.push({id,projectId:project.id,key,type,title,status:'draft',knowledgeState:'undefined',version:1,currentVersionId:id+'-v1',tags:[],sourceIds:[],metadata:{},payload:{},createdAt:now,updatedAt:now}); project.changes.push({kind:'artifact.created',key,at:now}); selected=id; save(); render();}
function addRelation(){ const fromKey=prompt('From artifact key'); const toKey=prompt('To artifact key'); const type=prompt('Relation type\n'+RELATION_TYPES.join(', ')); const from=artifactByKey(project,fromKey),to=artifactByKey(project,toKey); if(!from||!to){alert('Artifact key not found');return;} const now=new Date().toISOString(),r={id:crypto.randomUUID(),projectId:project.id,fromArtifactId:from.id,toArtifactId:to.id,type,status:'active',source:'human',createdAt:now,updatedAt:now}; const vr=validateRelation(project,r); if(!vr.ok){alert(vr.error);return;} project.relations.push(r); project.changes.push({kind:'relation.created',relation:`${from.key} ${type} ${to.key}`,at:now}); save(); render();}
function exportJson(){const b=new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='engineering-design-graph-project.json';a.click();URL.revokeObjectURL(u)}
function importJson(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!Array.isArray(p.artifacts)||!Array.isArray(p.relations))throw new Error('artifacts/relations required');project=p;project.changes=project.changes||[];selected=project.artifacts[0]?.id||null;save();render()}catch(err){alert(err.message)}};r.readAsText(f)}
render();
