import http from 'node:http';
import {randomUUID} from 'node:crypto';
import {createApiService} from './api-v1.mjs';
import {authorize,permissionForRequest} from './security.mjs';
import {authorizeProject} from './project-access.mjs';
import {createAuditOutboxStore} from './audit-outbox.mjs';
import {createIdempotencyStore} from './idempotency.mjs';
import {createMetrics,createRateLimiter,createStructuredLogger} from './observability.mjs';
import {toPrometheus} from './telemetry.mjs';

async function readJson(req){const chunks=[];for await(const c of req)chunks.push(c);if(!chunks.length)return{};const text=Buffer.concat(chunks).toString('utf8');return text?JSON.parse(text):{}}
function send(res,status,headers,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8',...headers});res.end(JSON.stringify(body))}
function routeKey(path){return path.replace(/\/(projects|artifacts|change-sets|ai-candidates)\/[^/]+/g,'/$1/:id')}
function resolveProjectId(api,path){const parts=path.split('/').filter(Boolean),p=parts.slice(2);if(parts[0]!=='api'||parts[1]!=='v1')return null;if(p[0]==='projects'&&p[1])return p[1];const projects=api?.projects;if(!projects?.values)return null;if(p[0]==='artifacts'&&p[1])for(const project of projects.values())if(project.artifacts?.some(x=>x.id===p[1]))return project.id;if(p[0]==='change-sets'&&p[1])for(const project of projects.values())if(project.changeSets?.some(x=>x.id===p[1]))return project.id;if(p[0]==='ai-candidates'&&p[1])for(const project of projects.values())if(project.aiCandidates?.some(x=>x.id===p[1]))return project.id;return null}

export function createHttpGateway({api=createApiService(),verifyBearer,auditOutbox=createAuditOutboxStore(),idempotency=createIdempotencyStore(),projectAccessRepository=null,logger=createStructuredLogger({sink:null}),metrics=createMetrics(),rateLimiter=createRateLimiter(),readinessCheck=async()=>true}={}){
  if(!verifyBearer)throw new Error('verifyBearer is required');
  const handler=async(req,res)=>{const started=Date.now(),requestId=req.headers['x-request-id']||randomUUID(),url=new URL(req.url,'http://local'),method=(req.method||'GET').toUpperCase(),route=routeKey(url.pathname);let principal=null,body={},projectId=null,status=500;try{
    if(method==='GET'&&url.pathname==='/health/live'){status=200;send(res,status,{'x-request-id':requestId},{status:'ok'});return}
    if(method==='GET'&&url.pathname==='/health/ready'){try{await readinessCheck();status=200;send(res,status,{'x-request-id':requestId},{status:'ready'})}catch{status=503;send(res,status,{'x-request-id':requestId},{status:'not_ready',code:'DEPENDENCY_UNAVAILABLE'})}return}
    if(method==='GET'&&url.pathname==='/metrics'){status=200;res.writeHead(200,{'content-type':'text/plain; version=0.0.4; charset=utf-8','x-request-id':requestId});res.end(toPrometheus(metrics));return}
    principal=await verifyBearer(req.headers.authorization);const rate=rateLimiter.check(principal.userId||'anonymous');if(!rate.allowed)throw Object.assign(new Error('Rate limit exceeded'),{status:429,code:'RATE_LIMITED',rate});const permission=permissionForRequest(method,url.pathname);projectId=resolveProjectId(api,url.pathname);if(projectAccessRepository&&projectId)await authorizeProject({principal,projectId,permission,accessRepository:projectAccessRepository});else authorize(principal,permission);if(method!=='GET'&&method!=='HEAD')body=await readJson(req);const idem=idempotency.appliesTo(method,url.pathname)?idempotency.lookup({principal,method,path:url.pathname,key:req.headers['idempotency-key'],body}):null;if(idem?.hit){const cached=idem.response;status=cached.status;await auditOutbox.record({principal,method,path:url.pathname,status,requestId,body,replayed:true});send(res,status,{'x-request-id':requestId,'idempotency-replayed':'true',...cached.headers},cached.body);return}const response=await api.handle({method,url:url.pathname+url.search,body,headers:{...req.headers,'x-user-id':principal.userId,'x-request-id':requestId,'x-project-id':projectId||''}});status=response.status;if(idem&&!idem.hit&&req.headers['idempotency-key']&&status>=200&&status<300)idempotency.store({scope:idem.scope,fingerprint:idem.fingerprint,response});if(response.headers?.['x-transactional-audit']!=='true')await auditOutbox.record({principal,method,path:url.pathname,status,requestId,body});send(res,status,{'x-request-id':requestId,...response.headers},response.body)}catch(err){status=err.status||500;const code=err.code||'REQUEST_FAILED',problem={type:`https://errors.local/${String(code).toLowerCase().replaceAll('_','-')}`,title:err.message,status,code,traceId:requestId,errors:[]};try{await auditOutbox.record({principal,method,path:url.pathname,status,requestId,body})}catch{}const headers={'x-request-id':requestId};if(err.rate){headers['retry-after']=String(Math.max(1,Math.ceil((err.rate.resetAt-Date.now())/1000)));headers['x-ratelimit-remaining']='0'}send(res,status,headers,problem)}finally{const durationMs=Date.now()-started,labels={method,route,status};metrics.inc('http_requests_total',labels);metrics.observe('http_request_duration_ms',durationMs,{method,route});if(status>=400)metrics.inc('http_errors_total',labels);const fields={requestId,userId:principal?.userId||null,projectId,method,route,status,durationMs};if(status>=500)logger.error('http.request',fields);else if(status>=400)logger.warn('http.request',fields);else logger.info('http.request',fields)}};
  return{handler,api,auditOutbox,idempotency,projectAccessRepository,logger,metrics,rateLimiter,listen(port=4180,host='127.0.0.1'){const server=http.createServer(handler);return new Promise(resolve=>server.listen(port,host,()=>resolve(server)))}};
}
