const assert=require('node:assert/strict');
const fs=require('node:fs');
const {chromium}=require('playwright');
const plan=JSON.parse(fs.readFileSync('static/c04-user-defined-workspace-plan-v6.json','utf8'));
assert.equal(plan.planVersion,6);assert.equal(plan.status,'FROZEN_BEFORE_V6_IMPLEMENTATION');assert.equal(plan.acceptance.length,10);
const targetUrl=process.env.C04_TARGET_URL||'http://127.0.0.1:4173/';
const evidence={type:'TSUGUC04UserDefinedWorkspaceV6Evidence',planVersion:6,targetUrl,status:'RUNNING',scenarios:{},runtime:{consoleErrors:[],pageErrors:[],apiErrors:[]},metrics:{}};
const write=()=>fs.writeFileSync('c04-user-defined-workspace-v6-evidence.json',JSON.stringify(evidence,null,2)+'\n');
const mark=(id,detail={})=>{evidence.scenarios[id]={status:'PASS',...detail};write()};
function routes(page){return page.route('https://api.github.com/**',async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname;let status=200,body={};if(path==='/user')body={login:'c04-v6-e2e',id:1,type:'User'};else if(path==='/repos/kj2whvbzjn-hue/tsugu')body={id:1363396531,name:'tsugu',full_name:'kj2whvbzjn-hue/tsugu',private:true,permissions:{admin:true,push:true,pull:true}};else if(path==='/repos/kj2whvbzjn-hue/tsugu/branches/c04-v6-e2e-data')body={name:'c04-v6-e2e-data',commit:{sha:'1111111111111111111111111111111111111111'}};else if(path==='/repos/kj2whvbzjn-hue/tsugu/contents/data/projects')body=[];else if(path.startsWith('/repos/kj2whvbzjn-hue/tsugu/contents/data/projects/')){status=404;body={message:'Not Found'}}else{status=404;body={message:`Unhandled mock ${req.method()} ${path}`}}if(status>=400)evidence.runtime.apiErrors.push({status,path,expected:status===404&&path.includes('/contents/data/projects/')});await route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)})})}
async function clickTab(page,name){const b=page.getByRole('button',{name,exact:true}).first();await b.scrollIntoViewIfNeeded();await b.click()}
async function rawProject(page){await clickTab(page,'高度なJSON');return JSON.parse(await page.locator('#rawProject').inputValue())}
async function openCreate(page,label){const s=page.locator('details.v6-create').filter({hasText:label}).locator('summary').first();await s.click()}
async function choose(select,label){await select.selectOption({label})}
function card(page,title){return page.locator('.box-card-v6').filter({hasText:title}).first()}
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});page.on('console',m=>{if(m.type()==='error')evidence.runtime.consoleErrors.push(m.text())});page.on('pageerror',e=>evidence.runtime.pageErrors.push(e.message));await routes(page);page.on('dialog',async d=>{if(d.type()==='prompt')await d.accept('C-04 v6 user workspace');else await d.accept()});try{
 await page.goto(`${targetUrl}?c04v6=${Date.now()}`,{waitUntil:'networkidle',timeout:60000});await page.locator('#owner').fill('kj2whvbzjn-hue');await page.locator('#repo').fill('tsugu');await page.locator('#branch').fill('c04-v6-e2e-data');await page.locator('#token').fill('github_pat_c04_v6_placeholder');await page.getByRole('button',{name:'接続',exact:true}).click();await page.getByText(/GitHubから0件を読み込みました/).waitFor({timeout:10000});await page.getByRole('button',{name:/新規案件/}).click();
 await clickTab(page,'Box');assert.equal(await page.locator('[name="boxType"]').count(),0);assert.equal(await page.getByText('UI / Schema / Testは標準種別',{exact:false}).count(),0);await openCreate(page,'＋ Box追加');let form=page.locator('#v6BoxForm');
 async function addBox(title,classification=''){await form.locator('[name="title"]').fill(title);await form.locator('[name="classification"]').fill(classification);await form.locator('button[type="submit"]').click();form=page.locator('#v6BoxForm');if(!(await form.locator('[name="title"]').isVisible()))await openCreate(page,'＋ Box追加')}
 await addBox('画面まわり','自分の分類A');await addBox('データまわり','自分の分類B');await addBox('検証まわり','');let project=await rawProject(page);const fresh=project.core.workBoxes.filter(x=>x.uiModelVersion===6);assert.equal(fresh.length,3);assert.ok(fresh.every(x=>!Object.prototype.hasOwnProperty.call(x,'boxType')));assert.deepEqual(fresh.map(x=>x.classification),['自分の分類A','自分の分類B','']);mark('UI6-01',{boxes:3,noBuiltInTypeSelector:true,noBoxTypeWrites:true});mark('UI6-02',{classifications:fresh.map(x=>x.classification)});
 await clickTab(page,'Task');await openCreate(page,'＋ Task追加');form=page.locator('#v6TaskForm');async function addTask(title,box){await form.locator('[name="title"]').fill(title);await choose(form.locator('[name="boxId"]'),box);await form.locator('button[type="submit"]').click();form=page.locator('#v6TaskForm');if(!(await form.locator('[name="title"]').isVisible()))await openCreate(page,'＋ Task追加')};await addTask('作業1','画面まわり');await addTask('作業2','画面まわり');await addTask('作業3','データまわり');
 await clickTab(page,'テスト');await openCreate(page,'＋ Test追加');form=page.locator('#v6TestForm');async function addTest(title,box){await form.locator('[name="title"]').fill(title);await choose(form.locator('[name="boxId"]'),box);await form.locator('button[type="submit"]').click();form=page.locator('#v6TestForm');if(!(await form.locator('[name="title"]').isVisible()))await openCreate(page,'＋ Test追加')};await addTest('確認1','検証まわり');await addTest('確認2','検証まわり');project=await rawProject(page);const screen=project.core.workBoxes.find(x=>x.title==='画面まわり'),verify=project.core.workBoxes.find(x=>x.title==='検証まわり');assert.equal(project.core.tasks.filter(x=>x.boxId===screen.id).length,2);assert.equal(project.core.testDefinitions.filter(x=>x.boxId===verify.id).length,2);await clickTab(page,'構造');assert.match(await card(page,'画面まわり').innerText(),/Task 2/);assert.match(await card(page,'検証まわり').innerText(),/Test 2/);mark('UI6-03',{screenTasks:2,verifyTests:2});
 await clickTab(page,'依存');assert.equal(await page.locator('[name="kind"]').count(),0);await openCreate(page,'＋ 依存追加');form=page.locator('#v6DependencyForm');async function addDep(a,b,label=''){await choose(form.locator('[name="dependentRef"]'),a);await choose(form.locator('[name="prerequisiteRef"]'),b);await form.locator('[name="relationLabel"]').fill(label);await form.locator('button[type="submit"]').click();form=page.locator('#v6DependencyForm');if(!(await form.locator('[name="dependentRef"]').isVisible()))await openCreate(page,'＋ 依存追加')};await addDep('Box: 画面まわり','Box: データまわり','ユーザーが決めた関係');project=await rawProject(page);const dep=project.core.dependencies.find(x=>x.uiModelVersion===6);assert.equal(dep.relationLabel,'ユーザーが決めた関係');assert.equal(Object.prototype.hasOwnProperty.call(dep,'kind'),false);mark('UI6-04',{freeTextRelation:true,noKindWrite:true});await clickTab(page,'構造');assert.match(await card(page,'画面まわり').innerText(),/依存 1/);assert.match(await card(page,'データまわり').innerText(),/影響 1/);assert.equal(Object.prototype.hasOwnProperty.call(project.core,'impacts'),false);mark('UI6-05',{reverseDerived:true,noReverseStore:true});mark('UI6-06',{flagsVisible:true});
 const metrics=await page.evaluate(()=>{const w=document.querySelector('[data-v6-workspace]');const tabs=document.querySelector('.workspace-sticky .tabs');const menu=document.querySelector('.v6-mobile-project-menu');return{workspaceTop:w?.getBoundingClientRect().top,tabsHeight:tabs?.getBoundingClientRect().height,menuOpen:menu?.open,scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth}});assert.ok(metrics.workspaceTop<=300,`workspace top ${metrics.workspaceTop}`);assert.equal(metrics.menuOpen,false);mark('UI6-07',{workspaceTop:metrics.workspaceTop,projectMenuCollapsed:true});assert.ok(metrics.tabsHeight<=60,`tabs height ${metrics.tabsHeight}`);assert.ok(metrics.scrollWidth<=metrics.clientWidth+1);mark('UI6-08',{tabsHeight:metrics.tabsHeight,horizontalOverflow:false});
 await clickTab(page,'依存');if(!(await page.locator('#v6DependencyForm').count()))await openCreate(page,'＋ 依存追加');form=page.locator('#v6DependencyForm');const before=(await rawProject(page)).core.dependencies.length;await clickTab(page,'依存');await openCreate(page,'＋ 依存追加');form=page.locator('#v6DependencyForm');await form.locator('[name="dependentRef"]').evaluate(sel=>{const o=new Option('missing','WORKBOX::missing');sel.add(o);sel.value=o.value});await choose(form.locator('[name="prerequisiteRef"]'),'Box: データまわり');await form.locator('button[type="submit"]').click();await page.getByText(/存在するBox \/ Task \/ Test/).waitFor();assert.equal((await rawProject(page)).core.dependencies.length,before);await clickTab(page,'依存');await openCreate(page,'＋ 依存追加');form=page.locator('#v6DependencyForm');await choose(form.locator('[name="dependentRef"]'),'Box: データまわり');await choose(form.locator('[name="prerequisiteRef"]'),'Box: データまわり');await form.locator('button[type="submit"]').click();await page.getByText(/自己依存/).waitFor();await clickTab(page,'依存');await openCreate(page,'＋ 依存追加');form=page.locator('#v6DependencyForm');await choose(form.locator('[name="dependentRef"]'),'Box: データまわり');await choose(form.locator('[name="prerequisiteRef"]'),'Box: 画面まわり');await form.locator('button[type="submit"]').click();await page.getByText(/循環/).waitFor();project=await rawProject(page);assert.equal(project.items.length,0);assert.ok(project.core.tasks.filter(x=>x.uiModelVersion===6).every(x=>!Object.prototype.hasOwnProperty.call(x,'dependsOn')));mark('UI6-09',{missingRejected:true,selfRejected:true,cycleRejected:true,legacyItems:0});
 const unexpected=evidence.runtime.apiErrors.filter(x=>!x.expected);assert.deepEqual(evidence.runtime.consoleErrors,[]);assert.deepEqual(evidence.runtime.pageErrors,[]);assert.deepEqual(unexpected,[]);mark('UI6-10',{runtime:'PASS'});evidence.status='PASS_UI6_01_TO_10_UI_RUNTIME';evidence.metrics={boxes:project.core.workBoxes.length,tasks:project.core.tasks.length,tests:project.core.testDefinitions.length,dependencies:project.core.dependencies.length,workspaceTop:metrics.workspaceTop};write();await clickTab(page,'構造');await page.screenshot({path:'c04-user-defined-workspace-v6-mobile.png',fullPage:true});
}catch(e){evidence.status='FAIL';evidence.error=e.stack||String(e);write();throw e}finally{await browser.close()}})().catch(e=>{console.error(e.stack||e);process.exit(1)});
