const fs=require('node:fs');
const {chromium}=require('playwright');
const plan=JSON.parse(fs.readFileSync('static/c04-ui-usability-plan-v3.json','utf8'));
if(plan.status!=='FROZEN_BEFORE_BASELINE_MEASUREMENT'||plan.version!==3)throw new Error('C-04 v3 plan must be frozen before measurement');
const owner='kj2whvbzjn-hue',repo='tsugu',token=process.env.GH_TOKEN_E2E||process.env.GITHUB_TOKEN;
const targetUrl=process.env.C04_TARGET_URL||plan.target.publishedUrl,runId=process.env.GITHUB_RUN_ID||String(Date.now()),runAttempt=process.env.GITHUB_RUN_ATTEMPT||'1';
if(!token)throw new Error('GitHub token is required');
const tempBranch=`c04-v3-baseline-${runId}-${runAttempt}`;
const headers={Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'tsugu-c04-v3-baseline'};
async function api(path,options={},allow404=false){const r=await fetch(`https://api.github.com${path}`,{...options,cache:'no-store',headers:{...headers,...(options.headers||{})}});const text=await r.text();if(allow404&&r.status===404)return null;if(!r.ok)throw new Error(`GitHub ${r.status}: ${text}`);return text?JSON.parse(text):null}
function emptyCore(){return{architectureNodes:[],workBoxes:[],tasks:[],decisions:[],issues:[],checks:[],approvals:[],evidences:[],evidenceVersions:[],repositories:[],repositoryBaselines:[],pathEntries:[],plannedChanges:[],actualChanges:[],relations:[]}}
function planProject(){return{schemaVersion:1,id:'44444444-5555-4666-8777-888888888888',name:'C-04 v3 判断中心UI・関連参照ナビゲーション計画',purpose:'TSUGUの目的から逆算して、その時の判断に必要な情報を優先表示し、関連根拠へ検索なしで到達できるUIを事前基準で検証する',rules:'結果を見て合格基準を緩めない。C-04 v2基準を後退させない。',focus:'常設管理UI収納・余白密度・判断情報優先・関連1hop/連鎖の直接参照',baseline:'C-04|version=3|static/c04-ui-usability-plan-v3.json|frozen=2d0ae47bea70735576a9410ba409f3a6c50865ed',changeControlEnabled:true,next:'現行公開UIをPlaywrightでbaseline測定する',stage:'検討',implementationApproved:false,completionApproved:false,core:emptyCore(),items:plan.improvements.map(x=>({id:x.id,kind:'検証',title:x.name,body:`Fix\n${x.fix}\n\nPASS\n${x.pass.join('\n')}`,status:'未確認',parentId:'',reason:'TSUGUプロジェクト目的とユーザー実機UI評価に基づくC-04 v3事前基準'}))}}
function workloadProject(){const items=[
{id:'REL-A',kind:'構成',title:'関連起点 A',body:'Aの本文。関連Bを確認する前に未保存編集を加える。',status:'未着手',parentId:'REL-B',reason:'A→B→C関連参照baseline'},
{id:'REL-B',kind:'構成',title:'関連中継 B',body:'Bの本文。さらにCへ関連する。',status:'要確認',parentId:'REL-C',reason:'A→B→C関連参照baseline'},
{id:'REL-C',kind:'構成',title:'関連終点 C',body:'Cの本文。',status:'未着手',parentId:'',reason:'A→B→C関連参照baseline'}
];for(let i=1;i<=193;i++)items.push({id:`FILL-${String(i).padStart(3,'0')}`,kind:'構成',title:`測定用項目 ${i}`,body:`baseline filler ${i}`,status:i%5===0?'要確認':'未着手',parentId:'',reason:''});if(items.length!==196)throw new Error(`workload size ${items.length}`);return{schemaVersion:1,id:'55555555-6666-4777-8888-999999999999',name:'C-04 v3 現行UI baseline 196項目',purpose:'判断中心UIと関連参照コストを現行公開UIで実測する',rules:'測定中に承認・完了状態を変更しない',focus:'REL-A→REL-B→REL-C→REL-Aの遷移・検索・未保存値保持を計測',baseline:'C-04 v3 current published UI baseline',changeControlEnabled:true,next:'FAIL項目をUI改善実装へ変換する',stage:'検討',implementationApproved:false,completionApproved:false,core:emptyCore(),items}}
const evidence={type:'TSUGUC04DecisionUIV3BaselineEvidence',taskId:'C-04',planVersion:3,planFrozenCommit:'2d0ae47bea70735576a9410ba409f3a6c50865ed',targetUrl,runId,runAttempt,tempBranch,status:'MEASURING',registration:{},scenarios:{},metrics:{related:{},density:{},workspace:{},decisionInfo:{}},runtime:{consoleErrors:[],pageErrors:[],apiErrors:[]},notes:[]};
function result(id,pass,metrics,reason){evidence.scenarios[id]={status:pass?'PASS':'FAIL',metrics,reason}}
function write(){fs.writeFileSync('c04-ui-usability-v3-baseline-evidence.json',JSON.stringify(evidence,null,2)+'\n')}
async function connect(page){await page.locator('#owner').fill(owner);await page.locator('#repo').fill(repo);await page.locator('#branch').fill(tempBranch);await page.locator('#token').fill('github_pat_c04_v3_placeholder');await page.getByRole('button',{name:'接続',exact:true}).click();await page.getByText(/GitHubから\d+件を読み込みました/).waitFor({timeout:30000})}
async function importAndSave(page,project,fileName){const chooserP=page.waitForEvent('filechooser');await page.getByRole('button',{name:'JSONから新規取込',exact:true}).click();const chooser=await chooserP;await chooser.setFiles({name:fileName,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project,null,2)+'\n')});await page.getByRole('button',{name:'GitHubへ保存',exact:true}).waitFor({timeout:15000});await page.getByRole('button',{name:'GitHubへ保存',exact:true}).click();await page.getByText(/GitHubへ保存しました。案件版 1/).waitFor({timeout:30000})}
async function visible(locator){try{return await locator.isVisible()}catch{return false}}
async function openWorkload(page){await page.evaluate(()=>scrollTo(0,0));const card=page.locator('.project-list button').filter({hasText:'C-04 v3 現行UI baseline 196項目'});await card.click();await page.getByRole('button',{name:'項目',exact:true}).click();await page.locator('#itemSearch').waitFor({state:'visible'})}
async function searchItem(page,id,counter){counter.searches++;await page.locator('#itemSearch').fill(id);await page.locator('#itemSearch').press('Enter');const row=page.locator(`[data-item-row="${id}"]`);await row.waitFor({state:'visible',timeout:10000});return row}
async function openEdit(row,counter){counter.actions++;counter.transitions++;await row.locator('[data-edit]').click();const modal=row.page().locator('.modal');await modal.getByText('項目編集',{exact:true}).waitFor();return modal}
async function closeModal(modal,counter){counter.actions++;counter.transitions++;await modal.getByRole('button',{name:'閉じる',exact:true}).click()}
function fieldInput(modal,label){return modal.locator('.field').filter({hasText:label}).locator('input').first()}
function bodyArea(modal){return modal.locator('.field textarea:not(.code)').first()}
async function fieldGaps(modal){const boxes=await modal.locator('.field:visible').evaluateAll(els=>els.map(e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom}}).sort((a,b)=>a.y-b.y));const gaps=[];for(let i=1;i<boxes.length;i++){const g=boxes[i].y-boxes[i-1].bottom;if(g>=0)gaps.push(g)}return gaps}
async function scrollTravelTo(page,locator){await page.evaluate(()=>{window.__c04v3=[window.scrollY];if(!window.__c04v3Bound){window.addEventListener('scroll',()=>window.__c04v3.push(window.scrollY),{passive:true});window.__c04v3Bound=true}});await locator.scrollIntoViewIfNeeded();await page.waitForTimeout(100);const pts=await page.evaluate(()=>window.__c04v3||[window.scrollY]);let travel=0;for(let i=1;i<pts.length;i++)travel+=Math.abs(pts[i]-pts[i-1]);return{travel,points:pts}}
(async()=>{const mainRef=await api(`/repos/${owner}/${repo}/git/ref/heads/main`);await api(`/repos/${owner}/${repo}/git/refs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:`refs/heads/${tempBranch}`,sha:mainRef.object.sha})});const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});let expected404=true;page.on('pageerror',e=>evidence.runtime.pageErrors.push(e.message));page.on('console',m=>{if(m.type()==='error'){const t=m.text();if(expected404&&t.includes('404'))return;evidence.runtime.consoleErrors.push(t)}});page.on('response',r=>{if(r.url().startsWith('https://api.github.com/')&&r.status()>=400){if(expected404&&r.status()===404)return;evidence.runtime.apiErrors.push({url:r.url(),status:r.status()})}});page.on('dialog',async d=>{if(d.type()==='prompt')await d.accept('C-04 v3 baseline measurement');else await d.accept()});await page.addInitScript(({token,owner,repo})=>{const nativeFetch=window.fetch.bind(window);window.fetch=async(input,init={})=>{const url=typeof input==='string'?input:input.url;if(url==='https://api.github.com/user')return new Response(JSON.stringify({login:owner,id:1,type:'User'}),{status:200,headers:{'content-type':'application/json'}});const h=new Headers(init.headers||(typeof input!=='string'?input.headers:undefined)||{});if(url.startsWith('https://api.github.com/'))h.set('Authorization',`Bearer ${token}`);const r=await nativeFetch(input,{...init,headers:h,cache:'no-store'});if(url===`https://api.github.com/repos/${owner}/${repo}`&&r.ok){const data=await r.clone().json();data.private=true;data.permissions={admin:true,maintain:true,push:true,pull:true};return new Response(JSON.stringify(data),{status:200,headers:{'content-type':'application/json'}})}return r}},{token,owner,repo});try{
await page.goto(`${targetUrl}?c04v3baseline=${runId}`,{waitUntil:'networkidle',timeout:60000});await connect(page);expected404=false;
await importAndSave(page,planProject(),'c04-v3-plan.json');evidence.registration.planSavedThroughUI=true;evidence.registration.planName='C-04 v3 判断中心UI・関連参照ナビゲーション計画';
await importAndSave(page,workloadProject(),'c04-v3-workload.json');evidence.registration.workloadSavedThroughUI=true;
await page.getByRole('button',{name:'GitHubから再読込',exact:true}).click();await page.getByText(/GitHubから2件を読み込みました/).waitFor({timeout:30000});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(150);
const managementNames=['JSONから新規取込','GitHubから再読込','接続解除'];let persistent=0;const managementVisibility={};for(const name of managementNames){const v=await visible(page.getByRole('button',{name,exact:true}));managementVisibility[name]=v;if(v)persistent++}const overflowCandidates=page.locator('button[aria-haspopup="menu"],button[aria-label*="メニュー"],button[aria-label*="その他"]');const overflowVisible=await overflowCandidates.evaluateAll(els=>els.filter(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.visibility!=='hidden'&&s.display!=='none'}).length);const firstProject=page.locator('.project-list button').first();const fp=await firstProject.boundingBox();const workspace={persistentManagementButtons:persistent,managementVisibility,overflowVisible,firstProjectBox:fp,firstProjectTopRatio:fp?fp.y/844:null};evidence.metrics.workspace=workspace;const ui301=persistent===0&&overflowVisible<=1&&fp&&fp.y<=844*plan.budgets.firstProjectTopMaxViewportRatio;result('UI3-01',!!ui301,workspace,ui301?'connected workspace is compact':'connected workspace keeps maintenance controls and/or first project too low');await page.screenshot({path:'c04-v3-baseline-workspace-mobile.png',fullPage:true});
await openWorkload(page);const firstRow=page.locator('.item-card-compact:visible').first();const rb=await firstRow.boundingBox();const editBox=await firstRow.locator('[data-edit]').boundingBox();const rowHeight=rb?.height??null;const rowTouchOk=!!editBox&&editBox.width>=44&&editBox.height>=44;let row=await searchItem(page,'REL-A',{searches:0});let modal=await openEdit(row,{actions:0,transitions:0});const gaps=await fieldGaps(modal);const maxFieldGap=gaps.length?Math.max(...gaps):null;evidence.metrics.density={mobileItemRowHeight:rowHeight,modalFieldGaps:gaps,maxModalFieldGap:maxFieldGap,editTouchTarget:editBox};const ui302=rowHeight!==null&&rowHeight<=plan.budgets.mobileNormalItemRowHeightMaxPx&&maxFieldGap!==null&&maxFieldGap<=plan.budgets.modalFieldBlockGapMaxPx&&rowTouchOk;result('UI3-02',ui302,evidence.metrics.density,ui302?'density budgets met':'item row and/or modal spacing exceeds frozen budget');await modal.getByRole('button',{name:'閉じる',exact:true}).click();
await page.getByRole('button',{name:'概要',exact:true}).click();const labels=['目的','現在の焦点','次にすること'];const labelMetrics={};let decisionPass=true;for(const label of labels){const loc=page.getByText(label,{exact:true}).last();if(!(await visible(loc))){labelMetrics[label]={present:false};decisionPass=false;continue}await page.locator('h1').last().scrollIntoViewIfNeeded().catch(()=>{});const m=await scrollTravelTo(page,loc);labelMetrics[label]={present:true,travel:m.travel};if(m.travel>844*plan.budgets.projectDecisionInfoTravelMaxViewports)decisionPass=false}evidence.metrics.decisionInfo=labelMetrics;result('UI3-03',decisionPass,labelMetrics,decisionPass?'decision information is within one viewport':'decision information is too far or missing');
await page.getByRole('button',{name:'項目',exact:true}).click();const one={actions:0,transitions:0,searches:0,listIntermediates:0,idCopies:0};row=await searchItem(page,'REL-A',one);modal=await openEdit(row,one);const relInput=fieldInput(modal,'関連先ID');const relatedId=await relInput.inputValue();const relatedTitleInline=await modal.getByText('関連中継 B',{exact:true}).count();const relatedKindInline=await modal.getByText('構成',{exact:true}).count();const relatedStatusInline=(await modal.getByText('要確認',{exact:true}).count())>0;const ui304=relatedId==='REL-B'&&relatedTitleInline>0&&relatedKindInline>0&&relatedStatusInline;result('UI3-04',ui304,{relatedId,relatedTitleInline,relatedKindInline,relatedStatusInline},ui304?'related reference is resolved inline':'related reference is only an ID/input and does not expose target meaning inline');
const draftMarker='\n未保存draft-C04V3';await bodyArea(modal).fill((await bodyArea(modal).inputValue())+draftMarker);await closeModal(modal,one);one.listIntermediates++;row=await searchItem(page,'REL-B',one);modal=await openEdit(row,one);const oneHopDraftPreservable=false;const ui305=one.actions<=plan.budgets.relatedOneHopMaxActions&&one.searches===plan.budgets.relatedOneHopSearches&&one.listIntermediates===plan.budgets.relatedOneHopListIntermediates&&oneHopDraftPreservable;result('UI3-05',ui305,{...one,oneHopDraftPreservable,route:'REL-A modal -> close -> list search REL-B -> REL-B modal'},ui305?'one-hop relation is direct':'one-hop relation requires list/search and cannot preserve draft in context');
const chain={forwardActions:one.actions,forwardTransitions:one.transitions,searches:one.searches,listIntermediates:one.listIntermediates,returnActions:0,returnTransitions:0,idCopies:0};const bRelated=await fieldInput(modal,'関連先ID').inputValue();await closeModal(modal,{actions:0,transitions:0});chain.forwardActions++;chain.forwardTransitions++;chain.listIntermediates++;row=await searchItem(page,bRelated,{searches:0});chain.searches++;await row.locator('[data-edit]').click();chain.forwardActions++;chain.forwardTransitions++;modal=page.locator('.modal');await modal.getByText('項目編集',{exact:true}).waitFor();const cRelated=await fieldInput(modal,'関連先ID').inputValue();await closeModal(modal,{actions:0,transitions:0});chain.returnActions++;chain.returnTransitions++;chain.listIntermediates++;await page.locator('#itemSearch').fill('REL-A');await page.locator('#itemSearch').press('Enter');chain.searches++;chain.returnActions++;row=page.locator('[data-item-row="REL-A"]');await row.waitFor({state:'visible'});await row.locator('[data-edit]').click();chain.returnActions++;chain.returnTransitions++;modal=page.locator('.modal');await modal.getByText('項目編集',{exact:true}).waitFor();const reopenedBody=await bodyArea(modal).inputValue();const draftPreserved=reopenedBody.includes(draftMarker);chain.draftPreserved=draftPreserved;chain.cRelatedValue=cRelated;const forwardToC=chain.forwardActions;const ui306=forwardToC<=plan.budgets.relatedChainTwoHopMaxForwardActions&&chain.searches===plan.budgets.relatedChainSearches&&chain.listIntermediates===plan.budgets.relatedChainListIntermediates&&chain.returnActions<=plan.budgets.relatedChainReturnToOriginMaxActions&&draftPreserved;result('UI3-06',ui306,chain,ui306?'relation chain is direct and context-preserving':'relation chain repeats close/list/search/open and loses unsaved origin draft');evidence.metrics.related={oneHop:one,chain};
const rel=fieldInput(modal,'関連先ID');const originalRel=await rel.inputValue();const ariaAuto=await rel.getAttribute('aria-autocomplete');const listAttr=await rel.getAttribute('list');await rel.fill('NO-SUCH-C04-V3');await rel.blur();await page.waitForTimeout(100);const ariaInvalid=await rel.getAttribute('aria-invalid');const unresolvedText=await modal.getByText(/存在しません|未解決|見つかりません/).count();await rel.fill(originalRel);const ui307=!!ariaAuto||!!listAttr||ariaInvalid==='true'||unresolvedText>0;result('UI3-07',ui307,{ariaAutocomplete:ariaAuto,listAttribute:listAttr,ariaInvalidAfterUnknown:ariaInvalid,inlineUnresolvedMessageCount:unresolvedText},ui307?'relation input exposes assistance/validation':'relation input behaves as plain raw ID input without visible assistance or existence validation');await modal.getByRole('button',{name:'閉じる',exact:true}).click();
const runtimePass=evidence.runtime.pageErrors.length===0&&evidence.runtime.apiErrors.length===0&&evidence.runtime.consoleErrors.length===0;result('UI3-08',runtimePass,{runtime:evidence.runtime,note:'C-04 v2 regression runs separately in the same workflow'},runtimePass?'runtime clean':'runtime errors observed');
const failed=Object.entries(evidence.scenarios).filter(([,v])=>v.status==='FAIL').map(([k])=>k);evidence.status=failed.length?'BASELINE_FAIL':'BASELINE_PASS';evidence.failedScenarios=failed;evidence.summary={scenarioCount:Object.keys(evidence.scenarios).length,pass:Object.values(evidence.scenarios).filter(x=>x.status==='PASS').length,fail:failed.length};write();console.log('C04_V3_BASELINE_RESULT',JSON.stringify({status:evidence.status,failed,related:evidence.metrics.related,workspace:evidence.metrics.workspace,density:evidence.metrics.density,decisionInfo:evidence.metrics.decisionInfo}));
}catch(error){evidence.status='MEASUREMENT_ERROR';evidence.error={name:error.name,message:error.message,stack:error.stack};write();throw error}finally{await browser.close().catch(()=>{});await api(`/repos/${owner}/${repo}/git/refs/heads/${encodeURIComponent(tempBranch)}`,{method:'DELETE'},true).catch(()=>{})}})();
