const assert=require('node:assert/strict');
const fs=require('node:fs');
const {chromium}=require('playwright');
const plan=JSON.parse(fs.readFileSync('static/c04-ui-usability-plan-v3.json','utf8'));
assert.equal(plan.version,3);assert.equal(plan.status,'FROZEN_BEFORE_BASELINE_MEASUREMENT');
const owner='kj2whvbzjn-hue',repo='tsugu',token=process.env.GH_TOKEN_E2E||process.env.GITHUB_TOKEN,targetUrl=process.env.C04_TARGET_URL||plan.target.publishedUrl,runId=process.env.GITHUB_RUN_ID||String(Date.now()),attempt=process.env.GITHUB_RUN_ATTEMPT||'1';
if(!token)throw new Error('GitHub token required');
const tempBranch=`c04-v3-acceptance-${runId}-${attempt}`;
const headers={Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'tsugu-c04-v3-acceptance'};
async function api(path,options={},allow404=false){const r=await fetch(`https://api.github.com${path}`,{...options,cache:'no-store',headers:{...headers,...(options.headers||{})}});const text=await r.text();if(allow404&&r.status===404)return null;if(!r.ok)throw new Error(`GitHub ${r.status}: ${text}`);return text?JSON.parse(text):null}
function emptyCore(){return{architectureNodes:[],workBoxes:[],tasks:[],decisions:[],issues:[],checks:[],approvals:[],evidences:[],evidenceVersions:[],repositories:[],repositoryBaselines:[],pathEntries:[],plannedChanges:[],actualChanges:[],relations:[]}}
function planProject(){return{schemaVersion:1,id:'66666666-7777-4888-8999-aaaaaaaaaaaa',name:'C-04 v3 判断中心UI・関連参照ナビゲーション計画',purpose:'判断に必要な情報を優先し関連根拠へ検索なしで到達するUIを検証する',rules:'凍結基準を結果後に変更しない',focus:'常設管理UI収納・判断情報優先・direct relation navigation',baseline:'C-04 v3 frozen commit 2d0ae47bea70735576a9410ba409f3a6c50865ed',changeControlEnabled:true,next:'同じ基準で候補UIを測定',stage:'検討',implementationApproved:false,completionApproved:false,core:emptyCore(),items:plan.improvements.map(x=>({id:x.id,kind:'検証',title:x.name,body:`Fix\n${x.fix}\n\nPASS\n${x.pass.join('\n')}`,status:'未確認',parentId:'',reason:'C-04 v3 frozen acceptance'}))}}
function workloadProject(){const items=[{id:'REL-A',kind:'構成',title:'関連起点 A',body:'Aの本文。',status:'未着手',parentId:'REL-B',reason:'A→B→C relation chain'},{id:'REL-B',kind:'構成',title:'関連中継 B',body:'Bの本文。',status:'要確認',parentId:'REL-C',reason:'A→B→C relation chain'},{id:'REL-C',kind:'構成',title:'関連終点 C',body:'Cの本文。',status:'未着手',parentId:'',reason:'A→B→C relation chain'}];for(let i=1;i<=193;i++)items.push({id:`FILL-${String(i).padStart(3,'0')}`,kind:'構成',title:`測定用項目 ${i}`,body:`filler ${i}`,status:i%5===0?'要確認':'未着手',parentId:'',reason:''});assert.equal(items.length,196);return{schemaVersion:1,id:'77777777-8888-4999-8aaa-bbbbbbbbbbbb',name:'C-04 v3 候補UI 196項目',purpose:'人間が目的・状態・関連根拠・次作業を最短で判断できるかを確認する',rules:'承認・完了を推測しない',focus:'REL-A→REL-B→REL-C direct relation navigation',baseline:'C-04 v3 candidate',changeControlEnabled:true,next:'固定基準を全PASS後に公開環境で再測定',stage:'検討',implementationApproved:false,completionApproved:false,core:emptyCore(),items}}
const evidence={type:'TSUGUC04DecisionUIV3AcceptanceEvidence',planVersion:3,planFrozenCommit:'2d0ae47bea70735576a9410ba409f3a6c50865ed',runId,attempt,targetUrl,tempBranch,status:'RUNNING',scenarios:{},runtime:{consoleErrors:[],pageErrors:[],apiErrors:[]},navigation:[],metrics:{}};
function mark(id,pass,metrics={}){evidence.scenarios[id]={status:pass?'PASS':'FAIL',metrics}}
function write(){fs.writeFileSync('c04-ui-usability-v3-evidence.json',JSON.stringify(evidence,null,2)+'\n')}
async function isVisible(loc){return loc.isVisible().catch(()=>false)}
async function openWorkspaceAction(page,name){const b=page.getByRole('button',{name,exact:true});if(await isVisible(b))return b;const menu=page.getByRole('button',{name:'接続・取込メニュー',exact:true});await menu.click();const item=page.getByRole('menuitem',{name,exact:true});await item.waitFor({state:'visible',timeout:5000});return item}
async function connect(page){await page.locator('#owner').fill(owner);await page.locator('#repo').fill(repo);await page.locator('#branch').fill(tempBranch);await page.locator('#token').fill('github_pat_c04_v3_placeholder');await page.getByRole('button',{name:'接続',exact:true}).click();await page.getByText(/GitHubから\d+件を読み込みました/).waitFor({timeout:30000})}
async function importAndSave(page,project,name){const chooserP=page.waitForEvent('filechooser');await (await openWorkspaceAction(page,'JSONから新規取込')).click();const chooser=await chooserP;await chooser.setFiles({name,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project,null,2)+'\n')});await page.getByRole('button',{name:'GitHubへ保存',exact:true}).waitFor({timeout:10000});await page.getByRole('button',{name:'GitHubへ保存',exact:true}).click();await page.getByText(/GitHubへ保存しました。案件版 1/).waitFor({timeout:30000})}
async function openWorkload(page){await page.evaluate(()=>scrollTo(0,0));const card=page.locator('.project-list button').filter({hasText:'C-04 v3 候補UI 196項目'}).first();await card.click();await page.getByRole('button',{name:'項目',exact:true}).click();await page.locator('#itemSearch').waitFor()}
async function searchOpen(page,id){const input=page.locator('#itemSearch');await input.fill(id);await input.press('Enter');const row=page.locator(`[data-item-row="${id}"]`);await row.waitFor({state:'visible'});await row.locator('[data-edit]').click();const modal=page.locator('.modal');await modal.getByText('項目編集',{exact:true}).waitFor();return modal}
async function fieldGaps(modal){const boxes=await modal.locator('.field:visible').evaluateAll(els=>els.map(e=>{const r=e.getBoundingClientRect();return{y:r.y,b:r.bottom}}).sort((a,b)=>a.y-b.y));const g=[];for(let i=1;i<boxes.length;i++){const v=boxes[i].y-boxes[i-1].b;if(v>=0)g.push(v)}return g}
(async()=>{const mainRef=await api(`/repos/${owner}/${repo}/git/ref/heads/main`);await api(`/repos/${owner}/${repo}/git/refs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:`refs/heads/${tempBranch}`,sha:mainRef.object.sha})});const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});let expectedWorkspace404=true,expectedMutation404=false,trackNav=false;page.on('pageerror',e=>evidence.runtime.pageErrors.push(e.message));page.on('console',m=>{if(m.type()!=='error')return;const t=m.text();if(t.includes('404')&&(expectedWorkspace404||expectedMutation404))return;evidence.runtime.consoleErrors.push(t)});page.on('response',r=>{if(!r.url().startsWith('https://api.github.com/')||r.status()<400)return;if(r.status()===404&&(expectedWorkspace404||expectedMutation404))return;evidence.runtime.apiErrors.push({url:r.url(),status:r.status()})});page.on('framenavigated',f=>{if(trackNav&&f===page.mainFrame())evidence.navigation.push(f.url())});page.on('dialog',async d=>{if(d.type()==='prompt')await d.accept('C-04 v3 acceptance');else await d.accept()});await page.addInitScript(({token,owner,repo})=>{const nf=window.fetch.bind(window);window.fetch=async(input,init={})=>{const url=typeof input==='string'?input:input.url;if(url==='https://api.github.com/user')return new Response(JSON.stringify({login:owner,id:1,type:'User'}),{status:200,headers:{'content-type':'application/json'}});const h=new Headers(init.headers||(typeof input!=='string'?input.headers:undefined)||{});if(url.startsWith('https://api.github.com/'))h.set('Authorization',`Bearer ${token}`);const r=await nf(input,{...init,headers:h,cache:'no-store'});if(url===`https://api.github.com/repos/${owner}/${repo}`&&r.ok){const d=await r.clone().json();d.private=true;d.permissions={admin:true,maintain:true,push:true,pull:true};return new Response(JSON.stringify(d),{status:200,headers:{'content-type':'application/json'}})}return r}},{token,owner,repo});try{await page.goto(`${targetUrl}?c04v3=${runId}`,{waitUntil:'networkidle',timeout:60000});trackNav=true;await connect(page);expectedWorkspace404=false;expectedMutation404=true;await importAndSave(page,planProject(),'c04-v3-plan.json');expectedMutation404=false;expectedMutation404=true;await importAndSave(page,workloadProject(),'c04-v3-workload.json');expectedMutation404=false;await (await openWorkspaceAction(page,'GitHubから再読込')).click();await page.getByText(/GitHubから2件を読み込みました/).waitFor({timeout:30000});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(100);
// UI3-01
const hiddenNames=['JSONから新規取込','GitHubから再読込','接続解除'];const hidden={};for(const n of hiddenNames)hidden[n]=!(await isVisible(page.getByRole('button',{name:n,exact:true})));const menu=page.getByRole('button',{name:'接続・取込メニュー',exact:true});const menuVisible=await isVisible(menu);const firstProject=page.locator('.project-list button').first();const fp=await firstProject.boundingBox();const firstRatio=fp?fp.y/844:99;const ui301=Object.values(hidden).every(Boolean)&&menuVisible&&firstRatio<=plan.budgets.firstProjectTopMaxViewportRatio;mark('UI3-01',ui301,{hidden,menuVisible,firstProjectTopRatio:firstRatio});assert.equal(ui301,true,JSON.stringify(evidence.scenarios['UI3-01']));
// UI3-02
await openWorkload(page);const row0=page.locator('.item-card-compact:visible').first();const rb=await row0.boundingBox();const eb=await row0.locator('[data-edit]').boundingBox();let modal=await searchOpen(page,'REL-A');const gaps=await fieldGaps(modal);const maxGap=Math.max(...gaps);const ui302=rb.height<=plan.budgets.mobileNormalItemRowHeightMaxPx&&maxGap<=plan.budgets.modalFieldBlockGapMaxPx&&eb.width>=44&&eb.height>=44;mark('UI3-02',ui302,{rowHeight:rb.height,maxFieldGap:maxGap,editTarget:eb});assert.equal(ui302,true,JSON.stringify(evidence.scenarios['UI3-02']));await modal.getByRole('button',{name:'閉じる',exact:true}).click();
// UI3-03
await page.getByRole('button',{name:'概要',exact:true}).click();const title=page.locator('.topbar h2');await title.scrollIntoViewIfNeeded();const startY=await page.evaluate(()=>scrollY);const overview=page.locator('.overview-panel');const purpose=overview.getByText('目的',{exact:true}),focus=overview.getByText('現在の焦点',{exact:true}),next=overview.getByText('次にすること',{exact:true});assert.equal(await isVisible(purpose),true);assert.equal(await isVisible(focus),true);assert.equal(await isVisible(next),true);await next.scrollIntoViewIfNeeded();const endY=await page.evaluate(()=>scrollY);const decisionTravel=Math.abs(endY-startY);const ui303=decisionTravel<=844*plan.budgets.projectDecisionInfoTravelMaxViewports;mark('UI3-03',ui303,{startY,endY,decisionTravel,limit:844});assert.equal(ui303,true,JSON.stringify(evidence.scenarios['UI3-03']));
// UI3-04/05/06/07
await page.getByRole('button',{name:'項目',exact:true}).click();modal=await searchOpen(page,'REL-A');let rel=modal.locator('.relation-card');await rel.waitFor({state:'visible'});const relText=(await rel.textContent())||'';const ui304=['REL-B','関連中継 B','構成','要確認'].every(x=>relText.includes(x));mark('UI3-04',ui304,{relationText:relText.trim()});assert.equal(ui304,true,JSON.stringify(evidence.scenarios['UI3-04']));const body=modal.locator('.field textarea:not(.code)').first();const draft='Aの本文。\n未保存draft保持テスト';await body.fill(draft);const navBefore=evidence.navigation.length;
await rel.click();let titleInput=page.locator('#itemTitle');assert.equal(await titleInput.inputValue(),'関連中継 B');const oneHop={actions:1,searches:0,listIntermediates:0,documentNavigations:evidence.navigation.length-navBefore};let breadcrumb=page.locator('[data-relation-jump="REL-A"]');await breadcrumb.waitFor({state:'visible'});await breadcrumb.click();assert.equal(await page.locator('#itemTitle').inputValue(),'関連起点 A');assert.equal(await page.locator('.field textarea:not(.code)').first().inputValue(),draft);const ui305=oneHop.actions<=plan.budgets.relatedOneHopMaxActions&&oneHop.searches===0&&oneHop.listIntermediates===0&&oneHop.documentNavigations===0;mark('UI3-05',ui305,{...oneHop,draftPreserved:true});assert.equal(ui305,true,JSON.stringify(evidence.scenarios['UI3-05']));
// chain A->B->C, then C->A
await page.locator('.relation-card[data-related-open="REL-B"]').click();await page.locator('.relation-card[data-related-open="REL-C"]').click();assert.equal(await page.locator('#itemTitle').inputValue(),'関連終点 C');const forward={actions:2,searches:0,listIntermediates:0};await page.locator('[data-relation-jump="REL-A"]').click();assert.equal(await page.locator('#itemTitle').inputValue(),'関連起点 A');assert.equal(await page.locator('.field textarea:not(.code)').first().inputValue(),draft);const chain={forwardActions:2,returnActions:1,searches:0,listIntermediates:0,documentNavigations:evidence.navigation.length-navBefore,draftPreserved:true};const ui306=chain.forwardActions<=plan.budgets.relatedChainTwoHopMaxForwardActions&&chain.returnActions<=plan.budgets.relatedChainReturnToOriginMaxActions&&chain.searches===0&&chain.listIntermediates===0&&chain.documentNavigations===0;mark('UI3-06',ui306,chain);assert.equal(ui306,true,JSON.stringify(evidence.scenarios['UI3-06']));
// input assistance, unresolved detection, title->stable id normalization
const input=page.locator('#itemParent');assert.equal(await input.getAttribute('aria-autocomplete'),'list');assert.equal(await input.getAttribute('list'),'itemRelationOptions');const option=page.locator('#itemRelationOptions option[value="REL-B"]');assert.equal(await option.count(),1);assert.match((await option.getAttribute('label'))||'',/関連中継 B/);await input.fill('UNKNOWN-REF');assert.equal(await input.getAttribute('aria-invalid'),'true');await page.locator('.relation-unresolved').waitFor({state:'visible'});await input.fill('関連中継 B');assert.equal(await input.getAttribute('aria-invalid'),'false');await page.locator('.relation-card[data-related-open="REL-B"]').waitFor({state:'visible'});await page.getByRole('button',{name:'編集内容へ反映',exact:true}).click();modal=await searchOpen(page,'REL-A');assert.equal(await page.locator('#itemParent').inputValue(),'REL-B');const ui307=true;mark('UI3-07',ui307,{ariaAutocomplete:'list',candidateByIdAndTitle:true,unknownDetected:true,titleNormalizedToStableId:true});await modal.getByRole('button',{name:'閉じる',exact:true}).click();
assert.equal(evidence.runtime.pageErrors.length,0,JSON.stringify(evidence.runtime.pageErrors));assert.equal(evidence.runtime.consoleErrors.length,0,JSON.stringify(evidence.runtime.consoleErrors));assert.equal(evidence.runtime.apiErrors.length,0,JSON.stringify(evidence.runtime.apiErrors));evidence.metrics.relation={oneHop,chain};evidence.status='PASS_UI3_01_TO_07';write();console.log('C04_V3_ACCEPTANCE_CORE_PASS',JSON.stringify({scenarios:evidence.scenarios,relation:evidence.metrics.relation,runtime:evidence.runtime}));}catch(e){evidence.status='FAIL';evidence.error={name:e.name,message:e.message,stack:e.stack};write();throw e}finally{await browser.close().catch(()=>{});await api(`/repos/${owner}/${repo}/git/refs/heads/${encodeURIComponent(tempBranch)}`,{method:'DELETE'},true).catch(()=>{})}})();
