const test=require('node:test');
const assert=require('node:assert/strict');
const Architecture=require('../static/core-architecture.js');
const Box=require('../static/core-box.js');
const Core=require('../static/core-rule-test.js');
const CS=require('../static/core-rule-test-changeset.js');
const BASE_SHA='a'.repeat(40), NEXT_SHA='b'.repeat(40), COMMIT_SHA='c'.repeat(40);
function box(){
  let a=Architecture.createProjectArchitecture({projectId:'p:b02',name:'B02',repositoryScopes:[{repositoryId:1,fullName:'acme/app'}]});
  a=Architecture.addArchitectureNode(a,{id:'n:root',name:'Root'});
  a=Architecture.addArchitectureNode(a,{id:'n:child',name:'Child',parentNodeId:'n:root'});
  let b=Box.seedSystemDefinitions(Box.migrateFromStageA(a));
  b=Box.createBoxInstance(b,{id:'i:root',boxDefinitionId:'system:box:component',boxDefinitionVersion:1,architectureNodeId:'n:root',config:{name:'root'}});
  b=Box.createBoxInstance(b,{id:'i:child',boxDefinitionId:'system:box:leaf',boxDefinitionVersion:1,architectureNodeId:'n:child',parentBoxInstanceId:'i:root',config:{name:'child'}});
  return b;
}
function state(){return Core.migrateFromB01(box());}
function pubRule(s,id,constraints,{version=1,supersedes=[]}={}){s=Core.createRuleDraft(s,{id,version,name:id,constraints,supersedes});return Core.publishRuleDefinition(s,id,version,{now:`2026-09-11T00:0${version}:00Z`});}
function pubTest(s,id='test:smoke',version=1){s=Core.createTestDraft(s,{id,version,name:id,runner:'shell',command:'npm test',evaluationConditions:{exitCode:0}});return Core.publishTestDefinition(s,id,version,{now:'2026-09-11T00:10:00Z'});}
function requirementReady({conflict=false}={}){let s=state();s=pubRule(s,'rule:parent',conflict?[{type:'REQUIRED',key:'tls'}]:[{type:'MIN',key:'coverage',value:70}]);s=Core.addRuleBinding(s,{id:'rb:parent',ruleDefinitionId:'rule:parent',ruleDefinitionVersion:1,targetType:'BOX_INSTANCE',boxInstanceId:'i:root',inheritToChildren:true});if(conflict){s=pubRule(s,'rule:child',[{type:'PROHIBITED',key:'tls'}]);s=Core.addRuleBinding(s,{id:'rb:child',ruleDefinitionId:'rule:child',ruleDefinitionVersion:1,targetType:'BOX_INSTANCE',boxInstanceId:'i:child'});}s=pubTest(s);s=Core.addRequirementSource(s,{id:'src:child',sourceBoxDefinitionId:'system:box:leaf',sourceBoxDefinitionVersion:1,testDefinitionId:'test:smoke',testDefinitionVersion:1,scope:'SELF'});return Core.deriveRequirements(s);}

test('B-01 migration is additive and direct write/Waiver remain closed',()=>{const s=state();assert.equal(s.boxRegistry.architecture.project.id,'p:b02');assert.equal(s.revision,1);assert.throws(()=>Core.assertDirectWriteDisabled(),e=>e.code==='RULE_TEST_CHANGESET_REQUIRED');assert.throws(()=>Core.assertWaiverUnavailable(),e=>e.code==='WAIVER_NOT_AVAILABLE_UNTIL_B03');});
test('comparable constraints use intersection: allowed set and bounds get stricter',()=>{const x=Core.reduceComparableConstraints([{type:'ALLOWED_SET',key:'mode',values:['A','B']},{type:'ALLOWED_SET',key:'mode',values:['B','C']},{type:'MIN',key:'n',value:1},{type:'MIN',key:'n',value:3},{type:'MAX',key:'n',value:10},{type:'MAX',key:'n',value:8}]);assert.equal(x.status,'VALID');assert.deepEqual(x.constraints.find(c=>c.key==='mode').values,['B']);assert.equal(x.constraints.find(c=>c.type==='MIN').value,3);assert.equal(x.constraints.find(c=>c.type==='MAX').value,8);});
test('incompatible or opaque rules become CONFLICT instead of guessed weakening',()=>{assert.equal(Core.reduceComparableConstraints([{type:'REQUIRED',key:'x'},{type:'PROHIBITED',key:'x'}]).status,'CONFLICT');assert.equal(Core.reduceComparableConstraints([{type:'OPAQUE',key:'policy',text:'high enough'}]).status,'CONFLICT');assert.equal(Core.reduceComparableConstraints([{type:'ALLOWED_SET',key:'x',values:['1']},{type:'MIN',key:'x',value:1}]).status,'CONFLICT');});
test('supersede cannot weaken a published rule without B-03 Waiver',()=>{let s=pubRule(state(),'rule:q',[{type:'MIN',key:'coverage',value:80}]);s=Core.createNextRuleVersion(s,'rule:q',1,{constraints:[{type:'MIN',key:'coverage',value:90}]});assert.doesNotThrow(()=>Core.publishRuleDefinition(s,'rule:q',2,{now:'2026-09-11T00:20:00Z'}));let w=pubRule(state(),'rule:q',[{type:'MIN',key:'coverage',value:80}]);w=Core.createNextRuleVersion(w,'rule:q',1,{constraints:[{type:'MIN',key:'coverage',value:70}]});assert.throws(()=>Core.publishRuleDefinition(w,'rule:q',2,{now:'2026-09-11T00:20:00Z'}),e=>e.code==='RULE_WEAKENING_REQUIRES_WAIVER');});
test('effective rules inherit from parent and expose rule origin plus inheritance path',()=>{let s=state();s=pubRule(s,'rule:root',[{type:'MIN',key:'coverage',value:70}]);s=Core.addRuleBinding(s,{id:'rb:root',ruleDefinitionId:'rule:root',ruleDefinitionVersion:1,targetType:'BOX_INSTANCE',boxInstanceId:'i:root',inheritToChildren:true});const e=Core.effectiveRulesForInstance(s,'i:child');assert.equal(e.status,'VALID');assert.equal(e.sources[0].bindingId,'rb:root');assert.deepEqual(e.sources[0].inheritancePath,['i:root','i:child']);});
test('published TestDefinition is content-hash fixed',()=>{let s=pubTest(state());const hash=s.testDefinitions[0].contentHash;assert.match(hash,/^sha256:[a-f0-9]{64}$/);const raw=JSON.parse(Core.serialize(s));raw.testDefinitions[0].command='echo tampered';assert.throws(()=>Core.validateState(raw),e=>e.code==='PUBLISHED_CONTENT_HASH_MISMATCH');});
test('Requirement derivation is idempotent by source/target/definition versions',()=>{let s=requirementReady();const one=s.testRequirements[0],rev=s.revision;s=Core.deriveRequirements(s);assert.equal(s.revision,rev);assert.equal(s.testRequirements[0].id,one.id);assert.equal(s.testRequirements[0].version,one.version);assert.equal(s.testRequirements[0].generatedHash,one.generatedHash);});
test('manual edit is stored separately and survives requirement re-derivation',()=>{let s=requirementReady();const rid=s.testRequirements[0].id;s=Core.setManualRequirementEdit(s,{requirementId:rid,note:'owner note',priority:'high',labels:['manual']},{actor:'u:1',now:'2026-09-11T01:00:00Z'});const before=Core.requirementView(s,rid);assert.equal(before.manualEdit.note,'owner note');s=Core.deriveRequirements(s);const after=Core.requirementView(s,rid);assert.equal(after.manualEdit.note,'owner note');assert.deepEqual(after.generated.effectiveRules.constraints,before.generated.effectiveRules.constraints);assert.throws(()=>Core.setManualRequirementEdit(s,{requirementId:rid,effectiveRules:{}},{actor:'u:1',now:'2026-09-11T01:01:00Z'}),e=>e.code==='MANUAL_EDIT_CANNOT_OVERRIDE_GENERATED');});
test('derived requirement records source Box version, TestDefinition version and Effective Rule origins',()=>{const s=requirementReady(),r=s.testRequirements[0];assert.equal(r.source.sourceBoxDefinitionId,'system:box:leaf');assert.equal(r.source.sourceBoxDefinitionVersion,1);assert.equal(r.testDefinition.id,'test:smoke');assert.equal(r.testDefinition.version,1);assert.equal(r.effectiveRules.sources[0].ruleDefinitionId,'rule:parent');assert.deepEqual(r.inheritancePaths,[['i:child']]);});
test('Draft snapshot can be saved with CONFLICT but FINAL gate rejects it',()=>{let s=requirementReady({conflict:true});assert.equal(s.testRequirements[0].effectiveRules.status,'CONFLICT');s=Core.createRequirementSnapshotDraft(s,{id:'snap:conflict',targetBoxInstanceId:'i:child'},{now:'2026-09-11T02:00:00Z'});assert.equal(s.requirementSnapshots[0].status,'DRAFT');assert.throws(()=>Core.finalizeRequirementSnapshot(s,'snap:conflict',{now:'2026-09-11T02:01:00Z'}),e=>e.code==='SNAPSHOT_GATE_CONFLICT');});
test('FINAL RequirementSnapshot fixes requirement version, rule origins, conditions and test version by hash',()=>{let s=requirementReady();s=Core.createRequirementSnapshotDraft(s,{id:'snap:ok',targetBoxInstanceId:'i:child'},{now:'2026-09-11T02:00:00Z'});s=Core.finalizeRequirementSnapshot(s,'snap:ok',{now:'2026-09-11T02:01:00Z'});const snap=s.requirementSnapshots[0],item=snap.requirementItems[0];assert.equal(snap.status,'FINAL');assert.match(snap.contentHash,/^sha256:[a-f0-9]{64}$/);assert.equal(item.testRequirementVersion,1);assert.equal(item.source.sourceBoxDefinitionVersion,1);assert.equal(item.testDefinition.version,1);assert.equal(item.evaluationConditions.exitCode,0);assert.ok(item.effectiveRules.sources.length);const raw=JSON.parse(Core.serialize(s));raw.requirementSnapshots[0].requirementItems[0].evaluationConditions.exitCode=1;assert.throws(()=>Core.validateState(raw),e=>e.code==='SNAPSHOT_CONTENT_HASH_MISMATCH');});
test('ChangeSet requires explicit timestamps for publish/manual/snapshot operations',()=>{const agg=CS.createAggregate(state());assert.throws(()=>CS.createChangeSet({id:'cs:x',projectId:agg.projectId,idempotencyKey:'i:x',baseRevision:agg.revision,baseBlobSha:BASE_SHA,createdBy:'u',operations:[{type:'PUBLISH_RULE',ruleDefinitionId:'r',ruleDefinitionVersion:1}]}),e=>e.code==='INVALID_TIMESTAMP');});
test('ChangeSet revalidates deterministic candidate and records audit/outbox with idempotent replay',()=>{const agg=CS.createAggregate(state());const cs=CS.createChangeSet({id:'cs:one',projectId:agg.projectId,idempotencyKey:'idem:one',baseRevision:agg.revision,baseBlobSha:BASE_SHA,createdBy:'u',operations:[{type:'CREATE_RULE_DRAFT',id:'r:one',version:1,name:'R',constraints:[{type:'MIN',key:'coverage',value:80}]},{type:'PUBLISH_RULE',ruleDefinitionId:'r:one',ruleDefinitionVersion:1,at:'2026-09-11T03:00:00Z'}]});const v=CS.validateChangeSet(agg,BASE_SHA,cs,{now:'2026-09-11T03:01:00Z'});const p=CS.prepareApply(agg,BASE_SHA,cs,v.validationRecord,{now:'2026-09-11T03:02:00Z'});assert.equal(p.status,'READY');assert.equal(p.aggregate.appliedChangeSets.length,1);assert.equal(p.aggregate.auditEvents.length,1);assert.equal(p.aggregate.outbox.length,1);const replay=CS.prepareApply(p.aggregate,NEXT_SHA,cs,v.validationRecord,{now:'2026-09-11T03:03:00Z'});assert.equal(replay.status,'IDEMPOTENT_REPLAY');});
function fakeGitHub(initial,{conflict=false,lag=false}={}){let content=CS.stableStringify(initial),sha=BASE_SHA,commitContent=null,puts=0;async function fetch(url,init={}){const method=init.method||'GET';if(method==='GET'){const ref=new URL(url).searchParams.get('ref');const useCommit=ref===COMMIT_SHA&&commitContent;const body=useCommit?{sha:NEXT_SHA,content:Buffer.from(commitContent).toString('base64')}:{sha,content:Buffer.from(content).toString('base64')};return new Response(JSON.stringify(body),{status:200});}if(method==='PUT'){puts++;if(conflict)return new Response(JSON.stringify({message:'sha mismatch'}),{status:409});const body=JSON.parse(init.body);if(body.sha!==sha)return new Response(JSON.stringify({message:'sha mismatch'}),{status:409});const next=Buffer.from(body.content,'base64').toString('utf8');commitContent=next;if(!lag){content=next;sha=NEXT_SHA;}return new Response(JSON.stringify({content:{sha:NEXT_SHA},commit:{sha:COMMIT_SHA}}),{status:200});}return new Response('{}',{status:405});}return{fetch,get puts(){return puts;},snapshot:()=>({content,sha})};}
test('Contents API CAS maps conflicts to STALE and commit-pinned readback survives branch propagation lag',async()=>{const agg=CS.createAggregate(state()),cs=CS.createChangeSet({id:'cs:cas',projectId:agg.projectId,idempotencyKey:'idem:cas',baseRevision:agg.revision,baseBlobSha:BASE_SHA,createdBy:'u',operations:[{type:'CREATE_TEST_DRAFT',id:'t',version:1,name:'T',runner:'shell',command:'true',evaluationConditions:{}},{type:'PUBLISH_TEST',testDefinitionId:'t',testDefinitionVersion:1,at:'2026-09-11T04:00:00Z'}]});const v=CS.validateChangeSet(agg,BASE_SHA,cs,{now:'2026-09-11T04:00:10Z'});const lag=fakeGitHub(agg,{lag:true});const ok=await CS.applyWithContentApi({fetch:lag.fetch,owner:'o',repo:'r',branch:'b',path:'x.json',changeSet:cs,validationRecord:v.validationRecord,now:'2026-09-11T04:01:00Z'});assert.equal(ok.status,'APPLIED');assert.equal(ok.commitSha,COMMIT_SHA);const bad=fakeGitHub(agg,{conflict:true});await assert.rejects(()=>CS.applyWithContentApi({fetch:bad.fetch,owner:'o',repo:'r',branch:'b',path:'x.json',changeSet:cs,validationRecord:v.validationRecord,now:'2026-09-11T04:01:00Z'}),e=>e.code==='STALE_CHANGESET');assert.equal(bad.puts,1);});