const test=require('node:test');
const assert=require('node:assert/strict');
const H=require('../static/core-changeset.js');
const G=require('../static/core-governance.js');
const C=require('../static/core-check-evidence.js');
const A=require('../static/core-assurance-event.js');
const T=require('../static/core-task-execution.js');
const CS=require('../static/core-assurance-event-changeset.js');
const actor={id:'editor:1',subject:'editor:1',kind:'HUMAN',role:'PROJECT_ADMIN'};
const now='2026-09-11T15:00:00Z';
function ref(type,id,version=1){return{type,id,version,hash:H.sha256(`${type}:${id}:${version}`)};}
function scope(){return{subject:ref('TASK_SUBJECT','subject:1'),requirementSnapshot:ref('REQUIREMENT_SNAPSHOT','req:1'),target:ref('COMMIT','a'.repeat(40))};}
function checkRegistry(result='PASS',s=scope(),id='check:1'){
 let r=C.createRegistry({projectId:'p'});
 r=C.registerEvidence(r,{id:'evidence:1',subject:s.subject,requirementSnapshot:s.requirementSnapshot,target:s.target},{actor,now});
 const bytes=Buffer.from('b06-evidence\n');
 const expectedSha256=H.sha256(bytes.toString());
 r=C.reserveEvidenceVersion(r,{id:'evv:1',evidenceId:'evidence:1',version:1,objectPath:'evidence/p/evidence-1/v1.bin',expectedSha256,expectedSize:bytes.length},{actor,now});
 const receipt={repositoryFullName:'kj2whvbzjn-hue/tsugu',branch:'e2e',path:'evidence/p/evidence-1/v1.bin',contentSha256:expectedSha256,size:bytes.length,gitBlobSha:'1'.repeat(40),commitSha:'2'.repeat(40),storedAt:now,readbackCommitSha:'2'.repeat(40),verifiedAt:now};
 r=C.recordEvidenceVerified(r,'evv:1',{storageReceipt:receipt},{actor,now});
 r=C.finalizeEvidenceVersion(r,'evv:1',{}, {actor,now});
 r=C.createCheck(r,{id,subject:s.subject,requirementSnapshot:s.requirementSnapshot,target:s.target,command:'node --test',runner:{kind:'GITHUB_ACTIONS',name:'b06',version:'1',os:'linux',runId:'1'},evidenceVersionIds:['evv:1'],result,resolvesCheckIds:[],startedAt:now,completedAt:now},{actor,now});
 return r;
}
function eventInput(id='event:ready',producerTaskId=null){const s=scope();return{id,version:1,name:id,scope:s,producerTaskId};}
function taskWithEvent(g,eventDef,opts={}){const cond={type:'EVENT',ref:{type:'EVENT_DEFINITION',id:eventDef.id,version:eventDef.version,hash:eventDef.contentHash},required:true,note:''};return G.createTask(g,{id:opts.id||'task:1',name:opts.id||'task:1',subject:scope().subject,purpose:'test',startConditions:[cond],completionConditions:opts.completionConditions||[],requiredStartApprovals:opts.requiredStartApprovals||[],requiredCompletionApprovals:opts.requiredCompletionApprovals||[]},{actor,now});}
function established(){let a=A.createRegistry({projectId:'p'});a=A.defineEvent(a,eventInput());const ed=a.eventDefinitions[0];a=A.recordAssuranceFromCheck(a,{id:'assurance:g1',generation:1,scope:scope(),checkId:'check:1',at:now},{checkEvidenceRegistry:checkRegistry(),now});a=A.evaluateEvent(a,ed.id,ed.version,{at:now},{now});return{a,ed};}

test('exact scoped PASS + FINALIZED evidence establishes current assurance/event',()=>{const {a,ed}=established();assert.equal(A.currentAssuranceStatus(a,scope()).status,'VALID');assert.equal(A.currentEventStatus(a,ed.id,1).status,'ESTABLISHED');const bad=scope();bad.target=ref('COMMIT','b'.repeat(40));assert.throws(()=>A.recordAssuranceFromCheck(a,{scope:bad,checkId:'check:1',generation:1},{checkEvidenceRegistry:checkRegistry()}),e=>e.code==='ASSURANCE_CHECK_SCOPE_MISMATCH');});

test('generation invalidation makes old PASS stale and cannot re-establish current event',()=>{let {a,ed}=established();a=A.beginEvaluationGeneration(a,{reason:'new commit',at:now},{now});assert.equal(a.generation,2);assert.equal(A.currentEventStatus(a,ed.id,1).status,'UNKNOWN');a=A.recordAssuranceFromCheck(a,{id:'late:g1',generation:1,scope:scope(),checkId:'check:1',at:now},{checkEvidenceRegistry:checkRegistry(),now});a=A.completeEvaluationGeneration(a);assert.equal(A.currentAssuranceStatus(a,scope()).status,'STALE');a=A.evaluateEvent(a,ed.id,1,{id:'event:g2:revoked',at:now},{now});assert.equal(A.currentEventStatus(a,ed.id,1).status,'REVOKED');a=A.recordAssuranceFromCheck(a,{id:'assurance:g2',generation:2,scope:scope(),checkId:'check:1',at:now},{checkEvidenceRegistry:checkRegistry(),now});a=A.evaluateEvent(a,ed.id,1,{id:'event:g2:ok',at:now},{now});assert.equal(A.currentEventStatus(a,ed.id,1).status,'ESTABLISHED');});

test('composite Task/Event dependency cycle is rejected',()=>{let a=A.createRegistry({projectId:'p'}),g=G.createRegistry({projectId:'p'});g=G.createTask(g,{id:'task:cycle',name:'cycle',subject:scope().subject},{actor,now});a=A.defineEvent(a,eventInput('event:cycle','task:cycle'));assert.throws(()=>A.addTaskDependency(a,{id:'dep:cycle',taskId:'task:cycle',eventDefinitionId:'event:cycle',eventVersion:1},{governance:g}),e=>e.code==='TASK_EVENT_DEPENDENCY_CYCLE');});

test('READY -> IN_PROGRESS -> HOLD after conservative generation invalidation',()=>{let {a,ed}=established(),g=G.createRegistry({projectId:'p'});g=taskWithEvent(g,ed);a=A.addTaskDependency(a,{id:'dep:1',taskId:'task:1',eventDefinitionId:ed.id,eventVersion:1},{governance:g});g=T.submitTask(g,a,'task:1',{actor,now});assert.equal(g.tasks[0].state,'READY');g=T.startTask(g,a,'task:1',{actor,now});assert.equal(g.tasks[0].state,'IN_PROGRESS');a=A.beginEvaluationGeneration(a,{reason:'changed',at:now},{now});g=T.reconcileTask(g,a,'task:1',{actor,now});assert.equal(g.tasks[0].state,'HOLD');assert.ok(G.activeHoldReasons(g,'task:1').length>=1);});

test('READY becomes BLOCKED, restores to READY; HOLD requires explicit resolution + Resume',()=>{let {a,ed}=established(),g=G.createRegistry({projectId:'p'});g=taskWithEvent(g,ed);a=A.addTaskDependency(a,{id:'dep:1',taskId:'task:1',eventDefinitionId:ed.id,eventVersion:1},{governance:g});g=T.submitTask(g,a,'task:1',{actor,now});let a2=A.beginEvaluationGeneration(a,{reason:'changed',at:now},{now});g=T.reconcileTask(g,a2,'task:1',{actor,now});assert.equal(g.tasks[0].state,'BLOCKED');a2=A.recordAssuranceFromCheck(a2,{generation:2,scope:scope(),checkId:'check:1',at:now},{checkEvidenceRegistry:checkRegistry(),now});a2=A.completeEvaluationGeneration(a2);a2=A.evaluateEvent(a2,ed.id,1,{id:'event:g2:ok',at:now},{now});g=T.reconcileTask(g,a2,'task:1',{actor,now});assert.equal(g.tasks[0].state,'READY');g=T.startTask(g,a2,'task:1',{actor,now});a2=A.beginEvaluationGeneration(a2,{reason:'again',at:now},{now});g=T.reconcileTask(g,a2,'task:1',{actor,now});const first=G.activeHoldReasons(g,'task:1');assert.ok(first.length>=1);g=G.holdTask(g,'task:1',{reasonId:'manual:1',reason:'manual'},{actor,now});assert.throws(()=>T.resumeTask(g,a2,'task:1',{actor,now}),e=>e.code==='TASK_RESUME_HOLD_REASONS_ACTIVE');});

test('completion requires current evaluation and effective final approval',()=>{let {a,ed}=established(),g=G.createRegistry({projectId:'p'});const req={approvalType:'FINAL',policyVersion:'v1',humanRequired:true};g=taskWithEvent(g,ed,{requiredCompletionApprovals:[req]});a=A.addTaskDependency(a,{id:'dep:1',taskId:'task:1',eventDefinitionId:ed.id,eventVersion:1},{governance:g});g=T.submitTask(g,a,'task:1',{actor,now});g=T.startTask(g,a,'task:1',{actor,now});assert.throws(()=>T.completeTask(g,a,'task:1',{actor,now}),e=>e.code==='TASK_COMPLETE_REVALIDATION_FAILED');g=G.createApproval(g,{id:'approval:final',approvalType:'FINAL',policyVersion:'v1',humanRequired:true,target:G.taskApprovalTarget(g,'task:1')},{actor,now});g=T.completeTask(g,a,'task:1',{actor,now});assert.equal(g.tasks[0].state,'DONE');});

test('DONE history remains DONE; invalidation creates repair Issue and repair Task',()=>{let {a,ed}=established(),g=G.createRegistry({projectId:'p'});g=taskWithEvent(g,ed);a=A.addTaskDependency(a,{id:'dep:1',taskId:'task:1',eventDefinitionId:ed.id,eventVersion:1},{governance:g});g=T.submitTask(g,a,'task:1',{actor,now});g=T.startTask(g,a,'task:1',{actor,now});g=T.completeTask(g,a,'task:1',{actor,now});assert.equal(g.tasks[0].state,'DONE');a=A.beginEvaluationGeneration(a,{reason:'post done change',at:now},{now});g=T.reconcileTask(g,a,'task:1',{actor,now});assert.equal(g.tasks.find(x=>x.id==='task:1').state,'DONE');assert.ok(g.issues.some(x=>x.taskId==='task:1'));assert.ok(g.tasks.some(x=>x.id.startsWith('repair:task:1:')));});

test('combined ChangeSet binds blob, embedded revisions and evaluation generation atomically',()=>{let {a,ed}=established(),g=G.createRegistry({projectId:'p'});g=taskWithEvent(g,ed);a=A.addTaskDependency(a,{id:'dep:1',taskId:'task:1',eventDefinitionId:ed.id,eventVersion:1},{governance:g});const agg=CS.createAggregate(g,a),blob='1'.repeat(40);const cs=CS.createChangeSet({id:'cs:1',projectId:'p',idempotencyKey:'idem:1',baseRevision:agg.revision,baseBlobSha:blob,baseGovernanceRevision:g.revision,baseAssuranceRevision:a.revision,baseGeneration:a.generation,operations:[{type:'TASK_SUBMIT',taskId:'task:1',at:now},{type:'TASK_START',taskId:'task:1',at:'2026-09-11T15:00:01Z'},{type:'BEGIN_EVALUATION_GENERATION',reason:'new source',at:'2026-09-11T15:00:02Z'}]});const v=CS.validateChangeSet(agg,blob,cs,{actor,checkEvidenceRegistry:checkRegistry(),now});assert.equal(v.candidate.assuranceEvent.generation,2);assert.equal(v.candidate.governance.tasks[0].state,'HOLD');assert.throws(()=>CS.validateChangeSet(agg,blob,{...cs,baseGeneration:2,payloadHash:undefined},{actor}),e=>e.code==='STALE_CHANGESET');});
