import assert from 'node:assert/strict';
import test from 'node:test';
import {build} from 'esbuild';
async function load(file){const b=await build({entryPoints:[file],bundle:true,platform:'node',format:'esm',write:false});return import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'));}
const {emptyCoreState,coreStateIssues,coreTransitionIssues}=await load('app/core-model.ts');
const sha='a'.repeat(40);
function valid(){const c=emptyCoreState();c.architectureNodes.push({id:'A',name:'Root',parentId:'',description:''});c.workBoxes.push({id:'W',architectureNodeId:'A',title:'Box',body:''});c.tasks.push({id:'T',workBoxId:'W',title:'Task',body:'',status:'未着手',dependsOnTaskIds:[],acceptanceCriteria:['done'],requiresHumanApproval:true});c.repositories.push({id:'R',provider:'github',owner:'o',name:'r',defaultBranch:'main'});c.repositoryBaselines.push({id:'B',repositoryId:'R',commitSha:sha,recordedAt:'2026-09-10T00:00:00Z'});c.pathEntries.push({id:'P',repositoryId:'R',baselineId:'B',parentId:'',path:'app',entryType:'directory',baselineHash:'',protection:'normal',protectionReason:''});c.evidences.push({id:'E',title:'spec',kind:'file',currentVersionId:'EV1',description:''});c.evidenceVersions.push({id:'EV1',evidenceId:'E',versionNo:1,originalFilename:'spec.txt',mimeType:'text/plain',byteSize:1,sha256:'1'.repeat(64)});c.checks.push({id:'C1',title:'first',status:'FAIL',targetType:'task',targetId:'T',result:'fail',evidenceText:'',resolvesCheckIds:[]});c.checks.push({id:'C2',title:'retest',status:'PASS',targetType:'task',targetId:'T',result:'pass',evidenceText:'',resolvesCheckIds:['C1']});c.relations.push({id:'REL1',type:'supports_check',fromType:'evidenceVersion',fromId:'EV1',toType:'check',toId:'C2'});return c;}
test('typed core accepts the minimal vertical model',()=>assert.deepEqual(coreStateIssues(valid()),[]));
test('typed relations reject invalid type pairs',()=>{const c=valid();c.relations.push({id:'bad',type:'supports_check',fromType:'task',fromId:'T',toType:'check',toId:'C1'});assert.match(coreStateIssues(c).join('\n'),/型組合せ/);});
test('failed checks remain addressable by a separate resolving retest',()=>{const c=valid();assert.equal(c.checks.find(x=>x.id==='C1').status,'FAIL');assert.deepEqual(c.checks.find(x=>x.id==='C2').resolvesCheckIds,['C1']);});
test('path entries reject missing baselines and cycles',()=>{const c=valid();c.pathEntries[0].parentId='P';c.pathEntries[0].baselineId='missing';assert.match(coreStateIssues(c).join('\n'),/Baseline/);assert.match(coreStateIssues(c).join('\n'),/自分自身/);});
test('typed core transition allows same-ID path move but rejects history rewrites',()=>{const old=valid(),next=structuredClone(old);next.pathEntries[0].path='src';assert.deepEqual(coreTransitionIssues(old,next),[]);const replaced=structuredClone(old);replaced.pathEntries=[];assert.match(coreTransitionIssues(old,replaced).join('\n'),/PathEntryを削除/);const versionRewrite=structuredClone(old);versionRewrite.evidenceVersions[0].sha256='2'.repeat(64);assert.match(coreTransitionIssues(old,versionRewrite).join('\n'),/EvidenceVersionを上書き/);const failRewrite=structuredClone(old);failRewrite.checks[0].status='PASS';assert.match(coreTransitionIssues(old,failRewrite).join('\n'),/過去FAIL Check/);});
