const test=require('node:test');
const assert=require('node:assert/strict');
const Sync=require('../static/core-sync.js');
const R=require('../static/core-sync-recovery.js');
const H1='1'.repeat(40),H2='2'.repeat(40),H3='3'.repeat(40),OLD='0'.repeat(40);
function response(body,status=200){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});}
function fakeGitHub({head=H3,compareStatus='ahead',commits=[H2,H3],branchStatus=200,compareHttp=200}={}){return async(url)=>{if(url.includes('/branches/main'))return response(branchStatus===200?{commit:{sha:head}}:{message:'down'},branchStatus);if(url.includes('/compare/'))return response(compareHttp===200?{status:compareStatus,commits:commits.map(sha=>({sha}))}:{message:'compare down'},compareHttp);return response({message:'unexpected'},500);};}
function seeded(){let s=Sync.createSyncAggregate({projectId:'p'});s=Sync.receiveCommit(s,{id:10,full_name:'acme/app'},H1,'main',{now:'2026-09-12T00:00:00Z'}).aggregate;let r=R.createRecoveryState({projectId:'p'});return{sync:s,recovery:r};}
async function establish(){let {sync,recovery}=seeded();const out=await R.reconcileBranch(recovery,sync,{fetch:fakeGitHub({head:H1,commits:[]}),repositoryId:10,repositoryFullName:'acme/app',branch:'main',now:'2026-09-12T00:00:01Z'});return out;}

test('delivery identity is separate and reverse notification never overwrites canonical branch head',async()=>{let x=await establish();x=await R.reconcileBranch(x.state,x.syncAggregate,{fetch:fakeGitHub(),repositoryId:10,repositoryFullName:'acme/app',branch:'main',now:'2026-09-12T00:01:00Z'});assert.equal(x.currentHeadSha,H3);let d=R.recordDelivery(x.state,{deliveryId:'delivery:new',repositoryId:10,eventName:'push',observedCommitSha:H3,payload:{after:H3}},{now:'2026-09-12T00:01:01Z'});d=R.recordDelivery(d.state,{deliveryId:'delivery:old',repositoryId:10,eventName:'push',observedCommitSha:OLD,payload:{after:OLD}},{now:'2026-09-12T00:01:02Z'});assert.equal(d.state.branches[0].canonicalHeadSha,H3);assert.equal(d.state.deliveries.length,2);const dup=R.recordDelivery(d.state,{deliveryId:'delivery:old',repositoryId:10,eventName:'push',observedCommitSha:OLD,payload:{after:OLD}},{now:'2026-09-12T00:01:03Z'});assert.equal(dup.status,'DEDUPED');});

test('reconciliation fills missed commits from fresh GitHub compare in returned order',async()=>{let x=await establish();x=await R.reconcileBranch(x.state,x.syncAggregate,{fetch:fakeGitHub(),repositoryId:10,repositoryFullName:'acme/app',branch:'main',now:'2026-09-12T00:02:00Z'});assert.equal(x.status,'CURRENT');assert.deepEqual(x.receivedCommitShas,[H2,H3]);assert.equal(x.syncAggregate.integrations.length,3);assert.equal(x.state.branches[0].canonicalHeadSha,H3);assert.equal(x.state.branches[0].consistency,'CURRENT');});

test('GitHub API failure is UNKNOWN/retry and does not guess deletion or mutate canonical head',async()=>{let x=await establish();const before=x.state.branches[0].canonicalHeadSha;x=await R.reconcileBranch(x.state,x.syncAggregate,{fetch:fakeGitHub({branchStatus:503}),repositoryId:10,repositoryFullName:'acme/app',branch:'main',now:'2026-09-12T00:03:00Z'});assert.equal(x.status,'UNKNOWN');assert.equal(x.requiresRetry,true);assert.equal(x.state.branches[0].canonicalHeadSha,before);assert.ok(x.state.incidents.some(i=>i.code==='GITHUB_API_UNKNOWN'));});

test('transient compare failure retains recovery base so a later retry can fill the missed gap',async()=>{let x=await establish();x=await R.reconcileBranch(x.state,x.syncAggregate,{fetch:fakeGitHub({head:H3,compareHttp:503}),repositoryId:10,repositoryFullName:'acme/app',branch:'main',now:'2026-09-12T00:03:10Z'});assert.equal(x.status,'UNKNOWN');assert.equal(x.state.branches[0].recoveryBaseSha,H1);x=await R.reconcileBranch(x.state,x.syncAggregate,{fetch:fakeGitHub({head:H3,commits:[H2,H3]}),repositoryId:10,repositoryFullName:'acme/app',branch:'main',now:'2026-09-12T00:03:20Z'});assert.equal(x.status,'CURRENT');assert.deepEqual(x.receivedCommitShas,[H2]);assert.deepEqual(x.dedupedCommitShas,[H3]);assert.equal(x.state.branches[0].recoveryBaseSha,null);});

test('non-fast-forward branch records current external fact but requires explicit full reconciliation',async()=>{let x=await establish();x=await R.reconcileBranch(x.state,x.syncAggregate,{fetch:fakeGitHub({compareStatus:'diverged',commits:[]}),repositoryId:10,repositoryFullName:'acme/app',branch:'main',now:'2026-09-12T00:04:00Z'});assert.equal(x.status,'UNKNOWN');assert.equal(x.currentHeadSha,H3);assert.equal(x.state.branches[0].canonicalHeadSha,H3);assert.equal(x.state.branches[0].consistency,'UNKNOWN');assert.ok(x.state.incidents.some(i=>i.code==='NON_FAST_FORWARD_BRANCH'));});

test('expired processing lease is reclaimed by the existing Sync lease contract',()=>{let {sync}=seeded();let c=Sync.claimNextJob(sync,{workerId:'worker:a',now:'2026-09-12T00:00:10Z',leaseSeconds:10});const out=R.recoverExpiredLeases(c.aggregate,{workerId:'worker:recovery',now:'2026-09-12T00:00:21Z',leaseSeconds:30,limit:5});assert.equal(out.expiredCount,1);assert.deepEqual(out.recoveredJobIds,[c.job.id]);assert.equal(out.aggregate.jobs[0].leaseOwner,'worker:recovery');assert.equal(out.aggregate.jobs[0].attempts,2);});

test('sync recovery cannot silently modify Approval Decision Waiver or Task state',async()=>{const business={tasks:[{id:'t1',state:'READY'}],approvals:[{id:'a1'}],waivers:[{id:'w1'}],decisions:[{id:'d1'}]};const fp=R.businessFingerprint(business);let x=await establish();x=await R.reconcileBranch(x.state,x.syncAggregate,{fetch:fakeGitHub(),repositoryId:10,repositoryFullName:'acme/app',branch:'main',now:'2026-09-12T00:05:00Z'});assert.equal(R.assertBusinessStateUnchanged(fp,business),true);const changed=structuredClone(business);changed.tasks[0].state='DONE';assert.throws(()=>R.assertBusinessStateUnchanged(fp,changed),e=>e.code==='BUSINESS_STATE_MUTATED_BY_SYNC_RECOVERY');});

test('delivery ID collision with different content is rejected',()=>{let r=R.createRecoveryState({projectId:'p'});r=R.recordDelivery(r,{deliveryId:'d1',repositoryId:10,eventName:'push',observedCommitSha:H1,payload:{after:H1}},{now:'2026-09-12T00:00:00Z'}).state;assert.throws(()=>R.recordDelivery(r,{deliveryId:'d1',repositoryId:10,eventName:'push',observedCommitSha:H2,payload:{after:H2}},{now:'2026-09-12T00:00:01Z'}),e=>e.code==='DELIVERY_ID_CONTENT_MISMATCH');});

test('load probe records sync and recalculation latency but unapproved profile cannot become acceptance PASS',()=>{let ticks=[0,12.5,21.75],i=0;const profile={id:'profile:provisional',approved:false,source:'G0 public repo only; private operational scale unavailable',integrationRecords:100,missedCommits:20,recalculationItems:200};const result=R.runLoadProbe({profile,clock:()=>ticks[i++],syncWork:()=>{},recalculate:()=>{},now:'2026-09-12T00:06:00Z'});assert.equal(result.syncMs,12.5);assert.equal(result.recalculationMs,9.25);assert.equal(R.assessLoadProbe(result).status,'AWAITING_PROFILE_APPROVAL');});

test('approved load profile enforces thresholds and requires cause when exceeded',()=>{let ticks=[0,8,20],i=0;const profile={id:'profile:approved',approved:true,source:'human-approved G0/operations profile',integrationRecords:100,missedCommits:20,recalculationItems:200,maxSyncMs:10,maxRecalculationMs:10,approvalRef:{type:'APPROVAL',id:'approval:scale:1'}};const result=R.runLoadProbe({profile,clock:()=>ticks[i++],now:'2026-09-12T00:07:00Z'});const missing=R.assessLoadProbe(result);assert.equal(missing.status,'EXCEEDED_CAUSE_REQUIRED');const recorded=R.assessLoadProbe(result,{cause:'recalculation fixture intentionally exceeds 10ms'});assert.equal(recorded.status,'EXCEEDED_RECORDED');assert.equal(recorded.accepted,true);assert.equal(recorded.exceedances[0].metric,'recalculationMs');});
