import test from 'node:test';
import assert from 'node:assert/strict';
import {loadRuntimeConfig,publicConfigSummary} from '../engineering-design-graph/config.mjs';

test('runtime config requires OIDC settings and parses database/rate limit/operations values',()=>{const config=loadRuntimeConfig({OIDC_ISSUER:'https://issuer.test',OIDC_AUDIENCE:'edg',OIDC_JWKS_URL:'https://issuer.test/jwks',PGHOST:'db',PGPORT:'5433',PGUSER:'edg',PGPASSWORD:'secret',PGDATABASE:'design',PGPOOL_MAX:'7',RATE_LIMIT_PER_MINUTE:'90',PORT:'4190',BROKER_URL:'https://broker.test/events',BROKER_SECRET:'broker-secret',OUTBOX_INTERVAL_MS:'2500',OTLP_ENDPOINT:'https://otel.test/v1/metrics',OTLP_AUTHORIZATION:'Bearer secret',OTLP_INTERVAL_MS:'9000'});assert.equal(config.port,4190);assert.equal(config.database.host,'db');assert.equal(config.database.port,5433);assert.equal(config.database.max,7);assert.equal(config.rateLimit.limit,90);assert.equal(config.outbox.intervalMs,2500);assert.equal(config.outbox.brokerUrl,'https://broker.test/events');assert.equal(config.telemetry.exportIntervalMs,9000)});

test('public config summary never exposes database broker or telemetry secrets',()=>{const config=loadRuntimeConfig({OIDC_ISSUER:'https://issuer.test',OIDC_AUDIENCE:'edg',OIDC_JWKS_URL:'https://issuer.test/jwks',PGPASSWORD:'top-secret',BROKER_URL:'https://broker.test',BROKER_SECRET:'broker-secret',OTLP_ENDPOINT:'https://otel.test',OTLP_AUTHORIZATION:'Bearer telemetry-secret'}),summary=publicConfigSummary(config),text=JSON.stringify(summary);assert.equal(text.includes('top-secret'),false);assert.equal(text.includes('broker-secret'),false);assert.equal(text.includes('telemetry-secret'),false);assert.equal('password' in summary.database,false);assert.equal(summary.outbox.brokerConfigured,true);assert.equal(summary.telemetry.otlpConfigured,true)});

test('runtime config fails closed when OIDC variables are absent',()=>{assert.throws(()=>loadRuntimeConfig({}),/OIDC_ISSUER/)});
