import test from 'node:test'; import assert from 'node:assert/strict';
import {detectCycles,makeSampleProject,readiness,requirementCoverage,runValidation,validateRelation} from '../engineering-design-graph/core.mjs';

test('sample project has full must requirement coverage',()=>{const p=makeSampleProject();const req=p.artifacts.find(a=>a.type==='requirement');assert.equal(requirementCoverage(p,req).score,100)});
test('sample relation type registry accepts task implements module',()=>{const p=makeSampleProject();const r=p.relations.find(r=>r.type==='implements');assert.deepEqual(validateRelation(p,r),{ok:true})});
test('invalid relation direction is rejected',()=>{const p=makeSampleProject();const req=p.artifacts.find(a=>a.type==='requirement');const task=p.artifacts.find(a=>a.type==='task');assert.equal(validateRelation(p,{...p.relations[0],type:'implements',fromArtifactId:req.id,toArtifactId:task.id}).ok,false)});
test('dependency cycle is detected',()=>{const p=makeSampleProject();const [sys,mod]=['system','module'].map(t=>p.artifacts.find(a=>a.type===t));p.relations.push({id:'c1',fromArtifactId:sys.id,toArtifactId:mod.id,type:'depends_on',status:'active'},{id:'c2',fromArtifactId:mod.id,toArtifactId:sys.id,type:'depends_on',status:'active'});assert.ok(detectCycles(p).length>0);assert.ok(runValidation(p).some(i=>i.ruleId==='VAL-DEP-001'))});
test('blocking question makes gate NOT_READY',()=>{const p=makeSampleProject();p.artifacts.push({id:'q1',projectId:p.id,key:'Q-001',type:'question',title:'Decision?',status:'draft',knowledgeState:'undefined',sourceIds:[],payload:{blocking:true,question:'Which consistency model?'}});assert.equal(readiness(p).status,'NOT_READY')});
test('approving task yields ready sample without warnings introduced by task',()=>{const p=makeSampleProject();p.artifacts.find(a=>a.type==='task').status='approved';const r=readiness(p);assert.equal(r.blocking.length,0);assert.ok(['READY','READY_WITH_WARNINGS'].includes(r.status))});
