import test from 'node:test';
import assert from 'node:assert/strict';
import {addChangeItem,applyChangeSet,buildImplementationPackage,createChangeSet,detectCycles,makeSampleProject,previewChangeSet,readiness,requirementCoverage,runValidation,VALIDATION_RULE_COUNT,validateRelation} from '../engineering-design-graph/core.mjs';

test('sample project has full must requirement coverage',()=>{const p=makeSampleProject();const req=p.artifacts.find(a=>a.type==='requirement');assert.equal(requirementCoverage(p,req).score,100)});
test('sample relation type registry accepts task implements module',()=>{const p=makeSampleProject();const r=p.relations.find(r=>r.type==='implements');assert.deepEqual(validateRelation(p,r),{ok:true})});
test('invalid relation direction is rejected',()=>{const p=makeSampleProject();const req=p.artifacts.find(a=>a.type==='requirement');const task=p.artifacts.find(a=>a.type==='task');assert.equal(validateRelation(p,{...p.relations[0],type:'implements',fromArtifactId:req.id,toArtifactId:task.id}).ok,false)});
test('dependency cycle is detected and blocks readiness',()=>{const p=makeSampleProject();const [sys,mod]=['system','module'].map(t=>p.artifacts.find(a=>a.type===t));p.relations.push({id:'c1',fromArtifactId:sys.id,toArtifactId:mod.id,type:'depends_on',status:'active'},{id:'c2',fromArtifactId:mod.id,toArtifactId:sys.id,type:'depends_on',status:'active'});assert.ok(detectCycles(p).length>0);assert.ok(runValidation(p).some(i=>i.ruleId==='VAL-DEP-001'));assert.equal(readiness(p).status,'NOT_READY')});
test('blocking question makes gate NOT_READY',()=>{const p=makeSampleProject();p.artifacts.push({id:'q1',projectId:p.id,key:'Q-001',type:'question',title:'Decision?',status:'draft',knowledgeState:'undefined',sourceIds:[],payload:{blocking:true,question:'Which consistency model?'}});assert.equal(readiness(p).status,'NOT_READY')});
test('validation engine exposes 20+ deterministic rules',()=>assert.ok(VALIDATION_RULE_COUNT>=20));
test('changeset preview does not mutate current artifact',()=>{const p=makeSampleProject(),a=p.artifacts.find(x=>x.id==='req1'),v=a.version,cs=createChangeSet(p,'edit requirement');addChangeItem(cs,{kind:'update_artifact',artifactId:a.id,previousStatus:a.status,patch:{title:'Updated requirement'}});const preview=previewChangeSet(p,cs.id);assert.equal(a.version,v);assert.equal(preview.staged.artifacts.find(x=>x.id===a.id).title,'Updated requirement')});
test('changeset apply creates immutable artifact version and increments revision',()=>{const p=makeSampleProject(),a=p.artifacts.find(x=>x.id==='req1'),before=p.artifactVersions.length,rev=p.revision,cs=createChangeSet(p,'edit requirement');addChangeItem(cs,{kind:'update_artifact',artifactId:a.id,previousStatus:a.status,patch:{title:'Updated requirement'}});applyChangeSet(p,cs.id);assert.equal(p.revision,rev+1);assert.equal(p.artifactVersions.length,before+1);assert.equal(p.artifacts.find(x=>x.id==='req1').version,2)});
test('implementation package is task rooted and readiness snapshot backed',()=>{const p=makeSampleProject();assert.equal(readiness(p).status,'READY');const pkg=buildImplementationPackage(p,['task1']);assert.deepEqual(pkg.manifest.rootTaskIds,['task1']);assert.ok(pkg.manifest.readinessSnapshotId);assert.ok(pkg.artifacts.some(a=>a.type==='requirement'))});
