import test from 'node:test';
import assert from 'node:assert/strict';
import {createHttpBroker} from '../engineering-design-graph/broker.mjs';
import {OutboxScheduler} from '../engineering-design-graph/outbox-scheduler.mjs';
import {toPrometheus,createOtlpHttpExporter} from '../engineering-design-graph/telemetry.mjs';
import {createMetrics} from '../engineering-design-graph/observability.mjs';

test('HTTP broker emits CloudEvents envelope and signature',async()=>{let seen;const broker=createHttpBroker({url:'https://broker.test/events',secret:'secret',fetchImpl:async(url,init)=>{seen={url,init};return{ok:true,status:202}}});await broker.publish({id:'e1',type:'artifact.updated',aggregateType:'artifact',aggregateId:'a1',payload:{x:1},createdAt:'2026-09-13T00:00:00Z'});assert.equal(seen.url,'https://broker.test/events');assert.equal(seen.init.headers['content-type'],'application/cloudevents+json');assert.match(seen.init.headers['x-edg-signature'],/^sha256=[a-f0-9]{64}$/);const body=JSON.parse(seen.init.body);assert.equal(body.specversion,'1.0');assert.equal(body.type,'artifact.updated');assert.deepEqual(body.data,{x:1})});

test('outbox scheduler skips overlapping tick and stops cleanly',async()=>{let release,calls=0;const gate=new Promise(r=>release=r),worker={async runOnce(){calls++;await gate;return{fetched:1,published:1,failed:0,errors:[]}}},scheduler=new OutboxScheduler({worker,intervalMs:100});const first=scheduler.tick(),second=await scheduler.tick();assert.deepEqual(second,{skipped:true});release();const result=await first;assert.equal(result.published,1);assert.equal(calls,1);scheduler.start();assert.ok(scheduler.timer);await scheduler.stop();assert.equal(scheduler.timer,null)});

test('Prometheus and OTLP exporters serialize metrics without secrets',async()=>{const metrics=createMetrics();metrics.inc('http_requests_total',{method:'GET',route:'/health/live',status:200});metrics.observe('http_request_duration_ms',12,{method:'GET',route:'/health/live'});const text=toPrometheus(metrics);assert.match(text,/http_requests_total/);assert.match(text,/http_request_duration_ms_count/);let payload;const exporter=createOtlpHttpExporter({endpoint:'https://otel.test/v1/metrics',fetchImpl:async(url,init)=>{payload={url,init};return{ok:true,status:200}}});const result=await exporter.export(metrics);assert.equal(result.ok,true);assert.equal(payload.url,'https://otel.test/v1/metrics');const body=JSON.parse(payload.init.body);assert.equal(body.resourceMetrics[0].resource.attributes[0].value.stringValue,'engineering-design-graph')});
