import test from 'node:test';
import assert from 'node:assert/strict';
import {createApiService} from '../engineering-design-graph/api-v1.mjs';
const call=(api,method,url,body,headers={})=>api.handle({method,url,body,headers});

test('project summary exposes validation and readiness',async()=>{const api=createApiService(),r=await call(api,'GET','/api/v1/projects/p1/summary');assert.equal(r.status,200);assert.ok(r.body.validation);assert.ok(r.body.readiness)});
test('artifact PATCH stages a changeset rather than mutating current state',async()=>{const api=createApiService(),before=await call(api,'GET','/api/v1/artifacts/req1');const staged=await call(api,'PATCH','/api/v1/artifacts/req1',{title:'Changed'});const after=await call(api,'GET','/api/v1/artifacts/req1');assert.equal(staged.status,202);assert.equal(after.body.title,before.body.title)});
test('changeset preview and apply update immutable version history',async()=>{const api=createApiService(),staged=await call(api,'PATCH','/api/v1/artifacts/req1',{title:'Changed'}),id=staged.body.changeSet.id;const preview=await call(api,'POST',`/api/v1/change-sets/${id}/impact-preview`);assert.equal(preview.status,200);const applied=await call(api,'POST',`/api/v1/change-sets/${id}/apply`);assert.equal(applied.status,200);const versions=await call(api,'GET','/api/v1/artifacts/req1/versions');assert.equal(versions.body.items.length,2)});
test('invalid relation is rejected before staging',async()=>{const api=createApiService(),r=await call(api,'POST','/api/v1/projects/p1/relations',{fromArtifactId:'req1',toArtifactId:'task1',type:'implements'});assert.equal(r.status,422);assert.equal(r.body.code,'RELATION_INVALID')});
test('implementation package endpoint is task rooted',async()=>{const api=createApiService(),r=await call(api,'POST','/api/v1/projects/p1/implementation-packages',{taskIds:['task1']});assert.equal(r.status,201);assert.deepEqual(r.body.manifest.rootTaskIds,['task1'])});
test('AI request returns pending candidate and accept stages ChangeSet',async()=>{const api=createApiService(),created=await call(api,'POST','/api/v1/projects/p1/ai-requests',{role:'requirement_reviewer',targetArtifactId:'req1'});assert.equal(created.status,202);assert.equal(created.body.candidates[0].status,'pending');const id=created.body.candidates[0].id;const accepted=await call(api,'POST',`/api/v1/ai-candidates/${id}/accept`,{});assert.equal(accepted.status,202);assert.equal(accepted.body.changeSet.items.length,1)});
test('ZIP package endpoint returns binary body and SHA-256 headers',async()=>{const api=createApiService(),r=await call(api,'POST','/api/v1/projects/p1/implementation-packages?format=zip',{taskIds:['task1']});assert.equal(r.status,201);assert.equal(r.headers['content-type'],'application/zip');assert.match(r.headers['x-content-sha256'],/^sha256:[0-9a-f]{64}$/);assert.equal(r.body[0],0x50);assert.equal(r.body[1],0x4b)});
