import assert from 'node:assert/strict';
import test from 'node:test';
import {build} from 'esbuild';
async function load(file){const b=await build({entryPoints:[file],bundle:true,platform:'node',format:'esm',write:false});return import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'));}
const coreM=await load('app/core-model.ts'),repo=await load('app/repository-service.ts');
const sha='a'.repeat(40),h1='1'.repeat(64),h2='2'.repeat(64);
function setup(){let c=coreM.emptyCoreState();c.evidences.push({id:'E',title:'e',kind:'file',currentVersionId:'EV',description:''});c.evidenceVersions.push({id:'EV',evidenceId:'E',versionNo:1,originalFilename:'e.txt',mimeType:'text/plain',byteSize:1,sha256:h1});c=repo.addRepository(c,{id:'R',provider:'github',owner:'o',name:'r',defaultBranch:'main'});c=repo.addRepositoryBaseline(c,{id:'B',repositoryId:'R',commitSha:sha,recordedAt:'2026-09-10T00:00:00Z'});c=repo.addPathEntry(c,{id:'ROOT',repositoryId:'R',baselineId:'B',parentId:'',path:'app',entryType:'directory',baselineHash:'',protection:'normal',protectionReason:''});c=repo.addPathEntry(c,{id:'DIR',repositoryId:'R',baselineId:'B',parentId:'ROOT',path:'app/features',entryType:'directory',baselineHash:'',protection:'normal',protectionReason:''});c=repo.addPathEntry(c,{id:'FILE',repositoryId:'R',baselineId:'B',parentId:'DIR',path:'app/features/a.ts',entryType:'file',baselineHash:h1,protection:'normal',protectionReason:''});return c;}
test('path move preserves stable IDs, descendants and version-fixed evidence relation',()=>{let c=setup();c=repo.linkEvidenceVersionToPath(c,{relationId:'REL',evidenceVersionId:'EV',pathEntryId:'FILE'});const before=c.relations.find(x=>x.id==='REL');c=repo.movePathEntry(c,{pathEntryId:'DIR',newParentId:'ROOT',newPath:'app/modules'});assert.equal(c.pathEntries.find(x=>x.id==='DIR').id,'DIR');assert.equal(c.pathEntries.find(x=>x.id==='FILE').path,'app/modules/a.ts');assert.deepEqual(c.relations.find(x=>x.id==='REL'),before);});
test('path move rejects self and descendant parents',()=>{let c=setup();assert.throws(()=>repo.movePathEntry(c,{pathEntryId:'ROOT',newParentId:'DIR',newPath:'app/features/root'}),/子孫/);assert.throws(()=>repo.movePathEntry(c,{pathEntryId:'DIR',newParentId:'DIR',newPath:'app/features/x'}),/自分自身/);});
test('planned and actual changes remain separate records',()=>{let c=setup();c=repo.addPlannedChange(c,{id:'PLAN',pathEntryId:'FILE',action:'modify',beforePath:'app/features/a.ts',afterPath:'app/features/a.ts',reason:'change',requiresHumanApproval:false});const before=JSON.stringify(c.pathEntries);c=repo.addActualChange(c,{id:'ACT',plannedChangeId:'PLAN',commitSha:'b'.repeat(40),beforeHash:h1,afterHash:h2,diffSummary:'changed'});assert.equal(JSON.stringify(c.pathEntries),before);assert.equal(c.plannedChanges.length,1);assert.equal(c.actualChanges.length,1);});
