import test from 'node:test';
import assert from 'node:assert/strict';
import * as D from '../static/workflow-domain.mjs';
import {GitStore,encode,decode} from '../static/workflow-git.mjs';
const human={login:'operator',type:'User',canWrite:true};
async function add(p,k,values){return D.upsert(p,k,{...D.recordTemplate(k,p),...values},human);}
async function seed(){let p=D.createProject('工程検証');p=await add(p,'architecture_nodes',{id:'ARCH-1',name:'実装'});p=await add(p,'work_boxes',{id:'BOX-1',node_id:'ARCH-1',title:'機能'});p=await add(p,'tasks',{id:'TASK-1',title:'作業',box_id:'BOX-1',acceptance_criteria:'結果を確認',requires_human_approval:true});return p;}
async function ready(){let p=await seed();p=await add(p,'checks',{id:'CHK-START',title:'開始条件',gate:'Implementation',status:'Passed',result:'条件成立',evidence:'仕様レビュー'});p=await D.transition(p,'planning',human);p=await D.approveTask(p,'TASK-1',human);return D.transition(p,'implementation',human);}
async function done(){let p=await ready();p=await D.changeTaskStatus(p,'TASK-1','Doing',human);p=await add(p,'checks',{id:'CHK-DONE',title:'成果確認',gate:'Completion',target_type:'Task',target_id:'TASK-1',status:'Passed',result:'期待値一致',evidence:'test run 1'});p=await D.changeTaskStatus(p,'TASK-1','Done',human);p=await D.transition(p,'verifying',human);return D.transition(p,'completion',human);}
const rejects=(fn,re)=>assert.rejects(fn,re);
test('complete project traverses all stages; terminal history and explicit reopen',async()=>{const p=await done();assert.equal(p.workflow.stage,'Completed');assert.equal(p.lifecycle.status,'Completed');assert.equal(p.tasks[0].status,'Done');assert.equal(p.workflow.completion_approval.by,'operator');assert.equal(p.workflow.completion_approval.content_hash.length,64);await D.validate(p);const reopened=await D.transition(p,'reopen',human);assert.equal(reopened.workflow.stage,'Verifying');assert.equal(reopened.lifecycle.status,'Active');assert.equal(reopened.tasks[0].status,'Done');assert.ok(reopened.history.length>p.history.length);});
test('empty implementation gate cannot pass',async()=>{let p=await seed();p=await D.transition(p,'planning',human);await rejects(()=>D.transition(p,'implementation',human),/Gate/);});
test('unapproved Completed import is rejected',async()=>{const p=await seed();p.workflow.stage='Completed';p.workspace.status='Completed';p.lifecycle.status='Completed';await rejects(()=>D.validate(p),/承認/);});
test('task cycles and missing foreign keys are rejected',async()=>{const p=await seed();const x=D.clone(p);x.tasks.push({...D.recordTemplate('tasks',x),id:'TASK-2',title:'依存',box_id:'BOX-1',acceptance_criteria:'条件',depends_on:['TASK-1']});x.tasks[0].depends_on=['TASK-2'];await rejects(()=>D.validate(x),/循環/);x.tasks[0].depends_on=[];x.tasks[1].depends_on=['missing'];await rejects(()=>D.validate(x),/参照先/);});
test('architecture cycles and deletion with inbound references fail',async()=>{const p=await seed();await rejects(()=>add(p,'architecture_nodes',{id:'ARCH-2',name:'子',parent_id:'ARCH-2'}),/循環/);await rejects(()=>D.removeRecord(p,'work_boxes','BOX-1',human),/参照先/);});
test('unknown task status is rejected, never coerced to Todo',async()=>{const p=await seed();p.tasks[0].status='unknown';await rejects(()=>D.validate(p),/不正/);});
test('task start requires individual approval and dependency completion',async()=>{let p=await ready();p.tasks[0].approval={status:'Pending',by:'',at:'',content_hash:''};await rejects(()=>D.changeTaskStatus(p,'TASK-1','Doing',human),/承認待ち/);});
test('Task cannot be marked Done via generic upsert or without completion Check',async()=>{const p=await ready();await rejects(()=>D.upsert(p,'tasks',{...p.tasks[0],status:'Done'},human),/専用操作/);const doing=await D.changeTaskStatus(p,'TASK-1','Doing',human);await rejects(()=>D.changeTaskStatus(doing,'TASK-1','Done',human),/完了Check/);});
test('manual pause survives validation and requires explicit resume',async()=>{const p=await ready();const paused=await D.transition(p,'pause',human);assert.equal(paused.lifecycle.status,'Paused');await rejects(()=>D.changeTaskStatus(paused,'TASK-1','Doing',human),/Active/);assert.equal((await D.transition(paused,'resume',human)).lifecycle.status,'Active');});
test('plan changes invalidate content-bound workflow and task approvals',async()=>{const p=await ready();const edited=await D.upsert(p,'tasks',{...p.tasks[0],acceptance_criteria:'異なる条件'},human);assert.equal(edited.workflow.stage,'Planning');assert.equal(edited.workflow.implementation_approval.status,'Pending');assert.equal(edited.tasks[0].approval.status,'Pending');await D.validate(edited);});
test('Failed remains immutable and retest resolves only matching target/gate',async()=>{let p=await ready();p=await add(p,'checks',{id:'FAIL-1',title:'失敗',gate:'Completion',target_type:'Task',target_id:'TASK-1',status:'Failed',result:'不一致',evidence:'run failed'});const failure=D.clone(p.checks.at(-1));await rejects(()=>D.upsert(p,'checks',{...failure,status:'Passed'},human),/変更/);await rejects(()=>D.removeRecord(p,'checks','FAIL-1',human),/証跡/);await rejects(()=>add(p,'checks',{title:'無関係',status:'Passed',gate:'Completion',result:'OK',evidence:'other',resolves_check_ids:['FAIL-1']}),/別対象/);p=await add(p,'checks',{id:'RETEST-1',title:'再検査',gate:'Completion',target_type:'Task',target_id:'TASK-1',status:'Passed',result:'修正確認',evidence:'new run',resolves_check_ids:['FAIL-1']});assert.deepEqual(p.checks.find(c=>c.id==='FAIL-1'),failure);assert.equal(D.resolvedBy(p,failure).id,'RETEST-1');assert.equal(D.gate(p,'Completion').ready,true);});
test('General required FAIL blocks execution and both gates',async()=>{let p=await ready();p=await add(p,'checks',{title:'全体の欠陥',status:'Failed',result:'欠陥',evidence:'audit'});assert.equal(D.gate(p,'Implementation').ready,false);assert.ok(D.taskBlockers(p,p.tasks[0]).length);});
test('resolution comparison uses actual instants across timezone offsets',async()=>{const p=await seed();const base={...D.recordTemplate('checks',p),title:'時刻検証',target_type:'Project',target_id:p.workspace.id,status:'Failed',result:'bad',evidence:'x',checked_by:'x',checked_at:'2026-09-12T00:00:00Z'};base.id='F';const a={...base,id:'A',status:'Passed',resolves_check_ids:['F'],checked_at:'2026-09-12T10:00:00+09:00'},b={...base,id:'B',status:'Passed',resolves_check_ids:['F'],checked_at:'2026-09-12T02:00:00Z'};p.checks=[base,a,b];await D.validate(p);assert.equal(D.resolvedBy(p,base).id,'B');});
test('partial AI record set is merged before reference validation',async()=>{const p=await seed();const r={...p.tasks[0],title:'名前更新'};delete r.approval;const merged=await D.mergeReturn(p,{project_id:p.workspace.id,instance_id:p.authority.instance_id,base_revision:0,summary:'編集',upserts:[{collection:'tasks',record:r}]},human);assert.equal(merged.tasks[0].title,'名前更新');assert.equal(merged.work_boxes.length,1);});
test('AI cannot forge approvals, workflow, lifecycle, foreign instance, stale base',async()=>{const p=await seed();const input={project_id:p.workspace.id,instance_id:p.authority.instance_id,base_revision:0,summary:'',upserts:[]};for(const key of ['workflow','lifecycle','authority'])await rejects(()=>D.mergeReturn(p,{...input,[key]:{}},human),/許可/);await rejects(()=>D.mergeReturn(p,{...input,instance_id:'other'},human),/identity/);await rejects(()=>D.mergeReturn(p,{...input,base_revision:1},human),/base_revision/);await rejects(()=>D.mergeReturn(p,{...input,upserts:[{collection:'tasks',record:p.tasks[0]}]},human),/approval/);});
test('save rejects deleting immutable failure/history',async()=>{const p=await ready();const q=D.clone(p);q.checks=[];await rejects(()=>D.assertSave(p,q),/承認後|Check/);const r=D.clone(p);r.history=[];await rejects(()=>D.assertSave(p,r),/履歴/);});
test('forged actor and old schemas fail closed',async()=>{const p=await seed();await rejects(()=>D.transition(p,'planning',{login:'AI',type:'Bot',canWrite:true}),/利用者/);await rejects(()=>D.validate({schemaVersion:1,items:[]}),/未対応/);p.schema_version='2.0';await rejects(()=>D.validate(p),/未対応/);});
test('candidate snapshot detects stale material and promotes exact reviewed contents',async()=>{let p=await seed();p=await add(p,'specifications',{id:'SPEC-1',title:'仕様',body:'元の内容'});p=await add(p,'specification_candidates',{id:'CAND-1',title:'新仕様',target_specification_id:'SPEC-1',body:'新しい内容',material_snapshot:{material_ids:['BOX-1'],decision_ids:[],snapshot_hash:''}});p=await D.captureCandidate(p,'CAND-1',human);const changed=await D.upsert(p,'work_boxes',{...p.work_boxes[0],body:'変更'},human);await rejects(()=>D.promoteCandidate(changed,'CAND-1',human),/素材が変わ/);const approved=await D.promoteCandidate(p,'CAND-1',human);assert.equal(approved.specifications[0].body,'新しい内容');assert.equal(approved.specifications[0].status,'Approved');assert.equal(approved.specifications[0].revision,2);});
test('snapshot completion approval cannot survive a forged changed payload',async()=>{const p=await done();p.tasks[0].title='差替え';await rejects(()=>D.validate(p),/承認対象|承認後/);});
function mockGit(){let remote=null,n=0,privateRepo=true,puts=0;const paths=[];return {get remote(){return remote;},set remote(v){remote=v;},get puts(){return puts;},paths,set private(v){privateRepo=v;},fetch:async(url,init)=>{const u=new URL(url);paths.push({url,method:init.method,body:init.body});const reply=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});if(u.pathname==='/user')return reply({login:'operator',type:'User'});if(u.pathname==='/repos/example/private')return reply({private:privateRepo,permissions:{push:true}});if(u.pathname.includes('/branches/'))return reply({name:'work'});if(init.method==='PUT'){puts++;const b=JSON.parse(init.body);assert.equal(b.branch,'work');if(remote&&b.sha!==remote.sha)return reply({},409);remote={content:b.content,sha:'blob-'+(++n)};return reply({content:{sha:remote.sha},commit:{sha:'commit-'+n}});}return remote?reply(remote):reply({},404);}};}
test('Git UTF-8 roundtrip, explicit branch, SHA/revision concurrency, reload persistence',async()=>{const api=mockGit(),git=new GitStore(api.fetch);await git.connect({owner:'example',repo:'private',branch:'work',token:'test-token'});let p=await seed();const saved=await git.save(p,'','初期');assert.equal(saved.project.revision,1);assert.equal(api.puts,1);const read=await git.open(p.workspace.id);assert.deepEqual(read.project,saved.project);assert.ok(api.paths.filter(r=>r.method==='GET'&&r.url.includes('/contents/')).every(r=>r.url.endsWith('?ref=work')));api.remote={...api.remote,sha:'concurrent'};await rejects(()=>git.save(saved.project,saved.sha,'競合'),/競合/);assert.equal(api.puts,1);assert.equal(decode(encode('日本語\n🎉')),'日本語\n🎉');assert.ok(!JSON.stringify(saved.project).includes('test-token'));});
test('missing canonical file cannot silently recreate saved project',async()=>{const api=mockGit(),git=new GitStore(api.fetch);await git.connect({owner:'example',repo:'private',branch:'work',token:'test-token'});const saved=await git.save(await seed(),'','new');api.remote=null;await rejects(()=>git.save(saved.project,saved.sha,'bad'),/削除/);assert.equal(api.puts,1);});
test('public data repository denied and failed connection clears actor',async()=>{const api=mockGit(),git=new GitStore(api.fetch);api.private=false;await rejects(()=>git.connect({owner:'example',repo:'private',branch:'work',token:'test-token'}),/Private/);assert.equal(git.actor,null);assert.equal(git.connection,null);});
test('SOURCE_UPDATE completion requires a pinned Applied implementation record',async()=>{let p=await ready();p=await D.upsert(p,'tasks',{...p.tasks[0],work_type:'SOURCE_UPDATE'},human);p=await D.approveTask(p,'TASK-1',human);p=await D.transition(p,'implementation',human);p=await D.changeTaskStatus(p,'TASK-1','Doing',human);p=await add(p,'checks',{title:'実装確認',gate:'Completion',target_type:'Task',target_id:'TASK-1',status:'Passed',result:'PASS',evidence:'test log'});await rejects(()=>D.changeTaskStatus(p,'TASK-1','Done',human),/実装記録/);p=await add(p,'implementation_records',{title:'適用',task_ids:['TASK-1'],repository:'https://github.com/example/source',commit_sha:'a'.repeat(40),result:'Applied',evidence:'fixed commit and test log'});p=await D.changeTaskStatus(p,'TASK-1','Done',human);assert.equal(p.tasks[0].status,'Done');});
test('full-record validation rejects Done with no task completion checks',async()=>{const p=await seed();p.tasks[0].requires_human_approval=false;p.tasks[0].status='Done';await rejects(()=>D.validate(p),/Completion Check/);});

// Registration is a distinct planning format; it cannot import execution authority.
const I=await import('../static/workflow-import.mjs');
const {readFile}=await import('node:fs/promises');
const importExample=await readFile(new URL('../static/project-import-example.json',import.meta.url),'utf8');
const registration=projects=>JSON.stringify({schema_version:I.IMPORT_SCHEMA,projects});
test('published sample imports two independent projects with preserved references and initial authority',async()=>{
 const projects=await I.prepareImport(importExample,human);assert.equal(projects.length,2);
 assert.notEqual(projects[0].workspace.id,projects[1].workspace.id);
 for(const p of projects){await D.validate(p);assert.equal(p.revision,0);assert.equal(p.workflow.stage,'Discovery');assert.equal(p.lifecycle.status,'Active');assert.ok(p.tasks.every(t=>t.status==='Todo'&&t.approval.status==='Pending'));assert.equal(p.history[0].by,human.login);}
 assert.equal(projects[0].checks[0].target_id,projects[0].workspace.id);assert.deepEqual(projects[0].tasks[1].depends_on,['TASK-1']);
 const again=await I.prepareImport(importExample,human);assert.notEqual(again[0].workspace.id,projects[0].workspace.id);
});
test('registration accepts minimal input and BOM, fills defaults but rejects wrong types and unknown fields',async()=>{
 const [p]=await I.prepareImport('\ufeff'+registration([{name:'最小'}]),human);assert.equal(p.workspace.name,'最小');assert.equal(p.tasks.length,0);
 for(const project of [{name:4},{name:'型',project_context:{purpose:5}},{name:'未知',purpose:'x'},{name:'承認',workflow:{stage:'Completed'}}])await assert.rejects(()=>I.prepareImport(registration([project]),human));
 await assert.rejects(()=>I.prepareImport('not json',human),/構文/);await assert.rejects(()=>I.prepareImport(JSON.stringify(p),human),/新規登録用/);
 await assert.rejects(()=>I.prepareImport(registration([{name:'最小'}]),null),/接続/);
});
test('registration rejects evidence and approval injection without silently resetting claims',async()=>{
 for(const [collection,row] of [ ['tasks',{approval:{status:'Approved'}}],['tasks',{status:'Done'}],['checks',{status:'Passed'}],['checks',{checked_by:'someone'}],['checks',{result:'PASS'}],['decisions',{status:'Approved'}],['specifications',{status:'Verified'}],['specification_candidates',{status:'approved'}]]){
  const input=JSON.parse(importExample);const p=input.projects[0];p[collection]??=[{id:'R',title:'記録'}];Object.assign(p[collection][0],row);
  await assert.rejects(()=>I.prepareImport(JSON.stringify(input),human));
 }
 for(const key of ['implementation_records','artifacts','system_events','history','authority','items','core'])await assert.rejects(()=>I.prepareImport(registration([{name:'不可',[key]:[]}]),human),/未対応/);
});
test('registration validates entire batch and forward references, missing parents, IDs and cycles',async()=>{
 let input=JSON.parse(importExample);input.projects[0].tasks.reverse();await I.prepareImport(JSON.stringify(input),human);
 input.projects[1].tasks[0].depends_on=['missing'];await assert.rejects(()=>I.prepareImport(JSON.stringify(input),human),/案件 2.*参照先/);
 for(const change of [p=>p.tasks.push({...p.tasks[0]}),p=>p.tasks[0].depends_on=['TASK-2'],p=>delete p.work_boxes[0].node_id,p=>p.tasks[0].requires_human_approval='true']){
  input=JSON.parse(importExample);change(input.projects[0]);await assert.rejects(()=>I.prepareImport(JSON.stringify(input),human));
 }
});
test('registration limits size, record count, project count and duplicate names',async()=>{
 for(const projects of [[],Array.from({length:21},(_,i)=>({name:'P'+i})),[{name:'same'},{name:'same'}],[{name:'多い',architecture_nodes:Array.from({length:1001},(_,i)=>({id:'N'+i,name:'N'}))}]])await assert.rejects(()=>I.prepareImport(registration(projects),human));
 await assert.rejects(()=>I.prepareImport(' '.repeat(I.MAX_IMPORT_BYTES+1),human),/2MB/);
});
test('batch writes all validated projects once and returns per-project commit receipts',async()=>{
 const projects=await I.prepareImport(importExample,human),receipt=I.importReceipt(projects),saved=[];
 const store={verify:async()=>human,connection:{owner:'test',repo:'private',branch:'work'},save:async(p,sha)=>{assert.equal(sha,'');saved.push(p.workspace.id);return {project:{...p,revision:1},commit_sha:'a'.repeat(40)};}};
 await I.registerBatch(store,projects,receipt);assert.equal(saved.length,2);assert.ok(receipt.entries.every(e=>e.status==='登録済み'));assert.equal(receipt.connection.branch,'work');
 await assert.rejects(()=>I.registerBatch(store,projects,receipt),/実行済み/);assert.equal(saved.length,2);
});
test('batch prevalidation writes nothing on invalid later project; partial failure stops and cannot retry',async()=>{
 const projects=await I.prepareImport(registration([{name:'A'},{name:'B'},{name:'C'}]),human);let calls=0;
 const store={verify:async()=>human,connection:{branch:'main'},save:async p=>{calls++;if(calls===2)throw new Error('保存結果不明');return {project:{...p,revision:1},commit_sha:'a'.repeat(40)};}};
 const bad=D.clone(projects);bad[2].schema_version='bad';await assert.rejects(()=>I.registerBatch(store,bad,I.importReceipt(bad)));assert.equal(calls,0);
 const receipt=I.importReceipt(projects);await I.registerBatch(store,projects,receipt);assert.equal(calls,2);assert.deepEqual(receipt.entries.map(e=>e.status),['登録済み','要確認','未登録']);
 await assert.rejects(()=>I.registerBatch(store,projects,receipt));assert.equal(calls,2);assert.ok(receipt.entries[1].message.includes('不明'));
});
