'use client';
import {useEffect,useMemo,useState} from 'react';
import {evidenceKinds,type CoreState,type Evidence,type EvidenceVersionRef} from './core-model';
import {linkEvidenceVersionToPath,RepositoryModelError} from './repository-service';

type ApiVersion={id:string;evidenceId:string;versionNo:number;originalFilename:string;mimeType:string;byteSize:number;sha256:string;storageState:string;createdAt:string};
type ApiEvidence={id:string;projectId:string;title:string;kind:string;description:string;currentVersionId:string;versions:ApiVersion[]};
type EvidenceListResponse={evidences:ApiEvidence[]};
type EvidenceUploadResponse={evidenceId:string;currentVersionId:string;version:ApiVersion;idempotent:boolean};
type ApiErrorResponse={error:string};
type Attempt={evidenceId:string;operationId:string;signature:string};
const isRecord=(value:unknown):value is Record<string,unknown>=>typeof value==='object'&&value!==null&&!Array.isArray(value);
const apiError=(value:unknown,fallback:string)=>isRecord(value)&&typeof value.error==='string'?value.error:fallback;
function evidenceListResponse(value:unknown):EvidenceListResponse{if(!isRecord(value)||!Array.isArray(value.evidences))throw Error('Evidence一覧の応答形式が不正です');return {evidences:value.evidences as ApiEvidence[]};}
function evidenceUploadResponse(value:unknown):EvidenceUploadResponse{if(!isRecord(value)||!isRecord(value.version)||typeof value.evidenceId!=='string'||typeof value.currentVersionId!=='string'||!value.currentVersionId||typeof value.version.id!=='string'||typeof value.version.versionNo!=='number'||typeof value.version.evidenceId!=='string')throw Error('Evidence登録の応答形式が不正です');return value as unknown as EvidenceUploadResponse;}
const signature=(file:File,title:string,kind:string)=>[file.name,file.size,file.type,title,kind].join('\u0000');
const versionRef=(v:ApiVersion):EvidenceVersionRef=>({id:v.id,evidenceId:v.evidenceId,versionNo:v.versionNo,originalFilename:v.originalFilename,mimeType:v.mimeType,byteSize:v.byteSize,sha256:v.sha256});
function syncEvidence(core:CoreState,row:ApiEvidence,version?:ApiVersion){const next=structuredClone(core),e:Evidence={id:row.id,title:row.title,kind:row.kind as Evidence['kind'],currentVersionId:row.currentVersionId||version?.id||'',description:row.description};const at=next.evidences.findIndex(x=>x.id===e.id);if(at>=0)next.evidences[at]=e;else next.evidences.push(e);for(const v of row.versions){const ref=versionRef(v),vi=next.evidenceVersions.findIndex(x=>x.id===ref.id);if(vi>=0)next.evidenceVersions[vi]=ref;else next.evidenceVersions.push(ref);}if(version&&!next.evidenceVersions.some(x=>x.id===version.id))next.evidenceVersions.push(versionRef(version));return next;}

export default function EvidencePanel({projectId,core,onChange,disabled=false}:{projectId:string;core:CoreState;onChange:(core:CoreState)=>void;disabled?:boolean}){
 const [targetId,setTargetId]=useState(''),[rows,setRows]=useState<ApiEvidence[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[file,setFile]=useState<File|null>(null),[title,setTitle]=useState(''),[kind,setKind]=useState<Evidence['kind']>('file'),[description,setDescription]=useState(''),[attempt,setAttempt]=useState<Attempt|null>(null),[pathByVersion,setPathByVersion]=useState<Record<string,string>>({});
 const pathEntries=useMemo(()=>[...core.pathEntries].sort((a,b)=>a.path.localeCompare(b.path,'ja')),[core.pathEntries]);
 async function load(){setError('');try{const r=await fetch('/api/evidence?projectId='+encodeURIComponent(projectId),{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(30000)}),raw:unknown=await r.json();if(!r.ok)throw Error(apiError(raw,'Evidenceを読み込めません'));setRows(evidenceListResponse(raw).evidences);}catch(e:unknown){setError(e instanceof Error?e.message:'Evidenceを読み込めません')}}
 useEffect(()=>{load()},[projectId]);
 async function upload(){if(!file||!title.trim()||busy)return;setBusy(true);setError('');const sig=signature(file,title.trim(),kind),a=attempt?.signature===sig?attempt:{evidenceId:targetId||crypto.randomUUID(),operationId:crypto.randomUUID(),signature:sig};setAttempt(a);try{const form=new FormData();form.set('projectId',projectId);form.set('evidenceId',a.evidenceId);form.set('operationId',a.operationId);form.set('title',title.trim());form.set('kind',kind);form.set('description',description);form.set('file',file);const r=await fetch('/api/evidence',{method:'POST',credentials:'same-origin',body:form,signal:AbortSignal.timeout(60000)}),raw:unknown=await r.json();if(!r.ok)throw Error(apiError(raw,'Evidenceを登録できません'));const data=evidenceUploadResponse(raw);await load();const row:ApiEvidence={id:a.evidenceId,projectId,title:title.trim(),kind,description,currentVersionId:data.currentVersionId,versions:[...(rows.find(x=>x.id===a.evidenceId)?.versions||[]),data.version]};onChange(syncEvidence(core,row,data.version));setAttempt(null);setTargetId('');setFile(null);setTitle('');setDescription('');}catch(e:unknown){setError(e instanceof Error?e.message:'Evidenceを登録できません')}finally{setBusy(false)}}
 function sync(row:ApiEvidence){onChange(syncEvidence(core,row));}
 function link(row:ApiEvidence,version:ApiVersion){const pathId=pathByVersion[version.id];if(!pathId)return;try{let next=syncEvidence(core,row,version);next=linkEvidenceVersionToPath(next,{relationId:crypto.randomUUID(),evidenceVersionId:version.id,pathEntryId:pathId});onChange(next);setError('');}catch(e){setError(e instanceof RepositoryModelError?e.message:'EvidenceとPathを関連付けできません')}}
 return <div className="overview"><section className="panel"><div className="section-title"><h2>Evidenceを直接登録</h2><span className="count">{rows.length}</span></div><p className="muted">旧JSON取込とは別に原本を保存します。版は上書きせず、同じoperation IDで失敗を再試行します。登録後は案件の変更保存で型付き参照を固定してください。</p><label className="field"><span>登録先</span><select value={targetId} disabled={busy} onChange={e=>{const id=e.target.value,row=rows.find(r=>r.id===id);setTargetId(id);setAttempt(null);setTitle(row?.title||'');setKind((row?.kind as Evidence['kind'])||'file');setDescription(row?.description||'')}}><option value="">新しい資料</option>{rows.map(row=><option key={row.id} value={row.id}>{row.title} — 新版を追加</option>)}</select></label><label className="field"><span>タイトル</span><input disabled={!!targetId||busy} value={title} onChange={e=>{setTitle(e.target.value);setAttempt(null)}}/></label><label className="field"><span>種別</span><select disabled={!!targetId||busy} value={kind} onChange={e=>{setKind(e.target.value as Evidence['kind']);setAttempt(null)}}>{evidenceKinds.map(x=><option value={x} key={x}>{x}</option>)}</select></label><label className="field"><span>説明</span><textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="field"><span>原本ファイル</span><input type="file" onChange={e=>{setFile(e.target.files?.[0]||null);setAttempt(null)}}/></label>{attempt&&<p className="muted">再試行operation: {attempt.operationId}</p>}<button className="primary" disabled={disabled||busy||!file||!title.trim()} onClick={upload}>{busy?'登録中…':attempt?'同じoperationで再試行':'原本を登録'}</button>{error&&<p className="error" role="alert">{error}</p>}</section><section className="panel"><h2>登録済みEvidence</h2>{!rows.length?<p className="empty-row">Evidenceはまだありません。</p>:rows.map(row=><div className="history-row" key={row.id}><strong>{row.title}</strong><small>{row.kind} · Evidence ID {row.id}</small>{row.versions.map(v=><div key={v.id} className="diff"><strong>版 {v.versionNo}: {v.originalFilename}</strong><p className="muted">SHA-256 {v.sha256} · {v.byteSize.toLocaleString()} bytes · version {v.id}</p><div className="actions"><a className="button" href={`/api/evidence?projectId=${encodeURIComponent(projectId)}&versionId=${encodeURIComponent(v.id)}`} target="_blank" rel="noreferrer">原本を取得</a><select aria-label={`${v.originalFilename}の関連Path`} value={pathByVersion[v.id]||''} onChange={e=>setPathByVersion(prev=>({...prev,[v.id]:e.target.value}))}><option value="">Pathを選択</option>{pathEntries.map(p=><option value={p.id} key={p.id}>{p.path}</option>)}</select><button disabled={disabled||!pathByVersion[v.id]} onClick={()=>link(row,v)}>この版をPathへ固定参照</button></div></div>)}{!core.evidences.some(x=>x.id===row.id)&&<button disabled={disabled} onClick={()=>sync(row)}>型付き中核へ同期</button>}</div>)}</section></div>;
}
