'use client';
import {useEffect,useState} from 'react';
import LargeTextField,{ExpandedTextDialog} from './large-text';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
export const sourceLabels:Record<string,string>={schema_version:'形式の版',workspace:'案件',project_context:'目的・概要',current_focus:'現在の焦点',source_baseline:'ソース基準',project_rules:'方針',lifecycle:'ライフサイクル',implementation_records:'実装記録',discussions:'議論',decisions:'決定',specifications:'仕様',specification_candidates:'仕様候補',system_nodes:'システム構成',system_contracts:'システム契約',system_connections:'接続',system_flags:'フラグ',system_events:'イベント',system_impacts:'影響',architecture_nodes:'構成',work_boxes:'作業箱',tasks:'タスク',checks:'検証',workflow:'工程・承認',history:'過去の履歴',authority:'正本情報'};
export default function ImportedSource({projectId}:{projectId:string}){
 const [detailOpen,setDetailOpen]=useState(false);
 const [data,setData]=useState<Record<string,any>|null>(null),[error,setError]=useState(''),[section,setSection]=useState('specifications'),[query,setQuery]=useState(''),[page,setPage]=useState(0),[selected,setSelected]=useState<any>(null);
 async function load(){setError('');try{const r=await fetch('/api/projects?original='+encodeURIComponent(projectId),{credentials:'same-origin',signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('元JSONを読み込めません。案件一覧からサインイン状態を確認してください。');setData(await r.json())}catch(e:any){setError(e.message)}}
 useEffect(()=>{load()},[projectId]);
 if(error)return <div className="error" role="alert">{error}<button onClick={load}>再試行</button></div>;
 if(!data)return <p role="status">元JSONを読み込んでいます…</p>;
 const source=data[section],rows=Array.isArray(source)?source:[source],filtered=rows.filter(v=>JSON.stringify(v??'').toLowerCase().includes(query.toLowerCase()));
 return <section className="panel"><h2>取込時の資料</h2><p className="muted">元JSONの全情報を読み取り専用で確認できます。取り込んだ後の編集は各タブに保存され、この原本は変わりません。</p><div className="actions"><Select value={section} onValueChange={v=>{setSection(v);setPage(0);setSelected(null)}}><SelectTrigger aria-label="資料の種類"><SelectValue/></SelectTrigger><SelectContent>{Object.keys(data).map(k=><SelectItem key={k} value={k}>{sourceLabels[k]||k} {Array.isArray(data[k])?`(${data[k].length})`:''}</SelectItem>)}</SelectContent></Select><input aria-label="資料を検索" placeholder="ID・本文で検索" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} className="source-search"/></div><div className="source-layout"><div>{filtered.slice(page*30,(page+1)*30).map((v,i)=><button className="source-row" key={i} onClick={()=>{setSelected(v);setDetailOpen(true)}}>{v?.title||v?.name||v?.id||v?.key||`${sourceLabels[section]||section} ${page*30+i+1}`}<small>{v?.id||''}</small></button>)}<div className="actions"><button disabled={page===0} onClick={()=>setPage(page-1)}>前へ</button><span>{filtered.length}件 / {page+1}ページ</span><button disabled={(page+1)*30>=filtered.length} onClick={()=>setPage(page+1)}>次へ</button></div></div><div><LargeTextField label="選択した資料の全項目" value={selected!==null?JSON.stringify(selected,null,2):'資料を選択してください。'}/></div></div><ExpandedTextDialog open={detailOpen} onOpenChange={setDetailOpen} label={selected?.title||selected?.name||selected?.id||sourceLabels[section]||section} value={selected!==null?JSON.stringify(selected,null,2):''}/></section>;
}
