import {coreStateIssues,type ActualChange,type CoreState,type PathEntry,type PlannedChange,type Repository,type RepositoryBaseline,type TypedRelation} from './core-model';

export class RepositoryModelError extends Error{}
const commitPattern=/^[a-f0-9]{40,64}$/i,hashPattern=/^(?:[a-f0-9]{64})?$/i;
const idExists=(core:CoreState,id:string)=>Object.values(core).some(value=>Array.isArray(value)&&value.some((row:any)=>row?.id===id));
const clone=(core:CoreState):CoreState=>structuredClone(core);
const assertId=(id:string,label:string)=>{if(!id.trim())throw new RepositoryModelError(`${label} IDが必要です`);};
export function normalizeRepositoryPath(value:string){const p=value.trim().replaceAll('\\','/').replace(/^\.\//,'').replace(/\/+$/,'').replace(/\/{2,}/g,'/');if(!p||p.startsWith('/')||p.split('/').some(x=>!x||x==='.'||x==='..'))throw new RepositoryModelError('Repository pathは相対pathで、. / .. / 空segmentを含められません');return p;}
function assertCore(core:CoreState){const issues=coreStateIssues(core);if(issues.length)throw new RepositoryModelError(issues.join(' / '));return core;}
function ensureNewId(core:CoreState,id:string,label:string){assertId(id,label);if(idExists(core,id))throw new RepositoryModelError(`${label} IDが重複しています: ${id}`);}
function repository(core:CoreState,id:string){const row=core.repositories.find(x=>x.id===id);if(!row)throw new RepositoryModelError(`Repositoryが見つかりません: ${id}`);return row;}
function baseline(core:CoreState,id:string){const row=core.repositoryBaselines.find(x=>x.id===id);if(!row)throw new RepositoryModelError(`Baselineが見つかりません: ${id}`);return row;}
function pathEntry(core:CoreState,id:string){const row=core.pathEntries.find(x=>x.id===id);if(!row)throw new RepositoryModelError(`PathEntryが見つかりません: ${id}`);return row;}

export function addRepository(core:CoreState,row:Repository){const next=clone(core);ensureNewId(next,row.id,'Repository');if(!row.provider.trim()||!row.owner.trim()||!row.name.trim()||!row.defaultBranch.trim())throw new RepositoryModelError('Repository情報が不足しています');next.repositories.push({...row});return assertCore(next);}
export function addRepositoryBaseline(core:CoreState,row:RepositoryBaseline){const next=clone(core);ensureNewId(next,row.id,'Baseline');repository(next,row.repositoryId);if(!commitPattern.test(row.commitSha))throw new RepositoryModelError('Baseline commit SHAが不正です');next.repositoryBaselines.push({...row,commitSha:row.commitSha.toLowerCase()});return assertCore(next);}
export function addPathEntry(core:CoreState,row:PathEntry){const next=clone(core);ensureNewId(next,row.id,'PathEntry');const repo=repository(next,row.repositoryId),base=baseline(next,row.baselineId);if(base.repositoryId!==repo.id)throw new RepositoryModelError('PathEntryのRepositoryとBaselineが一致しません');const path=normalizeRepositoryPath(row.path);if(row.baselineHash&&!hashPattern.test(row.baselineHash))throw new RepositoryModelError('baselineHashはSHA-256で登録してください');if(row.parentId){const parent=pathEntry(next,row.parentId);if(parent.repositoryId!==row.repositoryId||parent.baselineId!==row.baselineId)throw new RepositoryModelError('親PathEntryは同じRepository/Baselineでなければなりません');if(parent.entryType!=='directory')throw new RepositoryModelError('fileを親PathEntryにできません');if(!path.startsWith(parent.path+'/'))throw new RepositoryModelError('子Pathは親Path配下にしてください');}if(next.pathEntries.some(x=>x.repositoryId===row.repositoryId&&x.baselineId===row.baselineId&&x.path===path))throw new RepositoryModelError(`同じPathが既にあります: ${path}`);next.pathEntries.push({...row,path});return assertCore(next);}

function isDescendant(core:CoreState,ancestorId:string,candidateId:string){let id=candidateId;const seen=new Set<string>();while(id&&!seen.has(id)){if(id===ancestorId)return true;seen.add(id);id=core.pathEntries.find(x=>x.id===id)?.parentId||'';}return false;}
export function movePathEntry(core:CoreState,input:{pathEntryId:string;newParentId:string;newPath:string}){const next=clone(core),row=pathEntry(next,input.pathEntryId),oldPath=row.path,newPath=normalizeRepositoryPath(input.newPath);if(input.newParentId===row.id)throw new RepositoryModelError('PathEntryは自分自身の配下へ移動できません');if(input.newParentId){if(isDescendant(next,row.id,input.newParentId))throw new RepositoryModelError('PathEntryを自分の子孫配下へ移動できません');const parent=pathEntry(next,input.newParentId);if(parent.entryType!=='directory')throw new RepositoryModelError('file配下へ移動できません');if(parent.repositoryId!==row.repositoryId||parent.baselineId!==row.baselineId)throw new RepositoryModelError('移動先は同じRepository/Baseline内に限ります');if(!newPath.startsWith(parent.path+'/'))throw new RepositoryModelError('移動後Pathは移動先親Path配下にしてください');}if(next.pathEntries.some(x=>x.id!==row.id&&x.repositoryId===row.repositoryId&&x.baselineId===row.baselineId&&x.path===newPath))throw new RepositoryModelError(`移動先Pathが既にあります: ${newPath}`);row.parentId=input.newParentId;row.path=newPath;if(row.entryType==='directory'){const prefix=oldPath+'/';for(const child of next.pathEntries){if(child.id!==row.id&&child.repositoryId===row.repositoryId&&child.baselineId===row.baselineId&&child.path.startsWith(prefix))child.path=newPath+'/'+child.path.slice(prefix.length);}}return assertCore(next);}

export function addPlannedChange(core:CoreState,row:PlannedChange){const next=clone(core);ensureNewId(next,row.id,'PlannedChange');const target=pathEntry(next,row.pathEntryId);const before=row.beforePath?normalizeRepositoryPath(row.beforePath):target.path;let after=row.afterPath;if(row.action==='move'||row.action==='add')after=normalizeRepositoryPath(after);if(row.action==='delete'&&after)throw new RepositoryModelError('delete予定にafterPathは指定できません');if(row.action!=='add'&&before!==target.path)throw new RepositoryModelError('PlannedChangeのbeforePathが現在Pathと一致しません');next.plannedChanges.push({...row,beforePath:before,afterPath:after});return assertCore(next);}
export function addActualChange(core:CoreState,row:ActualChange){const next=clone(core);ensureNewId(next,row.id,'ActualChange');if(!next.plannedChanges.some(x=>x.id===row.plannedChangeId))throw new RepositoryModelError('対応するPlannedChangeが見つかりません');if(!commitPattern.test(row.commitSha))throw new RepositoryModelError('ActualChange commit SHAが不正です');if(row.beforeHash&&!hashPattern.test(row.beforeHash)||row.afterHash&&!hashPattern.test(row.afterHash))throw new RepositoryModelError('ActualChange hashはSHA-256で登録してください');next.actualChanges.push({...row,commitSha:row.commitSha.toLowerCase()});return assertCore(next);}
export function linkEvidenceVersionToPath(core:CoreState,input:{relationId:string;evidenceVersionId:string;pathEntryId:string}){const next=clone(core);if(next.relations.some(x=>x.type==='documents_path'&&x.fromType==='evidenceVersion'&&x.fromId===input.evidenceVersionId&&x.toType==='pathEntry'&&x.toId===input.pathEntryId))return assertCore(next);ensureNewId(next,input.relationId,'Relation');if(!next.evidenceVersions.some(x=>x.id===input.evidenceVersionId))throw new RepositoryModelError('EvidenceVersionが見つかりません');pathEntry(next,input.pathEntryId);const relation:TypedRelation={id:input.relationId,type:'documents_path',fromType:'evidenceVersion',fromId:input.evidenceVersionId,toType:'pathEntry',toId:input.pathEntryId};next.relations.push(relation);return assertCore(next);}
