'use client';
import {useEffect,useState,useRef,useMemo} from 'react';
import ProposalInbox from './proposal-inbox';
import TaskPanel from './task-panel';
import {TaskFields,SourceBaselines} from './task-fields';
import {buildHandoff,type HandoffMode} from './handoff';
import {invalidateApprovals,reopenForActiveWork,type ApprovalRequests,type ApprovalKind} from './approvals';
import {historyPolicy} from './history-policy';
import {pendingLabels,itemSorts,visibleItems} from './item-list';
import FileOutput,{type OutputFile} from './file-output';
import {makeBackup} from './backup';
import {Trash2,LogOut,Plus,ArrowUpRight,Download,Upload,Save,History,GitBranch,ArrowLeft,FileText,CheckCircle2,MessagesSquare,Clipboard,Cloud} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Toaster,toast} from 'sonner';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import LargeTextField from './large-text';
import StatusAuditView from './status-audit-view';
import BulkWorkDialog from './bulk-work-dialog';
import {taskTransitionIssues,dependencyIssues} from './task-dependencies';
import {prepareImport,ImportResult} from './import-project';
import ImportedSource,{sourceLabels} from './imported-source';
import {Project,Item,RecordData,newProject,stages,kinds,projectSchema,proposalSchema,statusByKind,itemSchema} from './model';
import {emptyCoreState} from './core-model';
import EvidencePanel from './evidence-panel';
import RepositoryPanel from './repository-panel';
const statuses=statusByKind;
function Choice({value,options,onChange,label}:{value:string;options:readonly string[];onChange:(v:string)=>void;label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{!options.includes(value)&&<SelectItem value={value} disabled>{value}（旧状態・選び直してください）</SelectItem>}{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select>}
function Field({label,value,onChange,small=false}:{label:string;value:string;onChange:(v:string)=>void;small?:boolean}){return small?<label className="field"><span>{label}</span><input value={value} onChange={e=>onChange(e.target.value)}/></label>:<LargeTextField label={label} value={value} onChange={onChange}/>}


export default function Workspace({signInUrl,signOutUrl,accountLabel}:{signInUrl:string;signOutUrl:string;accountLabel:string}){
 const [output,setOutput]=useState<OutputFile|null>(null),[itemBaseline,setItemBaseline]=useState('');
 const [leaveAction,setLeaveAction]=useState<(()=>void)|null>(null);
 const allowUnload=useRef(false);
 function download(name:string,text:string,type='application/json'){setOutput({name,text,type,notice:'端末への保存は完了していません。共有・コピーから退避し、保存先で確認してください。'});}
 const [itemViews,setItemViews]=useState<Record<string,{filter:string;sort:string}>>({});
 const [handoffMode,setHandoffMode]=useState<HandoffMode>('簡潔版');
 const [approvalRequests,setApprovalRequests]=useState<ApprovalRequests>({});
 const [historyLoading,setHistoryLoading]=useState(false),[historyMore,setHistoryMore]=useState(false),[snapshotText,setSnapshotText]=useState('');
 const [deleteOpen,setDeleteOpen]=useState(false);
 const dialogTitle=useRef<HTMLHeadingElement>(null);
 const [records,setRecords]=useState<RecordData[]>([]),[active,setActive]=useState<RecordData|null>(null),[saved,setSaved]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('概要'),[modal,setModal]=useState(''),[name,setName]=useState(''),[item,setItem]=useState<Item|null>(null),[raw,setRaw]=useState(''),[proposal,setProposal]=useState<ReturnType<typeof proposalSchema.parse>|null>(null),[history,setHistory]=useState<any[]>([]);
 const [authRequired,setAuthRequired]=useState(false),[pendingImport,setPendingImport]=useState<ImportResult|null>(null),[bulkDirty,setBulkDirty]=useState(false);
 async function request(url:string,options:RequestInit={}){const r=await fetch(url,{...options,credentials:'same-origin',signal:AbortSignal.timeout(30000)});if(r.status===401){setAuthRequired(true);throw Error('サインインが必要です。下のボタンから続けてください。');}if(!r.headers.get('content-type')?.includes('application/json'))throw Error('応答を確認できません。サイトを開き直してください。');const data:any=await r.json();if(!r.ok)throw Error(data.error||'処理できませんでした');setAuthRequired(false);return data;}
 const p=active?.project,dirty=!!p&&(JSON.stringify(p)!==saved||Object.keys(approvalRequests).length>0);
 const modalDirty=modal==='item'?!!item&&JSON.stringify(item)!==itemBaseline:modal==='proposal'?!!raw.trim():modal==='create'?!!name.trim():modal==='import'?!!pendingImport:modal==='bulk'?bulkDirty:false;
 function guard(action:()=>void,onlyModal=false){if(busy)return;if(onlyModal?modalDirty:dirty||modalDirty)setLeaveAction(()=>action);else action();}
 function closeModal(){setModal('');setItem(null);setRaw('');setName('');setPendingImport(null);setBulkDirty(false);}
 function navigate(url:string){guard(()=>{allowUnload.current=true;window.location.assign(url)});}
 async function saveAndLeave(){
  if(!active)return;
  let record=active;
  if(modal==='item'&&item){const parsed=itemSchema.safeParse({...item,title:item.title.trim()});if(!parsed.success){toast.error(parsed.error.issues[0].message);return;}record={...active,project:reopenForActiveWork(invalidateApprovals({...active.project,items:[...active.project.items.filter(i=>i.id!==item.id),parsed.data]}))};}
  if(await persist(record)){const action=leaveAction;setLeaveAction(null);closeModal();action?.();}
 }
 async function load(){setLoading(true);setError('');try{const data=await request('/api/projects');setRecords(data);}catch(e:any){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(!allowUnload.current&&(dirty||modalDirty)){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[dirty,modalDirty]);
 function open(r:RecordData){setItemViews({});setApprovalRequests({});setHandoffMode('簡潔版');setActive(structuredClone(r));setSaved(JSON.stringify(r.project));setTab('概要');setError('');}
 function change(patch:Partial<Project>){if(active){setApprovalRequests({});setActive({...active,project:reopenForActiveWork(invalidateApprovals({...active.project,...patch}))});}}
 function approve(kind:ApprovalKind,value:boolean){if(!active)return;setApprovalRequests(prev=>({...prev,[kind]:value}));setActive({...active,project:{...active.project,[kind==='implementation'?'implementationApproved':'completionApproved']:value}});}
 async function persist(record=active,summary='案件を更新',originalText?:string){if(!record||busy)return false;setBusy(true);setError('');try{const data=await request('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project:record.project,baseRevision:record.revision,summary,originalText,approvals:record===active?approvalRequests:{}})});setApprovalRequests({});setActive(data);setSaved(JSON.stringify(data.project));setRecords(prev=>[data,...prev.filter(x=>x.project.id!==data.project.id)]);toast.success('サーバーに保存しました');return true;}catch(e:any){setError(e.message);return false;}finally{setBusy(false);}}
 async function create(){const n=name.trim();if(!n)return;const ok=await persist({project:newProject(n),revision:0,updatedAt:''},'案件を作成');if(ok){setModal('');setName('');setTab('概要');}}
 function editItem(kind:Item['kind'],existing?:Item){const draft=existing?structuredClone(existing):{id:crypto.randomUUID(),kind,title:'',body:'',status:statuses[kind][0] as Item['status'],parentId:'',reason:''};setItem(draft);setItemBaseline(JSON.stringify(draft));setModal('item');}
 function acceptItem(){if(!item||!p)return;const parsed=itemSchema.safeParse({...item,title:item.title.trim()});if(!parsed.success){toast.error(parsed.error.issues[0].message);return;}const items=[...p.items.filter(i=>i.id!==item.id),parsed.data];const issues=taskTransitionIssues(saved?JSON.parse(saved):p,{items});if(issues.length){toast.error(issues.join(' / '));return;}change({items});setModal('');}
 function acceptBulk(items:Item[]){if(!p||!items.length)return;change({items:[...p.items,...items]});setBulkDirty(false);setModal('');toast.success(`${items.length}件を編集内容へ反映しました`);}
 const manualProposalId=useRef('');
 function acceptServerRecord(data:RecordData){setApprovalRequests({});setActive(data);setSaved(JSON.stringify(data.project));setRecords(prev=>[data,...prev.filter(x=>x.project.id!==data.project.id)]);}
 function parseProposal(){try{const v=proposalSchema.parse(JSON.parse(raw));if(v.projectId!==p?.id||v.baseRevision!==active?.revision)throw Error('案件または基準版が一致しません。最新の引き継ぎをAIに渡してください。');if(new Set(v.upserts.map(i=>i.id)).size!==v.upserts.length)throw Error('返却の項目IDが重複しています');manualProposalId.current=crypto.randomUUID();setProposal(v);}catch(e:any){toast.error(e.issues?.[0]?.message||e.message);}}
 async function applyProposal(){if(!proposal||!active||busy)return;setBusy(true);try{await request('/api/proposals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:manualProposalId.current,proposal})});const data=await request('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({proposalId:manualProposalId.current})});acceptServerRecord(data);setModal('');setProposal(null);setRaw('');toast.success('変更案を反映して保存しました');}catch(e:any){toast.error(e.issues?.[0]?.message||e.message);}finally{setBusy(false)}}
 async function importFile(file?:File){if(!file)return;try{if(file.size>8*1024*1024)throw Error('ファイルは8MB以内にしてください');const text=await file.text();setPendingImport(prepareImport(JSON.parse(text),text));setError('');setModal('import');}catch(e:any){toast.error('取り込めません: '+(e.issues?.[0]?.message||e.message));}}
 async function confirmImport(){if(!pendingImport)return;const ok=await persist({project:pendingImport.project,revision:0,updatedAt:''},'JSONから新規取込',pendingImport.originalText);if(ok){const restored=pendingImport;setPendingImport(null);setModal('');setTab('概要');if(restored.draftItem){setItem(restored.draftItem);setItemBaseline('');setModal('item');}if(restored.proposalText){setRaw(restored.proposalText);if(!restored.draftItem)setModal('proposal');toast.info('退避したAI返却は元案件・元版向けです。内容を確認してください。');}}}
 function backup(){
  if(modal==='import'&&pendingImport){download('import-backup.json',JSON.stringify(makeBackup({project:pendingImport.project,revision:0,updatedAt:''},pendingImport.originalText),null,2));return;}
  if(!active){download('input-draft.json',JSON.stringify({name,proposalText:raw},null,2));return;}
  const draftState={...(modal==='item'&&item?{item}:{}),...(raw?{proposalText:raw}:{})};
  const data=makeBackup(active,undefined,active.project.sourceInfo?'元JSONは含まれていません。':undefined,draftState);
  setOutput({name:active.project.id+'-project-only.json',text:JSON.stringify(data,null,2),notice:'案件本体の退避です。未反映の項目入力も保持し、再取込時に編集画面へ戻せます。元JSONは含みません。',...(!dirty&&!modalDirty?{url:'/api/projects/export?id='+active.project.id+'&revision='+active.revision}:{} )});
 }
 async function completeBackup(){
  if(!active)return;
  const record=structuredClone(active);
  try{const r=await fetch('/api/projects?original='+record.project.id,{credentials:'same-origin',signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('元JSONを取得できません');const originalText=await r.text();setOutput({name:record.project.id+'-complete.json',text:JSON.stringify(makeBackup(record,originalText),null,2),notice:'案件本体と元JSONを含みます。保存先でファイルを確認してください。',...(!dirty&&!modalDirty?{url:'/api/projects/export?id='+record.project.id+'&revision='+record.revision+'&original=1'}:{})});}
  catch{backup();toast.error('元JSONを取得できませんでした。案件本体のみの退避を表示しています。');}
 }
 async function downloadOriginal(){if(!active)return;const url='/api/projects/export?id='+active.project.id+'&kind=original';try{const r=await fetch(url,{credentials:'same-origin',signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('元JSONを取得できません');setOutput({name:'original.json',text:await r.text(),url});}catch(e:any){toast.error(e.message);}}
 async function deleteProject(){if(!active||busy)return;setBusy(true);setError('');try{const result=await request('/api/projects',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:active.project.id,baseRevision:active.revision})});setRecords(prev=>prev.filter(r=>r.project.id!==active.project.id));setActive(null);setSaved('');setDeleteOpen(false);toast.success(result.cleanupPending?'案件を削除しました。元ファイルの削除は再読み込み時に再試行します。':'案件・更新履歴・元ファイルを削除しました');}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function showHistory(older=false){if(!p||historyLoading)return;setModal('history');setSnapshotText('');setHistoryLoading(true);if(!older)setHistory([]);try{const last=older?history.at(-1)?.revision:null;const data=await request('/api/projects?history='+p.id+(last?'&before='+last:''));setHistory(prev=>older?[...prev,...data]:data);setHistoryMore(data.length===historyPolicy.listLimit);}catch(e:any){toast.error(e.message);}finally{setHistoryLoading(false);}}
 async function viewSnapshot(revision:number){if(!p)return;setHistoryLoading(true);try{const data=await request('/api/projects?snapshot='+p.id+'&revision='+revision);setSnapshotText(JSON.stringify(data,null,2));}catch(e:any){toast.error(e.message)}finally{setHistoryLoading(false)}}
 const shown=(kind:string)=>visibleItems(p?.items||[],kind as Item['kind'],itemViews[kind]?.filter,itemViews[kind]?.sort);
 function setView(kind:string,patch:{filter?:string;sort?:string}){setItemViews(prev=>({...prev,[kind]:{...(prev[kind]||{filter:'すべて',sort:'元の順序'}),...patch}}));}
 const count=(kind:string)=>p?.items.filter(i=>i.kind===kind).length||0;
 const transfer=useMemo(()=>active&&tab==='AI引き継ぎ'?buildHandoff(active,handoffMode):'',[active,tab,handoffMode]);
 return <div className={p?"app":"app project-index"}><Toaster richColors position="bottom-right"/><header className="top"><a href="/" className="brand" onClick={e=>{e.preventDefault();navigate('/')}}><span className="brand-icon"><GitBranch size={23}/></span>継ぐ<span className="brand-en">TSUGU / WORKSPACE</span></a><div className="account-menu"><span className="cloud"><Cloud size={16}/> サーバー保存</span><span className="account-label" title={accountLabel}>{accountLabel}</span><a className="button" href={signOutUrl} target="_top" onClick={e=>{e.preventDefault();navigate(signOutUrl)}}><LogOut size={16}/>ログアウト</a></div></header>
 <main className="main">{!p?<><div className="index-toolbar"><h1>案件 <span className="index-count">{loading?'…':records.length}</span></h1><div className="actions"><a className="button" href="/tsugu-ai-manual-v9.md" download="tsugu-ai-manual-v9.md"><Download size={16}/>AI説明書</a><label className="button"><Upload size={16}/>JSON取込<input hidden type="file" accept=".json" disabled={busy||loading||authRequired} onChange={e=>{importFile(e.target.files?.[0]);e.target.value=''}}/></label><button className="primary" onClick={()=>{setName('');setModal('create')}} disabled={busy||loading||!!error}><Plus size={16}/>新規案件</button></div></div>
 {loading?<p role="status">案件を読み込んでいます…</p>:records.length?<ul className="project-list" aria-label="案件一覧">{records.map(r=><li key={r.project.id}><button className="project-list-row" onClick={()=>open(r)}><span className="project-list-name">{r.project.name}</span><span className="badge">{r.project.stage}</span><span className="project-list-meta">版 {r.revision} · {new Date(r.updatedAt).toLocaleDateString('ja-JP')}</span></button></li>)}</ul>:!error?<Empty className="index-empty"><EmptyHeader><EmptyTitle>案件はありません</EmptyTitle><EmptyDescription>新規案件を作成するか、JSONを取り込んでください。</EmptyDescription></EmptyHeader><button className="primary" onClick={()=>setModal('create')}><Plus size={17}/>案件を作成</button></Empty>:null}</>:<>
 <div className="breadcrumb"><button disabled={busy} onClick={()=>guard(()=>{setActive(null);setError('')})}><ArrowLeft size={16}/>案件一覧</button><span>/</span><span>{p.name}</span></div>
 <div className="page-head compact"><div><p className="eyebrow">PROJECT WORKSPACE</p><h1>{p.name}</h1><div className="project-meta"><span className="badge">{p.stage}</span><span>版 {active!.revision}</span><span>{dirty?'未保存の変更があります':`保存済み · ${new Date(active!.updatedAt).toLocaleString('ja-JP')}`}</span></div></div><div className="actions"><button className="danger-outline" disabled={busy} onClick={()=>{setError('');setDeleteOpen(true)}}><Trash2 size={16}/>案件を削除</button><button onClick={()=>showHistory()}><History size={16}/>履歴</button><button className="primary" disabled={busy||!dirty} onClick={()=>persist()}><Save size={16}/>{busy?'保存中…':'変更を保存'}</button></div></div>
 {tab==='AI引き継ぎ'&&<ProposalInbox key={p.id} record={active!} disabled={busy||dirty||modalDirty} onApplied={acceptServerRecord} onBusy={setBusy}/>}
 <fieldset disabled={busy} className="workspace-fieldset"><Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="workspace-tabs">{['概要','エビデンス','開発ディレクトリ','構成・作業','議論・決定','進行・検証','AI引き継ぎ',...(p.sourceInfo?['取込資料']:[])].map(t=><TabsTrigger key={t} value={t}>{t}</TabsTrigger>)}</TabsList>
 <TabsContent value="概要"><SourceBaselines value={p.sourceRefs} onChange={sourceRefs=>change({sourceRefs})}/>{p.sourceInfo&&<section className="panel import-summary"><h2>旧案件からの取込</h2><p>{p.sourceInfo.projectId} · 形式 {p.sourceInfo.schemaVersion}</p><p className="muted">構成・作業・議論・決定・検証を編集できます。{p.sourceInfo.originalMissing?'元JSONなしで復元しているため、取込資料は利用できません。':'仕様・システム情報・過去の履歴を含む全情報は「取込資料」に保持しています。'}</p><button onClick={downloadOriginal} disabled={p.sourceInfo.originalMissing}><Download size={16}/>元JSONを保存</button>{p.sourceInfo.warnings.length>0&&<details><summary>変換時のお知らせ {p.sourceInfo.warnings.length}件</summary>{p.sourceInfo.warnings.map((w,i)=><p className="muted" key={i}>{w}</p>)}</details>}</section>}<div className="overview"><section className="panel"><div className="panel-heading"><FileText size={18}/><h2>プロジェクトの軸</h2></div><Field small label="案件名" value={p.name} onChange={name=>change({name})}/><Field label="目的 / 何を実現するか" value={p.purpose} onChange={purpose=>change({purpose})}/><Field label="守る方針 / 変えてはいけないこと" value={p.rules} onChange={rules=>change({rules})}/><Field label="ソース基準 / リポジトリ・コミット・対象ファイル" value={p.baseline} onChange={baseline=>change({baseline})}/></section><div><section className="panel focus-panel"><p className="eyebrow">CURRENT FOCUS</p><h2>いま、取り組むこと</h2><Field label="現在の焦点" value={p.focus} onChange={focus=>change({focus})}/><Field label="次回の最初の一歩" value={p.next} onChange={next=>change({next})}/></section><section className="panel summary-panel"><h2>文脈のつながり</h2>{kinds.map(k=><div key={k}><span>{k}</span><strong>{count(k)}</strong></div>)}</section></div></div></TabsContent>
 <TabsContent value="エビデンス"><EvidencePanel projectId={p.id} core={p.core??emptyCoreState()} disabled={busy} onChange={core=>change({core})}/></TabsContent>
 <TabsContent value="開発ディレクトリ"><RepositoryPanel core={p.core??emptyCoreState()} disabled={busy} onChange={core=>change({core})}/></TabsContent>
 {(['構成・作業','議論・決定','進行・検証'] as const).map(t=><TabsContent key={t} value={t}>{t==='進行・検証'&&<section className="panel"><div className="panel-heading"><GitBranch size={18}/><h2>開発の進行</h2></div><div className="stage-track">{stages.map((s,i)=><div className={p.stage===s?'current':''} key={s}><span>0{i+1}</span>{s}</div>)}</div><div className="gate-controls"><Choice label="工程" value={p.stage} options={stages} onChange={stage=>change({stage:stage as Project['stage']})}/><label><Checkbox checked={p.implementationApproved} onCheckedChange={v=>approve('implementation',v===true)}/>実装を承認</label><label><Checkbox checked={p.completionApproved} onCheckedChange={v=>approve('completion',v===true)}/>完了を承認</label></div><p className="muted">保存する版ごとに承認が必要です。内容・工程を編集した後でチェックし、保存してください。承認なしでも現在の工程のまま編集内容を保存できますが、工程を先へ進めるには再承認が必要です。</p>{(['implementation','completion'] as const).map(kind=>{const stamp=kind==='implementation'?p.implementationApproval:p.completionApproval;const valid=kind==='implementation'?p.implementationApproved:p.completionApproved;return <p className="muted" key={kind}>{kind==='implementation'?'実装':'完了'}: {approvalRequests[kind]?'この内容を保存時に承認':valid?'現在版を承認済み':'未承認・再承認が必要'}{stamp&&` / 前回承認: 版 ${stamp.approvedRevision} · ${new Date(stamp.approvedAt).toLocaleString('ja-JP')}`}</p>})}</section>}
 {(t==='構成・作業'?['構成','作業']:t==='議論・決定'?['議論','決定']:['検証']).map(k=><section className="panel" key={k}><div className="section-title"><h2>{k} <span className="count">{count(k)}</span></h2><div className="actions">{k==='作業'&&<button onClick={()=>{setBulkDirty(false);setModal('bulk')}}><Plus size={16}/>一括追加</button>}<button onClick={()=>editItem(k as Item['kind'])}><Plus size={16}/>追加</button></div></div><div className="actions" style={{marginBottom:'1rem',alignItems:'end'}}><div className="field"><span>状態で絞り込み</span><Choice label={`${k}の状態フィルター`} value={itemViews[k]?.filter||'すべて'} options={['すべて',pendingLabels[k as Item['kind']],...statuses[k as Item['kind']]]} onChange={filter=>setView(k,{filter})}/></div><div className="field"><span>並べ替え</span><Choice label={`${k}の並べ替え`} value={itemViews[k]?.sort||'元の順序'} options={itemSorts} onChange={sort=>setView(k,{sort})}/></div><span className="muted" role="status">{shown(k).length} / {count(k)}件表示</span>{(itemViews[k]?.filter&&itemViews[k].filter!=='すべて'||itemViews[k]?.sort&&itemViews[k].sort!=='元の順序')&&<button onClick={()=>setView(k,{filter:'すべて',sort:'元の順序'})}>表示をリセット</button>}</div>{!count(k)?<p className="empty-row">{k==='構成'?'機能や領域を登録し、作業の関連先にできます。':k==='議論'?'問いと検討内容を残しましょう。':k==='決定'?'決めたことと、その理由を記録しましょう。':k==='検証'?'期待する結果と確認の根拠を残しましょう。':'実施する作業と完了条件を記録しましょう。'}</p>:!shown(k).length?<p className="empty-row">この条件に該当する項目はありません。</p>:shown(k).map(i=><button className="item-row" key={i.id} onClick={()=>editItem(i.kind,i)}><div><span className="badge">{i.status}</span><strong>{i.title}</strong><p>{i.body||'詳細を記入'}</p>{i.parentId&&<small>関連: {p.items.find(x=>x.id===i.parentId)?.title}</small>}</div><ArrowUpRight size={18}/></button>)}</section>)}</TabsContent>)}
 <TabsContent value="AI引き継ぎ"><TaskPanel key={p.id+':'+active!.revision} record={active!} disabled={busy||dirty||modalDirty} onBusy={setBusy} onOutput={text=>setOutput({name:'task-pack.md',text,type:'text/markdown',notice:'保存済みの作業と選択した元資料です。実行前の確認事項を先に読んでください。'})} onProposal={text=>{setRaw(text);setProposal(null);setModal('proposal')}}/><section className="panel"><div className="panel-heading"><FileText size={19}/><h2>AI用取扱説明書</h2></div><p className="muted">新規案件の登録方法とAI返却JSONの作り方・提出手順をまとめています。最新の引き継ぎと一緒にAIへ渡してください。</p><a className="button" href="/tsugu-ai-manual-v9.md" download="tsugu-ai-manual-v9.md"><Download size={16}/>AI用取扱説明書をダウンロード（Markdown）</a></section><div className="overview"><section className="panel"><div className="panel-heading"><MessagesSquare size={19}/><h2>次の会話へ渡す</h2></div><p className="muted">変更を保存し、引き継ぎをコピーしてChatGPTに渡してください。会話への自動接続はありません。</p><div className="field"><span>引き継ぎの範囲</span><Choice label="引き継ぎの範囲" value={handoffMode} options={['簡潔版','完全版']} onChange={v=>setHandoffMode(v as HandoffMode)}/></div><p className="muted">{handoffMode==='簡潔版'?'重要項目を抜粋しています。省略部分は必要に応じて確認してください。':'編集項目の本文を含みます。元JSONの全仕様は含みません。実装には作業パックを使ってください。'} {transfer.length.toLocaleString()}文字</p><div className="actions"><button disabled={dirty} onClick={async()=>{try{await navigator.clipboard.writeText(transfer);toast.success('引き継ぎをコピーしました')}catch{toast.error('コピーできません。下の文章を選択するか、ファイルを保存してください。')}}}><Clipboard size={16}/>コピー</button><button disabled={dirty} onClick={()=>setOutput({name:'handoff.md',text:transfer,type:'text/markdown',url:'/api/projects/export?id='+p.id+'&revision='+active!.revision+'&kind=handoff&mode='+(handoffMode==='完全版'?'full':'summary')})}><Download size={16}/>引き継ぎ保存</button></div><textarea className="handoff" readOnly value={transfer} aria-label="AIへの引き継ぎ"/></section><div><section className="panel focus-panel"><p className="eyebrow">RETURN & REVIEW</p><h2>AIの返却を取り込む</h2><p>更新案を確認してから案件に反映します。承認と工程は人が管理します。</p><button className="primary" disabled={dirty} onClick={()=>{setRaw('');setProposal(null);setModal('proposal')}}><Upload size={16}/>返却JSONを確認</button></section><section className="panel"><h2>JSONバックアップ</h2><p className="muted">案件本体と、元JSON付きのバックアップを選べます。取り込むと新しい案件として復元します。</p><button onClick={backup}><Download size={16}/>{dirty?'未保存の下書きを退避':'案件本体JSONを取得'}</button>{p.sourceInfo&&!p.sourceInfo.originalMissing&&<button onClick={completeBackup} disabled={dirty||modalDirty}>元JSON付きバックアップを取得</button>}</section></div></div></TabsContent>
 {p.sourceInfo&&<TabsContent value="取込資料">{p.sourceInfo.originalMissing?<p role="status">元JSONなしで復元した案件です。取込資料は利用できません。</p>:<><StatusAuditView key={p.id} project={p} onEdit={id=>{const target=p.items.find(i=>i.id===id);if(target)editItem(target.kind,target)}}/><ImportedSource projectId={p.id}/></>}</TabsContent>}
 </Tabs></fieldset></>}
 {error&&<div className="error" role="alert"><strong>{error}</strong>{authRequired&&<p><a className="button primary" href={signInUrl} target="_top" onClick={e=>{e.preventDefault();navigate(signInUrl)}}>ChatGPTでサインイン</a></p>}<div className="actions">{active&&<button onClick={backup}>下書きJSONを保存</button>}<button onClick={()=>guard(()=>{closeModal();setActive(null);load()})}>再読み込み</button></div></div>}
 </main><footer className="site-footer"><span>継ぐ / TSUGU · <a href="/storage" target="_blank" rel="noreferrer">保存データと利用について</a></span><span>目的 → 判断 → 実装 → 検証 → 引き継ぎ</span></footer>
 <AlertDialog open={deleteOpen} onOpenChange={v=>{if(!busy)setDeleteOpen(v)}}><AlertDialogContent><AlertDialogTitle>この案件を削除しますか？</AlertDialogTitle><AlertDialogDescription>「{p?.name}」の案件内容・更新履歴・取り込んだ元JSONを削除します。元に戻すには、事前に保存したJSONバックアップが必要です。{dirty?'未保存の変更も破棄されます。':''}</AlertDialogDescription><button disabled={busy} onClick={backup}><Download size={16}/>先にJSONバックアップを保存</button>{error&&<p className="error" role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>キャンセル</AlertDialogCancel><AlertDialogAction className="danger-button" disabled={busy} onClick={e=>{e.preventDefault();deleteProject()}}>{busy?'削除中…':'案件を削除する'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy)guard(closeModal,true)}}><DialogContent className={modal==='item'||modal==='bulk'?'item-detail-dialog':modal==='proposal'?'wide-dialog':''} onOpenAutoFocus={e=>{e.preventDefault();dialogTitle.current?.focus()}}><DialogTitle ref={dialogTitle} tabIndex={-1}>{({create:'新しい案件',item:`${item?.kind||''}の内容`,bulk:'タスク一括追加',proposal:'AI返却の確認',history:'更新履歴',import:'JSONの取込内容',reload:'最新版を読み直す'})[modal]||'編集'}</DialogTitle><DialogDescription>{modal==='history'?`新しい履歴ファイルは直近${historyPolicy.retainedSnapshots}版を保持します。旧形式の履歴は削除せず参照できます。JSONは保存時点の案件本文です（取込元JSONは含みません）。`:modal==='proposal'?'同じ案件・同じ版の返却だけを受け付けます。':modal==='reload'?'未保存の入力は失われます。必要なら先に下書きJSONを保存してください。':modal==='item'?'本文をタップすると全文を大きく表示できます。':modal==='bulk'?'複数の作業をまとめて検証し、未保存の編集内容へ反映します。':'内容を入力してください。'}</DialogDescription>
 {modal==='import'&&pendingImport&&<div className="dialog-body"><h2>{pendingImport.project.name}</h2><p>新しい案件としてサーバーに保存します。</p>{kinds.map(k=><p key={k}>{k}: {pendingImport.project.items.filter(i=>i.kind===k).length}件</p>)}{pendingImport.project.sourceInfo&&<><p className="muted">{pendingImport.project.sourceInfo.originalMissing?'案件本体のみを復元します。元JSON・取込資料は含まれません。':'作業には作業箱とタスクが含まれます。元JSONもそのまま保存します。'}</p><details><summary>元JSONの内訳</summary>{Object.entries(pendingImport.project.sourceInfo.counts).map(([k,n])=><p key={k}>{sourceLabels[k]||k}: {n}件</p>)}</details><p>変換時のお知らせ: {pendingImport.project.sourceInfo.warnings.length}件</p></>}<button className="primary" disabled={busy||authRequired} onClick={confirmImport}>{busy?'取り込んでいます…':'この内容で取り込む'}</button></div>}
 {modal==='create'&&<><Field small label="案件名" value={name} onChange={setName}/><button className="primary" disabled={busy||!name.trim()} onClick={create}>作成して始める</button></>}
 {modal==='item'&&item?.task&&p&&dependencyIssues([...p.items.filter(i=>i.id!==item.id),item],item).length>0&&<p role="status">依存条件を確認してください: {dependencyIssues([...p.items.filter(i=>i.id!==item.id),item],item).join(' / ')}。保留・中止への変更は可能です。</p>}
 {modal==='item'&&item&&<div className="dialog-body"><Field small label="タイトル" value={item.title} onChange={title=>setItem({...item,title})}/><Field label={item.kind==='作業'?'作業内容・完了条件':'内容'} value={item.body} onChange={body=>setItem({...item,body})}/><Field label={item.kind==='検証'?'結果・証拠 / 免除の理由':'理由・根拠'} value={item.reason} onChange={reason=>setItem({...item,reason})}/><div className="field"><span>状態</span><Choice label="状態" value={item.status} options={statuses[item.kind]} onChange={status=>setItem({...item,status:status as Item['status']})}/></div><div className="field"><span>関連する項目</span><Select value={item.parentId||'none'} onValueChange={v=>setItem({...item,parentId:v==='none'?'':v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">なし</SelectItem>{p?.items.filter(i=>i.id!==item.id).map(i=><SelectItem key={i.id} value={i.id}>{i.kind}: {i.title}</SelectItem>)}</SelectContent></Select></div>{item.kind==='作業'&&<TaskFields key={item.id} value={item.task} onChange={task=>setItem({...item,task})}/>}<button className="primary" disabled={!item.title.trim()} onClick={acceptItem}>編集内容を反映</button><p className="muted">反映後、案件の「変更を保存」でサーバーに保存します。</p></div>}
 {modal==='bulk'&&p&&<BulkWorkDialog existing={p.items} onDirty={setBulkDirty} onApply={acceptBulk}/>}
 {modal==='proposal'&&<div className="dialog-body">{!proposal?<><label className="field"><span>返却JSON</span><textarea rows={10} value={raw} onChange={e=>setRaw(e.target.value)} /></label><button onClick={parseProposal}>変更内容を確認</button></>:<><p><strong>変更理由：</strong>{proposal.summary}</p>{Object.entries(proposal.changes).map(([k,v])=><div className="diff" key={k}><strong>{({purpose:'目的',rules:'方針',focus:'焦点',baseline:'ソース基準',sourceRefs:'Git基準版',next:'次の作業'} as any)[k]}</strong><del>{JSON.stringify((p as any)[k]??'未記入',null,2)}</del><ins>{typeof v==='string'?v:JSON.stringify(v,null,2)}</ins></div>)}{proposal.upserts.map(i=><div className="diff" key={i.id}><strong>{p?.items.some(x=>x.id===i.id)?'更新':'追加'}: {i.title}</strong>{p?.items.find(x=>x.id===i.id)&&<pre>{JSON.stringify(p.items.find(x=>x.id===i.id),null,2)}</pre>}<pre>{JSON.stringify(i,null,2)}</pre></div>)}<div className="actions"><button onClick={()=>setProposal(null)}>入力へ戻る</button><button className="primary" disabled={busy} onClick={applyProposal}>反映して保存</button></div></>}</div>}
 {modal==='history'&&<div className="dialog-body">{history.map(h=><div className="history-row" key={h.revision}><span className="badge">版 {h.revision}</span><strong>{h.summary}</strong><small>{new Date(h.created_at).toLocaleString('ja-JP')}</small><button disabled={historyLoading} onClick={()=>viewSnapshot(h.revision)}>保存内容を表示</button><a className="button" href={'/api/projects?snapshot='+p?.id+'&revision='+h.revision} target="_blank" rel="noreferrer">JSONを開く</a></div>)}{historyLoading?<p role="status">履歴を読み込んでいます…</p>:!history.length?<p>履歴はありません。</p>:null}{historyMore&&<button disabled={historyLoading} onClick={()=>showHistory(true)}>以前の履歴を表示</button>}{snapshotText&&<LargeTextField label="保存時点の案件JSON（閲覧用・現在の案件は変更しません）" value={snapshotText}/>}</div>}
 {modal==='reload'&&<button onClick={()=>{setModal('');setActive(null);load()}}>変更を破棄して読み直す</button>}
 {modalDirty&&<button onClick={backup}>この入力を退避</button>}
 {error&&<div role="alert" className="error">{error}{authRequired&&<p><a className="button primary" href={signInUrl} target="_top" onClick={e=>{e.preventDefault();navigate(signInUrl)}}>ChatGPTでサインイン</a></p>}</div>}
 </DialogContent></Dialog><FileOutput file={output} onClose={()=>setOutput(null)}/><AlertDialog open={!!leaveAction} onOpenChange={v=>{if(!v&&!busy)setLeaveAction(null)}}><AlertDialogContent><AlertDialogTitle>未保存の入力があります</AlertDialogTitle><AlertDialogDescription>保存または退避してから移動してください。破棄を選ぶと入力は失われます。</AlertDialogDescription><button onClick={backup}>入力をファイルとして退避</button><AlertDialogFooter><AlertDialogCancel disabled={busy}>入力へ戻る</AlertDialogCancel>{active&&(!modalDirty||modal==='item')&&<button disabled={busy} onClick={saveAndLeave}>保存して続ける</button>}<AlertDialogAction disabled={busy} onClick={()=>{const action=leaveAction;setLeaveAction(null);action?.();}}>破棄して続ける</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>
}
