from pathlib import Path
import base64, gzip, re

src_path = Path('static/app.js.gz.b64')
raw = gzip.decompress(base64.b64decode(src_path.read_bytes())).decode('utf-8')

old_empty = "function emptyCore(){return {architectureNodes:[],workBoxes:[],tasks:[],decisions:[],issues:[],checks:[],approvals:[],evidences:[],evidenceVersions:[],repositories:[],repositoryBaselines:[],pathEntries:[],plannedChanges:[],actualChanges:[],relations:[]}}"
new_empty = "function emptyCore(){return {uiModelVersion:4,architectureNodes:[],workBoxes:[],requirements:[],tasks:[],testDefinitions:[],eventDefinitions:[],taskDependencies:[],decisions:[],issues:[],checks:[],approvals:[],evidences:[],evidenceVersions:[],repositories:[],repositoryBaselines:[],pathEntries:[],plannedChanges:[],actualChanges:[],relations:[]}}"
if old_empty not in raw:
    raise SystemExit('emptyCore anchor missing')
raw = raw.replace(old_empty, new_empty, 1)

inject_anchor = 'function renderItems(p){'
if inject_anchor not in raw:
    raise SystemExit('renderItems anchor missing')

block = r'''
const workspaceTabs=[
  {key:'概要',label:'概要'},
  {key:'構造',label:'構造'},
  {key:'Box',label:'Box'},
  {key:'要求・仕様',label:'要求・仕様'},
  {key:'Task',label:'Task'},
  {key:'テスト',label:'テスト'},
  {key:'依存',label:'依存'},
  {key:'記録',label:'判断・検査'},
  {key:'項目',label:'互換項目',aria:'項目'},
  {key:'AI引き継ぎ',label:'AI引き継ぎ'},
  {key:'高度なJSON',label:'高度なJSON'}
];
const coreArrayKeys=['architectureNodes','workBoxes','requirements','tasks','testDefinitions','eventDefinitions','taskDependencies','decisions','issues','checks','relations'];
const coreTypeLabels={ARCHITECTURE_NODE:'Architecture',WORKBOX:'WorkBox',REQUIREMENT:'要求・仕様',TASK:'Task',TEST:'Test',EVENT:'Event',DECISION:'Decision',ISSUE:'Issue',CHECK:'Check'};
function ensureCoreModel(p){
  if(!p.core||typeof p.core!=='object'||Array.isArray(p.core))p.core=emptyCore();
  if(!Number.isInteger(p.core.uiModelVersion)||p.core.uiModelVersion<4)p.core.uiModelVersion=4;
  for(const k of coreArrayKeys)if(!Array.isArray(p.core[k]))p.core[k]=[];
  if(!Array.isArray(p.items))p.items=[];
  return p.core;
}
function coreId(prefix){return `${prefix}:${crypto.randomUUID()}`}
function coreRawDraft(key,fallback=''){state.coreDrafts=state.coreDrafts||{};return Object.prototype.hasOwnProperty.call(state.coreDrafts,key)?state.coreDrafts[key]:fallback}
function coreDraft(key,fallback=''){return esc(coreRawDraft(key,fallback))}
function coreNodeParent(x){return x?.parentNodeId??x?.parentId??null}
function coreBoxNode(x){return x?.architectureNodeId??x?.nodeId??null}
function coreBoxParent(x){return x?.parentWorkBoxId??x?.parentBoxId??null}
function coreTaskSubject(x){if(x?.subjectType&&x?.subjectId)return {type:String(x.subjectType).toUpperCase(),id:String(x.subjectId)};if(x?.subject?.type&&x?.subject?.id)return {type:String(x.subject.type).toUpperCase(),id:String(x.subject.id)};if(x?.workBoxId)return {type:'WORKBOX',id:String(x.workBoxId)};if(x?.architectureNodeId)return {type:'ARCHITECTURE_NODE',id:String(x.architectureNodeId)};return null}
function coreTestTarget(x){if(x?.targetType&&x?.targetId)return {type:String(x.targetType).toUpperCase(),id:String(x.targetId)};if(x?.target?.type&&x?.target?.id)return {type:String(x.target.type).toUpperCase(),id:String(x.target.id)};if(x?.workBoxId)return {type:'WORKBOX',id:String(x.workBoxId)};if(x?.taskId)return {type:'TASK',id:String(x.taskId)};return null}
function coreDisplayName(x){return String(x?.name??x?.title??x?.label??x?.id??'')}
function coreStatus(x){return String(x?.status??x?.state??x?.result??'未設定')}
function coreFlag(status){const s=String(status||'').toUpperCase();if(['FAIL','FAILED','ERROR','CONFLICT','不合格'].some(x=>s.includes(x)))return 'failed';if(['HOLD','BLOCKED','未解決','要確認','保留','STALE','UNKNOWN'].some(x=>s.includes(String(x).toUpperCase())))return 'hold';if(['IN_PROGRESS','READY','進行中','ACTIVE','RUNNING'].some(x=>s.includes(String(x).toUpperCase())))return 'active';if(['DONE','PASS','VALID','完了','RESOLVED','PUBLISHED'].some(x=>s.includes(String(x).toUpperCase())))return 'done';return 'neutral'}
function coreEntityRows(p){const c=ensureCoreModel(p),rows=[];const add=(type,list)=>{for(const x of list||[])if(x&&x.id)rows.push({type,id:String(x.id),row:x})};add('ARCHITECTURE_NODE',c.architectureNodes);add('WORKBOX',c.workBoxes);add('REQUIREMENT',c.requirements);add('TASK',c.tasks);add('TEST',c.testDefinitions);add('EVENT',c.eventDefinitions);add('DECISION',c.decisions);add('ISSUE',c.issues);add('CHECK',c.checks);return rows}
function coreEntityMap(p){return new Map(coreEntityRows(p).map(x=>[`${x.type}:${x.id}`,x]))}
function coreEdges(p){
  const c=ensureCoreModel(p),edges=[],add=(fromType,fromId,toType,toId,relation,sourceId='')=>{if(fromId&&toId)edges.push({fromType:String(fromType).toUpperCase(),fromId:String(fromId),toType:String(toType).toUpperCase(),toId:String(toId),relation:String(relation||'RELATED').toUpperCase(),sourceId:String(sourceId||'')})};
  for(const n of c.architectureNodes){const parent=coreNodeParent(n);if(parent)add('ARCHITECTURE_NODE',parent,'ARCHITECTURE_NODE',n.id,'CHILD_NODE',n.id)}
  for(const b of c.workBoxes){const node=coreBoxNode(b),parent=coreBoxParent(b);if(node)add('ARCHITECTURE_NODE',node,'WORKBOX',b.id,'CONTAINS_WORKBOX',b.id);if(parent)add('WORKBOX',parent,'WORKBOX',b.id,'CHILD_WORKBOX',b.id)}
  for(const r of c.requirements)if(r.workBoxId)add('WORKBOX',r.workBoxId,'REQUIREMENT',r.id,'HAS_REQUIREMENT',r.id);
  for(const t of c.tasks){const s=coreTaskSubject(t);if(s)add(s.type,s.id,'TASK',t.id,'SUBJECT_OF_TASK',t.id)}
  for(const t of c.testDefinitions){const target=coreTestTarget(t);if(target)add(target.type,target.id,'TEST',t.id,'TESTED_BY',t.id)}
  for(const e of c.eventDefinitions)if(e.producerTaskId)add('TASK',e.producerTaskId,'EVENT',e.id,'PRODUCES',e.id);
  for(const d of c.taskDependencies)if(d.eventDefinitionId&&d.taskId)add('EVENT',d.eventDefinitionId,'TASK',d.taskId,'REQUIRED_BY',d.id);
  for(const d of c.decisions)if(d.workBoxId)add('WORKBOX',d.workBoxId,'DECISION',d.id,'HAS_DECISION',d.id);
  for(const i of c.issues)if(i.workBoxId)add('WORKBOX',i.workBoxId,'ISSUE',i.id,'HAS_ISSUE',i.id);
  for(const ch of c.checks){if(ch.workBoxId)add('WORKBOX',ch.workBoxId,'CHECK',ch.id,'HAS_CHECK',ch.id);if(ch.taskId)add('TASK',ch.taskId,'CHECK',ch.id,'CHECKED_BY',ch.id);if(ch.requirementId)add('REQUIREMENT',ch.requirementId,'CHECK',ch.id,'CHECKED_BY',ch.id)}
  for(const r of c.relations){if(!r)continue;const f=r.from||{},to=r.to||{};const ft=r.fromType||f.type,fi=r.fromId||f.id,tt=r.toType||to.type,ti=r.toId||to.id;if(ft&&fi&&tt&&ti)add(ft,fi,tt,ti,r.relation||r.type||'RELATED',r.id)}
  return edges;
}
function coreSelectionRow(p){const s=state.coreSelection;if(!s)return null;return coreEntityMap(p).get(`${s.type}:${s.id}`)||null}
function coreEntityButton(type,id,label){return `<button class="core-entity-link" data-core-open="${esc(type)}::${esc(id)}">${esc(label)}</button>`}
function coreOption(value,label,selected){return `<option value="${esc(value)}" ${selected===value?'selected':''}>${esc(label)}</option>`}
function coreAttachedRows(c,boxId){const rows=[];for(const x of c.requirements.filter(x=>x.workBoxId===boxId))rows.push({type:'REQUIREMENT',row:x});for(const x of c.tasks.filter(x=>{const s=coreTaskSubject(x);return s?.type==='WORKBOX'&&s.id===boxId}))rows.push({type:'TASK',row:x});for(const x of c.testDefinitions.filter(x=>{const t=coreTestTarget(x);return t?.type==='WORKBOX'&&t.id===boxId}))rows.push({type:'TEST',row:x});for(const [type,list] of [['DECISION',c.decisions],['ISSUE',c.issues],['CHECK',c.checks]])for(const x of list.filter(x=>x.workBoxId===boxId))rows.push({type,row:x});return rows}
function renderAttachedTable(c,boxId){const rows=coreAttachedRows(c,boxId);if(!rows.length)return '<div class="core-empty">このWorkBoxに紐づくtyped entityはまだありません。</div>';return `<table class="attached-table"><tbody>${rows.map(({type,row})=>`<tr><td><span class="badge">${esc(coreTypeLabels[type]||type)}</span></td><td>${coreEntityButton(type,row.id,coreDisplayName(row)||row.id)}</td><td><span class="flag-pill" data-flag="${coreFlag(coreStatus(row))}">${esc(coreStatus(row))}</span></td></tr>`).join('')}</tbody></table>`}
function renderWorkBoxBranch(c,box,seen=new Set()){if(!box||seen.has(box.id))return '';const next=new Set(seen);next.add(box.id);const attached=coreAttachedRows(c,box.id),health=attached.map(x=>coreFlag(coreStatus(x.row)));const h=health.includes('failed')?'failed':health.includes('hold')?'hold':health.includes('active')?'active':health.length&&health.every(x=>x==='done')?'done':'neutral';const children=c.workBoxes.filter(x=>coreBoxParent(x)===box.id);return `<div class="workbox-card" data-health="${h}" data-workbox-id="${esc(box.id)}"><div class="workbox-head"><div><span class="badge">WorkBox</span> ${coreEntityButton('WORKBOX',box.id,coreDisplayName(box)||box.id)}<div class="core-help"><code>${esc(box.id)}</code> · ${esc(coreStatus(box))}</div></div><span class="flag-pill" data-flag="${h}">${esc(coreStatus(box))}</span></div>${box.description?`<p>${esc(box.description)}</p>`:''}${renderAttachedTable(c,box.id)}${children.length?`<div class="workbox-children">${children.map(x=>renderWorkBoxBranch(c,x,next)).join('')}</div>`:''}</div>`}
function renderArchitectureBranch(c,node,seen=new Set()){if(!node||seen.has(node.id))return '';const next=new Set(seen);next.add(node.id);const nodeBoxes=c.workBoxes.filter(b=>coreBoxNode(b)===node.id),rootBoxes=nodeBoxes.filter(b=>{const p=coreBoxParent(b);return !p||!nodeBoxes.some(x=>x.id===p)}),children=c.architectureNodes.filter(x=>coreNodeParent(x)===node.id);return `<li><div class="architecture-branch"><div class="architecture-node-card" data-node-id="${esc(node.id)}"><div class="architecture-node-head"><div><span class="badge">Architecture</span> ${coreEntityButton('ARCHITECTURE_NODE',node.id,coreDisplayName(node)||node.id)}<div class="core-help"><code>${esc(node.id)}</code></div></div><div class="core-counts"><span class="badge">Box ${nodeBoxes.length}</span><span class="badge">子 ${children.length}</span></div></div>${rootBoxes.length?`<div class="workbox-stack">${rootBoxes.map(b=>renderWorkBoxBranch(c,b)).join('')}</div>`:'<div class="core-empty">このNodeにはWorkBoxがありません。</div>'}</div>${children.length?`<ul>${children.map(x=>renderArchitectureBranch(c,x,next)).join('')}</ul>`:''}</div></li>`}
function renderStructureMap(p){const c=ensureCoreModel(p),ids=new Set(c.architectureNodes.map(x=>x.id)),roots=c.architectureNodes.filter(x=>!coreNodeParent(x)||!ids.has(coreNodeParent(x)));return `<section class="panel structure-shell"><div class="core-form-head"><div><h3>構造マップ</h3><p class="hint">初期構想どおり、Architectureの分岐と各地点のWorkBox・typed entityを一つの構造として表示します。関係は詳細パネルから両方向に辿れます。</p></div><div class="core-counts"><span class="badge">Architecture ${c.architectureNodes.length}</span><span class="badge">WorkBox ${c.workBoxes.length}</span><span class="badge">Task ${c.tasks.length}</span><span class="badge">Test ${c.testDefinitions.length}</span></div></div><div class="structure-map">${roots.length?`<ul class="architecture-tree">${roots.map(n=>renderArchitectureBranch(c,n)).join('')}</ul>`:'<div class="core-empty">ArchitectureNodeがありません。下の登録欄から最初のNodeを作成してください。</div>'}</div></section>`}
function renderCoreInspector(p){const selected=coreSelectionRow(p);if(!selected)return '';const edges=coreEdges(p),map=coreEntityMap(p),incoming=edges.filter(e=>e.toType===selected.type&&e.toId===selected.id),outgoing=edges.filter(e=>e.fromType===selected.type&&e.fromId===selected.id);const rel=(e,side)=>{const type=side==='in'?e.fromType:e.toType,id=side==='in'?e.fromId:e.toId,target=map.get(`${type}:${id}`);return `<div class="core-relation"><div><span class="badge">${esc(e.relation)}</span><br>${target?coreEntityButton(type,id,`${coreTypeLabels[type]||type}: ${coreDisplayName(target.row)||id}`):`<code>${esc(type)}:${esc(id)}</code>`}</div></div>`};return `<section class="core-inspector"><div class="core-inspector-head"><div><h3>${esc(coreTypeLabels[selected.type]||selected.type)} 詳細</h3><strong>${esc(coreDisplayName(selected.row)||selected.id)}</strong><div class="core-help"><code>${esc(selected.id)}</code> · ${esc(coreStatus(selected.row))}</div></div><button id="coreInspectorClose">閉じる</button></div><div class="core-relations"><div class="core-relation-group"><strong>関連元 / 親 / 所属</strong><div class="core-relation-list">${incoming.length?incoming.map(e=>rel(e,'in')).join(''):'<span class="core-help">なし</span>'}</div></div><div class="core-relation-group"><strong>関連先 / 子 / 利用先</strong><div class="core-relation-list">${outgoing.length?outgoing.map(e=>rel(e,'out')).join(''):'<span class="core-help">なし</span>'}</div></div></div><details><summary>レコード</summary><pre class="code">${esc(JSON.stringify(selected.row,null,2))}</pre></details></section>`}
function renderNodeRegister(p){const c=ensureCoreModel(p),parent=String(coreRawDraft('node.parent',''));return `<section class="panel core-register"><form id="coreNodeForm" class="core-form"><div class="core-form-head"><div><h3>ArchitectureNode登録</h3><p class="hint">親を選ぶことで階層・分岐を作ります。親なしならrootです。</p></div></div><div class="core-grid"><label class="field"><span>名称</span><input required name="name" data-core-draft="node.name" value="${coreDraft('node.name')}" /></label><label class="field"><span>親Node</span><select name="parentNodeId" data-core-draft="node.parent"><option value="">root</option>${c.architectureNodes.map(x=>coreOption(x.id,coreDisplayName(x)||x.id,parent)).join('')}</select></label><label class="field full"><span>説明</span><textarea name="description" data-core-draft="node.description">${coreDraft('node.description')}</textarea></label></div><button class="primary" type="submit">ArchitectureNodeを登録</button></form></section>`}
function renderStructure(p){ensureCoreModel(p);return `<div class="structure-shell">${renderStructureMap(p)}${renderCoreInspector(p)}${renderNodeRegister(p)}</div>`}
function renderBoxTab(p){const c=ensureCoreModel(p),node=String(coreRawDraft('box.node','')),parent=String(coreRawDraft('box.parent',''));return `<div class="structure-shell"><section class="panel core-register"><form id="coreBoxForm" class="core-form"><div class="core-form-head"><div><h3>WorkBox登録</h3><p class="hint">WorkBoxはArchitectureNodeへ配置します。必要なら親WorkBoxを指定してBox自身も階層化できます。</p></div></div><div class="core-grid"><label class="field"><span>名称</span><input required name="name" data-core-draft="box.name" value="${coreDraft('box.name')}" /></label><label class="field"><span>状態</span><select name="status" data-core-draft="box.status">${['DRAFT','READY','IN_PROGRESS','HOLD','DONE'].map(x=>coreOption(x,x,String(coreRawDraft('box.status','DRAFT')))).join('')}</select></label><label class="field"><span>配置ArchitectureNode</span><select required name="architectureNodeId" data-core-draft="box.node"><option value="">選択</option>${c.architectureNodes.map(x=>coreOption(x.id,coreDisplayName(x)||x.id,node)).join('')}</select></label><label class="field"><span>親WorkBox</span><select name="parentWorkBoxId" data-core-draft="box.parent"><option value="">なし</option>${c.workBoxes.map(x=>coreOption(x.id,coreDisplayName(x)||x.id,parent)).join('')}</select></label><label class="field full"><span>目的・説明</span><textarea name="description" data-core-draft="box.description">${coreDraft('box.description')}</textarea></label></div><button class="primary" type="submit">WorkBoxを登録</button></form></section><section class="panel"><h3>WorkBox一覧</h3><div class="core-list">${c.workBoxes.length?c.workBoxes.map(x=>`<div class="core-row"><div class="core-row-main">${coreEntityButton('WORKBOX',x.id,coreDisplayName(x)||x.id)}<div class="core-help"><code>${esc(x.id)}</code> · Node ${esc(coreBoxNode(x)||'未設定')} · ${esc(coreStatus(x))}</div></div><span class="flag-pill" data-flag="${coreFlag(coreStatus(x))}">${esc(coreStatus(x))}</span></div>`).join(''):'<div class="core-empty">WorkBoxはまだありません。</div>'}</div></section>${renderCoreInspector(p)}</div>`}
function renderRequirementTab(p){const c=ensureCoreModel(p),box=String(coreRawDraft('req.box',''));return `<div class="structure-shell"><section class="panel core-register"><form id="coreRequirementForm" class="core-form"><div class="core-form-head"><div><h3>要求・仕様登録</h3><p class="hint">仕様をlegacy項目としてではなく、WorkBoxに属するtyped entityとして登録します。</p></div></div><div class="core-grid"><label class="field"><span>名称</span><input required name="name" data-core-draft="req.name" value="${coreDraft('req.name')}" /></label><label class="field"><span>WorkBox</span><select required name="workBoxId" data-core-draft="req.box"><option value="">選択</option>${c.workBoxes.map(x=>coreOption(x.id,coreDisplayName(x)||x.id,box)).join('')}</select></label><label class="field"><span>状態</span><select name="status" data-core-draft="req.status">${['DRAFT','ACTIVE','CONFLICT','DONE'].map(x=>coreOption(x,x,String(coreRawDraft('req.status','DRAFT')))).join('')}</select></label><label class="field full"><span>内容</span><textarea required name="body" data-core-draft="req.body">${coreDraft('req.body')}</textarea></label></div><button class="primary" type="submit">要求・仕様を登録</button></form></section><section class="panel"><h3>要求・仕様一覧</h3><div class="core-list">${c.requirements.length?c.requirements.map(x=>`<div class="core-row"><div class="core-row-main">${coreEntityButton('REQUIREMENT',x.id,coreDisplayName(x)||x.id)}<div class="core-help">WorkBox ${esc(x.workBoxId||'未設定')} · ${esc(coreStatus(x))}</div></div><span class="flag-pill" data-flag="${coreFlag(coreStatus(x))}">${esc(coreStatus(x))}</span></div>`).join(''):'<div class="core-empty">要求・仕様はまだありません。</div>'}</div></section>${renderCoreInspector(p)}</div>`}
function coreSubjectOptions(c,selected=''){const rows=[];for(const x of c.workBoxes)rows.push(coreOption(`WORKBOX::${x.id}`,`WorkBox: ${coreDisplayName(x)||x.id}`,selected));for(const x of c.architectureNodes)rows.push(coreOption(`ARCHITECTURE_NODE::${x.id}`,`Architecture: ${coreDisplayName(x)||x.id}`,selected));for(const x of c.requirements)rows.push(coreOption(`REQUIREMENT::${x.id}`,`要求・仕様: ${coreDisplayName(x)||x.id}`,selected));return rows.join('')}
function renderTaskTab(p){const c=ensureCoreModel(p),subject=String(coreRawDraft('task.subject',''));return `<div class="structure-shell"><section class="panel core-register"><form id="coreTaskForm" class="core-form"><div class="core-form-head"><div><h3>Task登録</h3><p class="hint">TaskはWorkBox / ArchitectureNode / 要求・仕様をsubjectとして明示します。legacy task JSONには埋め込みません。</p></div></div><div class="core-grid"><label class="field"><span>名称</span><input required name="name" data-core-draft="task.name" value="${coreDraft('task.name')}" /></label><label class="field"><span>状態</span><select name="status" data-core-draft="task.status">${['DRAFT','BLOCKED','READY','IN_PROGRESS','HOLD','DONE'].map(x=>coreOption(x,x,String(coreRawDraft('task.status','DRAFT')))).join('')}</select></label><label class="field full"><span>subject</span><select required name="subject" data-core-draft="task.subject"><option value="">選択</option>${coreSubjectOptions(c,subject)}</select></label><label class="field full"><span>目的</span><textarea name="purpose" data-core-draft="task.purpose">${coreDraft('task.purpose')}</textarea></label></div><button class="primary" type="submit">Taskを登録</button></form></section><section class="panel"><h3>Task一覧</h3><div class="core-list">${c.tasks.length?c.tasks.map(x=>{const s=coreTaskSubject(x);return `<div class="core-row"><div class="core-row-main">${coreEntityButton('TASK',x.id,coreDisplayName(x)||x.id)}<div class="core-help">subject ${esc(s?`${s.type}:${s.id}`:'未設定')} · ${esc(coreStatus(x))}</div></div><span class="flag-pill" data-flag="${coreFlag(coreStatus(x))}">${esc(coreStatus(x))}</span></div>`}).join(''):'<div class="core-empty">Taskはまだありません。</div>'}</div></section>${renderCoreInspector(p)}</div>`}
function coreTestTargetOptions(c,selected=''){const rows=[];for(const x of c.workBoxes)rows.push(coreOption(`WORKBOX::${x.id}`,`WorkBox: ${coreDisplayName(x)||x.id}`,selected));for(const x of c.tasks)rows.push(coreOption(`TASK::${x.id}`,`Task: ${coreDisplayName(x)||x.id}`,selected));for(const x of c.requirements)rows.push(coreOption(`REQUIREMENT::${x.id}`,`要求・仕様: ${coreDisplayName(x)||x.id}`,selected));return rows.join('')}
function renderTestTab(p){const c=ensureCoreModel(p),target=String(coreRawDraft('test.target',''));return `<div class="structure-shell"><section class="panel core-register"><form id="coreTestForm" class="core-form"><div class="core-form-head"><div><h3>Test登録</h3><p class="hint">検査定義を独立して登録し、対象を明示します。対象側からもTestを逆引きできます。</p></div></div><div class="core-grid"><label class="field"><span>名称</span><input required name="name" data-core-draft="test.name" value="${coreDraft('test.name')}" /></label><label class="field"><span>対象</span><select required name="target" data-core-draft="test.target"><option value="">選択</option>${coreTestTargetOptions(c,target)}</select></label><label class="field"><span>runner</span><input required name="runner" data-core-draft="test.runner" value="${coreDraft('test.runner','PLAYWRIGHT')}" /></label><label class="field"><span>状態</span><select name="status" data-core-draft="test.status">${['DRAFT','ACTIVE','PASS','FAIL'].map(x=>coreOption(x,x,String(coreRawDraft('test.status','DRAFT')))).join('')}</select></label><label class="field full"><span>command</span><input required name="command" data-core-draft="test.command" value="${coreDraft('test.command')}" /></label><label class="field full"><span>evaluation conditions JSON</span><textarea name="evaluationConditions" class="code" data-core-draft="test.eval">${coreDraft('test.eval','{}')}</textarea></label></div><button class="primary" type="submit">Testを登録</button></form></section><section class="panel"><h3>Test一覧</h3><div class="core-list">${c.testDefinitions.length?c.testDefinitions.map(x=>{const t=coreTestTarget(x);return `<div class="core-row"><div class="core-row-main">${coreEntityButton('TEST',x.id,coreDisplayName(x)||x.id)}<div class="core-help">${esc(x.runner||'')} · target ${esc(t?`${t.type}:${t.id}`:'未設定')} · ${esc(coreStatus(x))}</div></div><span class="flag-pill" data-flag="${coreFlag(coreStatus(x))}">${esc(coreStatus(x))}</span></div>`}).join(''):'<div class="core-empty">Testはまだありません。</div>'}</div></section>${renderCoreInspector(p)}</div>`}
function coreDependencyCycle(c){const graph=new Map(),add=(a,b)=>{if(!graph.has(a))graph.set(a,new Set());graph.get(a).add(b)};for(const e of c.eventDefinitions)if(e.producerTaskId)add(`T:${e.producerTaskId}`,`E:${e.id}`);for(const d of c.taskDependencies)if(d.eventDefinitionId&&d.taskId)add(`E:${d.eventDefinitionId}`,`T:${d.taskId}`);const color=new Map();function visit(n){const v=color.get(n)||0;if(v===1)return true;if(v===2)return false;color.set(n,1);for(const m of graph.get(n)||[])if(visit(m))return true;color.set(n,2);return false}for(const n of graph.keys())if(visit(n))return true;return false}
function renderDependencyTab(p){const c=ensureCoreModel(p),producer=String(coreRawDraft('event.producer','')),depTask=String(coreRawDraft('dep.task','')),depEvent=String(coreRawDraft('dep.event',''));return `<div class="structure-shell"><section class="panel core-register"><form id="coreEventForm" class="core-form"><div class="core-form-head"><div><h3>EventDefinition登録</h3><p class="hint">Taskが生成するEventを独立定義します。</p></div></div><div class="core-grid"><label class="field"><span>Event名称</span><input required name="name" data-core-draft="event.name" value="${coreDraft('event.name')}" /></label><label class="field"><span>producer Task</span><select name="producerTaskId" data-core-draft="event.producer"><option value="">なし</option>${c.tasks.map(x=>coreOption(x.id,coreDisplayName(x)||x.id,producer)).join('')}</select></label></div><button class="primary" type="submit">Eventを登録</button></form><form id="coreDependencyForm" class="core-form"><div class="core-form-head"><div><h3>TaskDependency登録</h3><p class="hint">required Event → dependent Task の正規関係を1件だけ保存し、UIは両方向を逆引きします。</p></div></div><div class="core-grid"><label class="field"><span>dependent Task</span><select required name="taskId" data-core-draft="dep.task"><option value="">選択</option>${c.tasks.map(x=>coreOption(x.id,coreDisplayName(x)||x.id,depTask)).join('')}</select></label><label class="field"><span>required Event</span><select required name="eventDefinitionId" data-core-draft="dep.event"><option value="">選択</option>${c.eventDefinitions.map(x=>coreOption(x.id,coreDisplayName(x)||x.id,depEvent)).join('')}</select></label></div><button class="primary" type="submit">依存を登録</button></form></section><section class="panel"><h3>依存グラフ</h3><div class="core-list">${c.eventDefinitions.length?c.eventDefinitions.map(e=>{const producer=c.tasks.find(t=>t.id===e.producerTaskId),deps=c.taskDependencies.filter(d=>d.eventDefinitionId===e.id);return `<div class="core-row"><div class="core-row-main"><div class="dependency-path">${producer?coreEntityButton('TASK',producer.id,coreDisplayName(producer)||producer.id):'<span>producerなし</span>'}<span class="dependency-arrow">→</span>${coreEntityButton('EVENT',e.id,coreDisplayName(e)||e.id)}${deps.flatMap(d=>{const t=c.tasks.find(x=>x.id===d.taskId);return t?[`<span class="dependency-arrow">→</span>${coreEntityButton('TASK',t.id,coreDisplayName(t)||t.id)}`]:[]}).join('')}</div><div class="core-help"><code>${esc(e.id)}</code> · dependent ${deps.length}</div></div></div>`}).join(''):'<div class="core-empty">Event / Dependencyはまだありません。</div>'}</div></section>${renderCoreInspector(p)}</div>`}
function renderRecordsTab(p){const c=ensureCoreModel(p);const section=(type,title,list)=>`<section class="panel"><h3>${esc(title)}</h3><div class="core-list">${list.length?list.map(x=>`<div class="core-row"><div class="core-row-main">${x.id?coreEntityButton(type,x.id,coreDisplayName(x)||x.id):esc(coreDisplayName(x))}<div class="core-help">${esc(coreStatus(x))}</div></div></div>`).join(''):'<div class="core-empty">記録なし</div>'}</div></section>`;return `<div class="structure-shell">${section('DECISION','Decision',c.decisions)}${section('ISSUE','Issue',c.issues)}${section('CHECK','Check',c.checks)}${renderCoreInspector(p)}</div>`}
function renderWorkspaceTabs(){return workspaceTabs.map(t=>`<button data-tab="${esc(t.key)}" aria-label="${esc(t.aria||t.label)}" class="${state.tab===t.key?'active':''}">${esc(t.label)}</button>`).join('')}
function renderWorkspaceTab(p){if(state.tab==='概要')return renderOverview(p);if(state.tab==='構造')return renderStructure(p);if(state.tab==='Box')return renderBoxTab(p);if(state.tab==='要求・仕様')return renderRequirementTab(p);if(state.tab==='Task')return renderTaskTab(p);if(state.tab==='テスト')return renderTestTab(p);if(state.tab==='依存')return renderDependencyTab(p);if(state.tab==='記録')return renderRecordsTab(p);if(state.tab==='項目')return `<div class="legacy-warning"><strong>互換領域</strong><div>この画面のproject.items / parentId / task.dependsOnは既存案件互換のみです。新規構造はArchitecture / WorkBox / typed entity側へ登録してください。</div></div>${renderItems(p)}`;if(state.tab==='AI引き継ぎ')return renderAi();return renderRaw(p)}
function coreRefExists(c,type,id){type=String(type||'').toUpperCase();const map={ARCHITECTURE_NODE:c.architectureNodes,WORKBOX:c.workBoxes,REQUIREMENT:c.requirements,TASK:c.tasks,TEST:c.testDefinitions,EVENT:c.eventDefinitions,DECISION:c.decisions,ISSUE:c.issues,CHECK:c.checks};return Boolean((map[type]||[]).some(x=>x.id===id))}
function coreParentCycle(list,idFn,parentFn){const byId=new Map(list.filter(Boolean).map(x=>[idFn(x),x]));for(const start of byId.keys()){const seen=new Set();let cur=start;while(cur){if(seen.has(cur))return true;seen.add(cur);const row=byId.get(cur);cur=row?parentFn(row):null}}return false}
function validateCoreModel(p){const c=ensureCoreModel(p),issues=[];for(const k of coreArrayKeys){const seen=new Set();for(const x of c[k]){if(!x||!x.id)continue;if(seen.has(x.id))issues.push(`${k} ID重複: ${x.id}`);seen.add(x.id)}}if(coreParentCycle(c.architectureNodes,x=>x.id,coreNodeParent))issues.push('ArchitectureNodeの親子が循環しています');if(coreParentCycle(c.workBoxes,x=>x.id,coreBoxParent))issues.push('WorkBoxの親子が循環しています');const nodeIds=new Set(c.architectureNodes.map(x=>x.id)),boxIds=new Set(c.workBoxes.map(x=>x.id));for(const b of c.workBoxes.filter(x=>x?.uiModelVersion===4)){if(!nodeIds.has(coreBoxNode(b)))issues.push(`WorkBox ${b.id} のArchitectureNodeが存在しません`);const parent=coreBoxParent(b);if(parent&&!boxIds.has(parent))issues.push(`WorkBox ${b.id} の親WorkBoxが存在しません`)}for(const r of c.requirements.filter(x=>x?.uiModelVersion===4))if(!boxIds.has(r.workBoxId))issues.push(`要求・仕様 ${r.id} のWorkBoxが存在しません`);for(const t of c.tasks.filter(x=>x?.uiModelVersion===4)){const s=coreTaskSubject(t);if(!s||!coreRefExists(c,s.type,s.id))issues.push(`Task ${t.id} のsubjectが存在しません`)}for(const t of c.testDefinitions.filter(x=>x?.uiModelVersion===4)){const target=coreTestTarget(t);if(!target||!coreRefExists(c,target.type,target.id))issues.push(`Test ${t.id} のtargetが存在しません`)}for(const e of c.eventDefinitions.filter(x=>x?.uiModelVersion===4))if(e.producerTaskId&&!coreRefExists(c,'TASK',e.producerTaskId))issues.push(`Event ${e.id} のproducer Taskが存在しません`);for(const d of c.taskDependencies.filter(x=>x?.uiModelVersion===4)){if(!coreRefExists(c,'TASK',d.taskId))issues.push(`TaskDependency ${d.id} のTaskが存在しません`);if(!coreRefExists(c,'EVENT',d.eventDefinitionId))issues.push(`TaskDependency ${d.id} のEventが存在しません`)}if(coreDependencyCycle(c))issues.push('Task / Event dependency が循環しています');return [...new Set(issues)]}
function applyCoreMutation(label,mutator){if(!state.active)return;const next=clone(state.active.project);try{const c=ensureCoreModel(next);mutator(c,next);const issues=validateCoreModel(next);if(issues.length)throw new Error(issues.join(' / '));markDirty();state.active.project.core=next.core;state.coreDrafts={};state.message={type:'success',text:`${label}を編集内容へ反映しました。GitHub保存はまだです。`};render()}catch(e){state.message={type:'error',text:e.message};render()}}
function parseCoreRef(value){const [type,...rest]=String(value||'').split('::');return {type:type.toUpperCase(),id:rest.join('::')}}
function bindCoreDrafts(){document.querySelectorAll('[data-core-draft]').forEach(el=>{const save=()=>{state.coreDrafts=state.coreDrafts||{};state.coreDrafts[el.dataset.coreDraft]=el.value};el.oninput=save;el.onchange=save})}
function bindCoreUI(){if(!state.active)return;bindCoreDrafts();document.querySelectorAll('[data-core-open]').forEach(b=>b.onclick=()=>{const [type,...rest]=String(b.dataset.coreOpen||'').split('::');state.coreSelection={type,id:rest.join('::')};render()});$('#coreInspectorClose')&&($('#coreInspectorClose').onclick=()=>{state.coreSelection=null;render()});const form=(id,handler)=>{const f=$(`#${id}`);if(f)f.onsubmit=e=>{e.preventDefault();handler(new FormData(f))}};form('coreNodeForm',fd=>applyCoreMutation('ArchitectureNode',c=>c.architectureNodes.push({uiModelVersion:4,id:coreId('architecture-node'),name:String(fd.get('name')||'').trim(),parentNodeId:String(fd.get('parentNodeId')||'')||null,description:String(fd.get('description')||''),status:'ACTIVE'})));form('coreBoxForm',fd=>applyCoreMutation('WorkBox',c=>c.workBoxes.push({uiModelVersion:4,id:coreId('workbox'),name:String(fd.get('name')||'').trim(),architectureNodeId:String(fd.get('architectureNodeId')||''),parentWorkBoxId:String(fd.get('parentWorkBoxId')||'')||null,status:String(fd.get('status')||'DRAFT'),description:String(fd.get('description')||'')})));form('coreRequirementForm',fd=>applyCoreMutation('要求・仕様',c=>c.requirements.push({uiModelVersion:4,id:coreId('requirement'),name:String(fd.get('name')||'').trim(),workBoxId:String(fd.get('workBoxId')||''),status:String(fd.get('status')||'DRAFT'),body:String(fd.get('body')||'')})));form('coreTaskForm',fd=>{const s=parseCoreRef(fd.get('subject'));applyCoreMutation('Task',c=>c.tasks.push({uiModelVersion:4,id:coreId('task'),name:String(fd.get('name')||'').trim(),subjectType:s.type,subjectId:s.id,status:String(fd.get('status')||'DRAFT'),purpose:String(fd.get('purpose')||'')}))});form('coreTestForm',fd=>{let evaluationConditions={};try{evaluationConditions=JSON.parse(String(fd.get('evaluationConditions')||'{}'))}catch{state.message={type:'error',text:'evaluation conditions JSONが不正です'};render();return}const target=parseCoreRef(fd.get('target'));applyCoreMutation('Test',c=>c.testDefinitions.push({uiModelVersion:4,id:coreId('test'),name:String(fd.get('name')||'').trim(),targetType:target.type,targetId:target.id,runner:String(fd.get('runner')||'').trim(),command:String(fd.get('command')||''),evaluationConditions,status:String(fd.get('status')||'DRAFT')}))});form('coreEventForm',fd=>applyCoreMutation('EventDefinition',c=>c.eventDefinitions.push({uiModelVersion:4,id:coreId('event'),name:String(fd.get('name')||'').trim(),producerTaskId:String(fd.get('producerTaskId')||'')||null,status:'DEFINED'})));form('coreDependencyForm',fd=>applyCoreMutation('TaskDependency',c=>{const taskId=String(fd.get('taskId')||''),eventDefinitionId=String(fd.get('eventDefinitionId')||'');if(c.taskDependencies.some(x=>x.taskId===taskId&&x.eventDefinitionId===eventDefinitionId))throw new Error('同じTaskDependencyが既にあります');c.taskDependencies.push({uiModelVersion:4,id:coreId('task-dependency'),taskId,eventDefinitionId})}))}
'''

raw = raw.replace(inject_anchor, block + '\n' + inject_anchor, 1)

old_tabs = "<div class=\"tabs\">${['概要','項目','AI引き継ぎ','高度なJSON'].map(t=>`<button data-tab=\"${t}\" class=\"${state.tab===t?'active':''}\">${t}</button>`).join('')}</div>"
if old_tabs not in raw:
    raise SystemExit('tabs anchor missing')
raw = raw.replace(old_tabs, '<div class="tabs">${renderWorkspaceTabs()}</div>', 1)

old_content = "${state.tab==='概要'?renderOverview(p):state.tab==='項目'?renderItems(p):state.tab==='AI引き継ぎ'?renderAi():renderRaw(p)}"
if old_content not in raw:
    raise SystemExit('content router anchor missing')
raw = raw.replace(old_content, '${renderWorkspaceTab(p)}', 1)

bind_anchor = "$('#rawApply')&&($('#rawApply').onclick=rawApply);if(state.modal){"
if bind_anchor not in raw:
    raise SystemExit('bind anchor missing')
raw = raw.replace(bind_anchor, "$('#rawApply')&&($('#rawApply').onclick=rawApply);bindCoreUI();if(state.modal){", 1)

raw = raw.replace("state.tab='概要'", "state.tab='構造'")
raw = raw.replace("tab:'概要'", "tab:'構造'")
raw = raw.replace('<h3>項目</h3><p class="hint">全${p.items.length}件。', '<h3>互換項目（legacy）</h3><p class="hint">全${p.items.length}件。')

if 'C04_STRUCTURE_UI_V4' not in raw:
    raw = "/* C04_STRUCTURE_UI_V4: Architecture/WorkBox/typed-entity first-class UI; legacy items compatibility-only. */\n" + raw

compiled = gzip.compress(raw.encode('utf-8'), compresslevel=9, mtime=0)
src_path.write_text(base64.b64encode(compiled).decode('ascii'))
Path('/tmp/c04-v4-app.js').write_text(raw)
print('patched bytes', len(raw))
